### ISSUE TITLE
Feature Request: append host info to "version" command

### ISSUE THREAD

**Issue by chiefy** [boot2docker/boot2docker#1001]
Per #938 

Assuming that this should always be true:

``` bash
$ docker --version && b2d ssh docker --version
Docker version 1.7.1, build 786b29d
Docker version 1.7.1, build 786b29d
```

It'd be nice if you could:

``` bash
$ boot2docker --version
```

And get back some kind of information about both client **and** host. Knowing the versions of stuff on the host can make troubleshooting much easier amongst other handy things.

``` bash
$ boot2docker --version
boot2docker client version: 1.7.1
host running docker: 1.7.0
host listening on tcp://0.0.0.0:2376
```

**Comment by jakirkham** [comment]
To summarize, you would like `boot2docker --version` to include the version of `boot2docker` and `docker`. If I understand you correctly, I agree, as well.

**Comment by jakirkham** [comment]
Though the move has been towards dropping the `--` so I would like to see it work in that case.

**Comment by chiefy** [comment]
@jakirkham most cli's I use these days use `--version` or `version` so either or both would be great.

**Comment by jakirkham** [comment]
I just don't see `boot2docker --version` currently, but I would also be happy with both.

**Comment by jakirkham** [comment]
@tianon, wanted to bring this to your attention as I think it would help when debugging issues raised here.
