### ISSUE TITLE
Name Pipes do not get mounted properly

### ISSUE THREAD

**Issue by martinvelez** [boot2docker/boot2docker#1002]
I am using a Mac.

1) I create a named pipe called `pin` with `mkfifo pin`.  
2) I start a container.  I load the folder containing the named pipe `pin` as a volume.  The volume gets loaded correctly except for named pipes.
3) I start a container and open a shell; `docker run -it -v ....`.
4) Within the container shell, I attempt to read from the pipe; `cat pin`.
5) Within the host shell, I write to the pipe; `echo 1 > pin`.

I expect step 4 to wait until I complete step 5.  It does but instead of output `1` I get an error message: `cat: pin: Protocol error`.

Is this a boot2docker issue or a VirtualBox issue?

**Comment by rayjohnson** [comment]
Did you get an answer to this?  I have the same question...

**Comment by martinvelez** [comment]
I never found a way to work around this.  It seems to be by design.  Name pipes are not preserved as such in the VM fired up by boot2docker.

**Comment by md5** [comment]
@martinvelez I'm not sure "by design" is the way to put it. It's more "by omission". I really doubt than anything except local filesystems support named pipes.
