### ISSUE TITLE
Boot2Docker won't start

### ISSUE THREAD

**Issue by jaredpetersen** [boot2docker/boot2docker#1010]
## Issue:
I am unable to start a docker instance.

## Steps Taken:

Initializing Boot2Docker via the shortcut produces the following response (sorry for the low res, I was barely able to capture it because the window disappears immediately):

![errorinit](https://cloud.githubusercontent.com/assets/8802128/8910532/33f286a6-343c-11e5-9f7a-f2a29639026f.png)
This occurs regardless of whether the VM has already been created or not.

If I go in and try to run it via the command line manually (with verbose output), I get this:

![unablerun](https://cloud.githubusercontent.com/assets/8802128/8910423/7921efce-343b-11e5-8646-131c891afba9.png)

Trying to start the Docker ISO via VirtualBox produces the following error:

![vboxerror](https://cloud.githubusercontent.com/assets/8802128/8910636/bd3593ea-343c-11e5-8610-f2ac47076abf.png)

Researching the VirtualBox error brought me to https://github.com/boot2docker/windows-installer/issues/39, which is only related to VirtualBox version 4.3.14

## Environment:
Windows 7
Boot2Docker release 1.7.1
VirtualBox 4.30.30 r101610 (Included in the Windows Installer)

**Comment by jaredpetersen** [comment]
Please let me know if you would like me to post the log file from VirtualBox.

**Comment by jakirkham** [comment]
Dup of boot2docker/boot2docker#999.

**Comment by jaredpetersen** [comment]
@jakirkham Sorry, I didn't see yours earlier when looking around. I'll close this and comment on your issue so that the repository owners have a little more information to work off of.

**Comment by jakirkham** [comment]
@jaredpetersen, not a problem. It happens. Thanks.
