### ISSUE TITLE
Windows 10 issue

### ISSUE THREAD

**Issue by Grafikart** [boot2docker/boot2docker#1014]
I know this early but I wanted to point out a problem I got after upgrading to windows 10 (I reinstalled VBox and Boot2Docker to be sure)

When I boot2docker init I have an error message, this is what the machine is saying 

![](https://sc-cdn.scaleengine.net/i/95d912a5ef56588886edf65147220c883.png)

With further investigations I found that the machine configuration seems to be a bit brokent 

![](https://sc-cdn.scaleengine.net/i/3768afa4633774aa542908c3cdeb7cb11.png)

It's broken using boot2docker or docker-machine. If you need me to do more test and show more logs I can do it

**Comment by mr47** [comment]
Follow instructions on https://www.virtualbox.org/ticket/14040#comment:36
