### ISSUE TITLE
unable to run boot2docker-vm in windows

### ISSUE THREAD

**Issue by csrajmohan** [boot2docker/boot2docker#1016]
I am having issues with Boot2Docker for Windows in windows 7. When I run the "start.sh" script for starting Boot2Docker, after initializing the boot2docker-vm, starting the vm fails.

C:\Program Files\Boot2Docker\Boot2Docker for Windows>boot2docker up
error in run: Failed to start machine "boot2docker-vm": exit status 1

C:\Program Files\Boot2Docker\Boot2Docker for Windows>boot2docker start
error in run: Failed to start machine "boot2docker-vm": exit status 1

I have tried uninstalling and re-installing. It did not help. I have deleted the boot2docker-vm and tried which also did not help. When I open Oracle VM VirtualBox manager, it is showing the VM "boot2docker-vm" with state Powered-Off and I could not start the VM from there as well.

Any help on how to fix this problem?

**Comment by jakirkham** [comment]
Dup of #999.
