### ISSUE TITLE
Unable to download iso for 1.7.1: connection reset by peer

### ISSUE THREAD

**Issue by fiunchinho** [boot2docker/boot2docker#1030]
I'm trying to upgrade to 1.7.1 but it fails trying to download the ISO. If I try to download the iso manually through the browser from https://github.com/boot2docker/boot2docker/releases, it also fails. It seems a problem with S3.
Is there any mirror where I can download it?

    $> boot2docker upgrade
    docker is up to date (1.7.1), skipping upgrade...
    boot2docker is up to date (v1.7.1), skipping upgrade...
    Latest release for github.com/boot2docker/boot2docker is v1.7.1
    Downloading boot2docker ISO image...
    error in run: Failed to download ISO image: read tcp 54.231.64.248:443: connection reset by peer

Thanks

**Comment by plamola** [comment]
Seeing the same problem

```bash
$> boot2docker -v download
Boot2Docker-cli version: v1.7.1
Git commit: 8fdc6f5
Latest release for github.com/boot2docker/boot2docker is v1.7.1
Downloading boot2docker ISO image...
error in run: Failed to download ISO image: read tcp 54.231.64.128:443: connection reset by peer
```

**Comment by gregory90** [comment]
It's probably due to S3 Outage in US Standard region:
https://news.ycombinator.com/item?id=10033172

**Comment by plamola** [comment]
Indeed. 

Now Amazon reports the error rates are dropping, I was able to download the image.
