### ISSUE TITLE
boot2docker interface for Docker Toolbox/Machine

### ISSUE THREAD

**Issue by nordicdyno** [boot2docker/boot2docker#1038]
Please, don't drop the boot2docker! It have much more clean and simple interface than new Docker toolbox.
For great good!

**Comment by SvenDowideit** [comment]
you have an interesting point - @nathanleclaire and I were just talking about the difference in UX, and you're right, we could make the boot2docker-cli a simplified frontend for docker-machine.

**Comment by nordicdyno** [comment]
:+1:
