### ISSUE TITLE
Installing docker-compose to boot2docker

### ISSUE THREAD

**Issue by michbil** [boot2docker/boot2docker#1055]
Was using boot2docker shell to install docker-compose cross-platformly to windows and mac with this command:
```
tce-load -wi python && curl https://bootstrap.pypa.io/get-pip.py  | sudo python - && sudo pip install -U docker-compose
```
After recent python.tcz repository update, can't install pip anymore. I'm using this command line

Getting this error
```
Traceback (most recent call last):
  File "<stdin>", line 17759, in <module>
  File "<stdin>", line 162, in main
  File "<stdin>", line 82, in bootstrap
  File "/tmp/tmpbuE2Di/pip.zip/pip/__init__.py", line 15, in <module>
  File "/tmp/tmpbuE2Di/pip.zip/pip/vcs/subversion.py", line 9, in <module>
  File "/tmp/tmpbuE2Di/pip.zip/pip/index.py", line 30, in <module>
  File "/tmp/tmpbuE2Di/pip.zip/pip/wheel.py", line 35, in <module>
  File "/tmp/tmpbuE2Di/pip.zip/pip/_vendor/distlib/scripts.py", line 14, in <module>
  File "/tmp/tmpbuE2Di/pip.zip/pip/_vendor/distlib/compat.py", line 31, in <module>
ImportError: cannot import name HTTPSHandler
```

Will appreciate for any help. Also would be good if you point me, where i can download old version of python.tcz
I've seen this changes in tcz repository changelog, so i think it is related.

```
python.tcz
Description:    Python programming language
Current:        2015/09/04 recompiled for updated openssl (juanito)
Uploaded on Sat Sep 05 10:37
 
####################################################
```

**Comment by rivaros** [comment]
Hi @michbil, Just yesterday got the same error as you.
This is a probably a bug with recent Tiny Core repository latest updates (2 days ago it was working :))

Could anybody of the boot2docker team test this:

1. Launch new docker-machine
2. Run tce-load -w -i python.tcz gmp-dev.tcz python-dev.tcz compiletc.tcz
3. Run
wget https://bootstrap.pypa.io/get-pip.py
sudo python get-pip.py

You will get the ImportError: cannot import name HTTPSHandler

I was speaking with TinyCore maintainer in #tinycorelinux irc channel yesterday but he tells that this is problem of boot2docker.

**Comment by michbil** [comment]
I've asked TinyCore guys, they said that they don't offer any support TinyCore respins.
After that i've downloaded and installed vanilla tinycorex64 on VirtualBox. Install succeed.
So problem after recent changes only on boot2docker OS.

**Comment by SvenDowideit** [comment]
I don't use compose as much as i should, but I really do wonder why you'd install it into the vm.

I pretty much always reach for my `svendowideit/compse` image: https://hub.docker.com/r/svendowideit/compose/

**Comment by michbil** [comment]
@SvenDowideit this method was taken from http://stackoverflow.com/questions/29289785/how-to-install-docker-compose-on-windows and it worked quite well before recent changes.

**Comment by rivaros** [comment]
@SvenDowideit , your solution with docker-compose is really smart (by mapping docker.sock as a volume inside the container), but what about the actual issue from @michbil ?

It's not about docker-compose in particular but some bug with installing pip on boot2docker. Do you know how this may be solved?

**Comment by Baggerone** [comment]
This is an issue for me and my colleagues as well.  Same symptoms.

**Comment by md5** [comment]
It appears that `python.tcz` requires `openssl.tcz`, but that package conflicts with the already installed `openssl-1.0.0.tcz` because they both try to supply `/usr/local/lib/libssl.so.1.0.0`.

It might be worth rebuilding the ISO with the `openssl-1.0.0` on this line changed to `openssl`: https://github.com/boot2docker/boot2docker/blob/eb5571f185ef46ccbb14b74ce969eff0327f8dfd/Dockerfile#L68

**Comment by md5** [comment]
I had a chance to test out replacing `openssl-1.0.0` in the build with `openssl` and it looks like it works fine.

Here's a list of executables that depend on `libssl.so.1.0.0`:

```console
$ find 2>/dev/null / -xdev -perm -0111 -type f -print -exec ldd {} \; | grep -e ^/ -e libssl | grep -B1 libssl
/usr/local/bin/openssl
	libssl.so.1.0.0 => /usr/local/lib/libssl.so.1.0.0 (0x00007f0cc58af000)
--
/usr/local/bin/curl
	libssl.so.1.0.0 => /usr/local/lib/libssl.so.1.0.0 (0x00007f14d493c000)
--
/usr/local/lib/git-core/git-http-push
	libssl.so.1.0.0 => /usr/local/lib/libssl.so.1.0.0 (0x00007f4bc9211000)
--
/usr/local/lib/git-core/git-imap-send
	libssl.so.1.0.0 => /usr/local/lib/libssl.so.1.0.0 (0x00007f5a6b7a5000)
/usr/local/lib/git-core/git-http-fetch
	libssl.so.1.0.0 => /usr/local/lib/libssl.so.1.0.0 (0x00007f5e944db000)
--
/usr/local/lib/git-core/git-remote-ftps
	libssl.so.1.0.0 => /usr/local/lib/libssl.so.1.0.0 (0x00007fe7900d3000)
/usr/local/lib/git-core/git-remote-http
	libssl.so.1.0.0 => /usr/local/lib/libssl.so.1.0.0 (0x00007ff9fd9f7000)
/usr/local/lib/git-core/git-remote-https
	libssl.so.1.0.0 => /usr/local/lib/libssl.so.1.0.0 (0x00007fa0b7aed000)
/usr/local/lib/git-core/git-remote-ftp
	libssl.so.1.0.0 => /usr/local/lib/libssl.so.1.0.0 (0x00007f20f5c5e000)
--
/usr/local/lib/libcurl.so.4.3.0
	libssl.so.1.0.0 => /usr/local/lib/libssl.so.1.0.0 (0x00007ff15a53c000)
/usr/local/lib/libssl.so.1.0.0
```

Based on that list, I tested `curl` with an HTTPS URL, `git` with an `https` remote, and `openssl req` to make sure they actually worked.

I then ran @michbil's original command and it succeeded, finishing with this:

```
Successfully built docker-compose docopt PyYAML texttable websocket-client docker-py dockerpty
Installing collected packages: docopt, PyYAML, requests, texttable, six, websocket-client, docker-py, dockerpty, docker-compose
Successfully installed PyYAML-3.11 docker-compose-1.4.0 docker-py-1.3.1 dockerpty-0.3.4 docopt-0.6.2 requests-2.6.2 six-1.9.0 texttable-0.8.3 websocket-client-0.32.0
```

I've opened https://github.com/boot2docker/boot2docker/pull/1056 with the change.

**Comment by michbil** [comment]
Updated to 1.8.2, problem gone. Thank you @md5 for fast solution.

**Comment by md5** [comment]
@michbil :+1:
