### ISSUE TITLE
VMWare Shared Folders not working on boot2docker v1.8.3

### ISSUE THREAD

**Issue by mixja** [boot2docker/boot2docker#1077]
My environment is:

- OS X El Capitan (10.11.0)
- VMWare Fusion 7.1.2

With **boot2docker v1.8.3** nothing is present in /Users:

```bash
Boot2Docker version 1.8.3, build master : af8b089 - Mon Oct 12 18:56:54 UTC 2015
Docker version 1.8.3, build f4bf5c7
docker@docker02:~$ cd /Users/
docker@docker02:/Users$ ls
```

With **boot2docker v1.8.2**:

```bash
Boot2Docker version 1.8.2, build master : aba6192 - Thu Sep 10 20:58:17 UTC 2015
Docker version 1.8.2, build 0a8c2e3
docker@docker03:~$ ls /Users
Guest/  Shared/ myusername/
```

I can confirm that `/mnt/hgfs` is present and all shared files are available under `/mnt/hgfs/Users`:

```bash
docker@docker02:/$ ls /mnt/hgfs/Users/
Guest/  Shared/ myusername/
```

Running the `vmhgfs-fuse -e` command has the following output:

```bash
root@docker02:~# vmhgfs-fuse -e
failed to access /bin/fusermount or /usr/bin/fusermount 2
vmhgfs-fuse: 2 - HGFS FUSE client needs FUSE environment
```

So looks to be an issue with the new VMHGFS FUSE support, which calls `/usr/local/bin/vmhgfs-fuse -o allow_other .host:/ /mnt/hgfs` in the `/etc/rc.d/vmtoolsd` startup script.

**Comment by robertwe** [comment]
Im on Fusion 8.0.1 and got exactly same issue.

**Comment by gravis** [comment]
same here

**Comment by gravis** [comment]
(quickfix: `docker-machine create -d vmwarefusion --vmwarefusion-boot2docker-url https://github.com/boot2docker/boot2docker/releases/download/v1.8.2/boot2docker.iso fusion`) :(

**Comment by tianon** [comment]
cc @frapposelli

**Comment by frapposelli** [comment]
@mixja @robertwe @gravis are you guys using `docker-machine` to bring the environment up?

**Comment by gravis** [comment]
Yup

**Comment by frapposelli** [comment]
@gravis you guys are most likely using a version of `docker-machine` that doesn't support the new FUSE-based shared folder implementation, see docker/machine#1995 quick fix: compile `docker-machine` from HEAD.

**Comment by gravis** [comment]
Thanks!

**Comment by t6d** [comment]
I'm experiencing the same issue with two different versions of Fusion: Fusion 7.1.2 and Fusion 8.0.1. Downgrade to 1.8.2 fixed the problem for me.

**Comment by mixja** [comment]
@frapposelli - confirming that using latest <a href="https://github.com/docker/machine/releases/tag/v0.5.0-rc4" target="_blank">docker-machine v0.5.0-rc4 release</a> fixes this issue

**Comment by mkorthuis** [comment]
Confirming the latest docker toolbox works.  (docker-machine v0.5.0 and bootdocker 1.9.0b)

**Comment by frapposelli** [comment]
@tianon I think we can safely close this.

**Comment by tianon** [comment]
Rock on :+1:
