### ISSUE TITLE
How can I do to Disable Transparent Huge Pages?

### ISSUE THREAD

**Issue by sebicas** [boot2docker/boot2docker#1083]
I am getting some warnings on a few containers ( Redis & Mongo )

```
** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
**        We suggest setting it to 'never'

** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
**        We suggest setting it to 'never'
```

And as far as can I read on https://github.com/docker-library/redis/issues/20#issuecomment-76066090 is a host ( boot2docker on VirtualBox ) issue.

How can I do to set this kernel flags as 'never' as suggested?

```
docker-machine version 0.4.1 (e2c88d6)
Boot2Docker version 1.8.2, build master : aba6192 - Thu Sep 10 20:58:17 UTC 2015
Docker version 1.8.2, build 0a8c2e3
```

**Comment by md5** [comment]
You can add these lines to the end of `/var/lib/boot2docker/profile`:

```console
echo never > /sys/kernel/mm/transparent_hugepage/enabled 
echo never > /sys/kernel/mm/transparent_hugepage/defrag
```

That will cause the kernel settings to be loaded after a reboot. If you want them to take effect without a reboot as well, you can do this:

```console
echo never | sudo tee /sys/kernel/mm/transparent_hugepage/enabled 
echo never | sudo tee /sys/kernel/mm/transparent_hugepage/defrag
```

**Comment by sebicas** [comment]
/var/lib/boot2docker/profile doesn't exist on my computer, I just created it but nothing happens.

I am using:
```
docker-machine version 0.4.1 (e2c88d6)
Boot2Docker version 1.8.2, build master : aba6192 - Thu Sep 10 20:58:17 UTC 2015
Docker version 1.8.2, build 0a8c2e3
```

**Comment by tianon** [comment]
He meant inside the VM, not on your computer. :)

**Comment by sebicas** [comment]
Ahh! Great thanks! I will try that then!

**Comment by sebicas** [comment]
It works perfectly! Thanks!

**Comment by md5** [comment]
@tianon Would `bootlocal.sh` or `bootsync.sh` be better than `profile`?

**Comment by brandontamm** [comment]
@md5 - did you ever determine if bootlocal.sh or bootsync.sh would be better to save these changes to vs. the profile?

**Comment by tianon** [comment]
https://github.com/boot2docker/boot2docker/blob/057e76a8cd6755415b42dea7b4b9185c5aae7ae4/rootfs/rootfs/bootscript.sh#L72

I'd vote `bootsync.sh` making the most sense, since it starts right before Docker does, but only on startup (not every time the daemon is restarted).

**Comment by arianitu** [comment]
How do I disable this when running on Docker native? I can't ssh to the VM to change these settings.

**Comment by arianitu** [comment]
You can actually do this with a privileged container in Docker native. You can do it like this:

    docker run -ti --privileged ubuntu /bin/bash
    echo never | tee /sys/kernel/mm/transparent_hugepage/enabled
    echo never | tee /sys/kernel/mm/transparent_hugepage/defrag
    
I ended up creating an image for this and made redis/mariadb include it under depends_on in my docker-compose.yml file

    FROM ubuntu:latest
    COPY ./docker-entrypoint.sh /
    ENTRYPOINT ["/docker-entrypoint.sh"]

where docker-entrypoint.sh has:

    #!/bin/bash
    set -e

    echo never | tee /sys/kernel/mm/transparent_hugepage/enabled
    echo never | tee /sys/kernel/mm/transparent_hugepage/defrag
