### ISSUE TITLE
hostname is set after DHCP starts

### ISSUE THREAD

**Issue by metcalfc** [boot2docker/boot2docker#1096]
Currently in the bootscript the hostname is set after DHCP client starts. The result is that all boot2docker instances report the same name `box` to the DHCP server. I am trying to use dnsmasq to automatically setup DNS for my boot2docker instances and this prevents that from working.

Pretty simple fix. Pull up setting the hostname to before starting the DHCP client.

PR incoming.

**Comment by up4** [comment]
Hello, I can see that the boot script has the proper initialization order, but I'm still getting no luck with dnsmasq.

I also set changed the host name with the "host" kernel boot param and in `/var/lib/boot2docker/etc/hostname`.

The `hostname` command returns the correct name.

Is there a way my dhcp server can receive the hostname as part of the dhcp request? Thanks.

**Comment by tianon** [comment]
@up4 not sure -- we're using TCL's `dhcp` script as-is, but I'm not sure whether it supports that :confused:

**Comment by up4** [comment]
Hi thanks for the reply. I will see if on the TCL side if people are complaining about that and will be back here if I ever find something. Thanks again.
