### ISSUE TITLE
Docker 1.9.1 hanging at build step "Setting up ca-certificates-java"

### ISSUE THREAD

**Issue by tiborvass** [boot2docker/boot2docker#1099]
From https://github.com/docker/docker/issues/18180

Could be due to https://github.com/boot2docker/boot2docker/commit/9a96c5a65ebc1a556cbce91f689e3615ec43741f

Ping @tianon

**Comment by jamshid** [comment]
Thanks! In case anyone else wants a boot2docker.iso image that downgrades aufs to avoid blocking bug docker/docker#18180 but wants to keep using docker 1.9.1:
```
git clone https://github.com/boot2docker/boot2docker.git
cd boot2docker
git checkout v1.9.1
<edit Dockerfile, changing AUFS_COMMIT to older e8b6a1538ae1aa8e5ad1d7c6d843dbf835b6af2a>
docker build -t boot2docker-fix .
docker-machine stop dev
docker run boot2docker-fix > ~/.docker/machine/machines/dev/boot2docker.iso
docker-machine start dev
```
Hopefully nothing in docker 1.9.1 depends on the newer aufs.

**Comment by tianon** [comment]
This is confirmed to be a general kernel issue (not specific to b2d, but something introduced in the latest 3.1 kernel) interacting strangely with AUFS and Java.  Please see https://github.com/docker/docker/issues/18180 for the latest on what's being done to track down the bug (kernel bisect necessary, which is very time consuming both in machine power and human power).

**Comment by jamshid** [comment]
@tianon, just one user's opinion but this seems like a serious enough issue to warrant a new release of boot2docker (and toolbox) that downgrades the kernel or aufs while preserving docker 1.9.1.

**Comment by stremlenye** [comment]
@jamshid Thanks for your workaround.
Only one question: how long should take the last step?
For me it is running about 10 minutes already and haven't stopped yet.

**Comment by stremlenye** [comment]
Yep, finally failed for me with:
```
Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
```

**Comment by jamshid** [comment]
@stremlenye It did take a long time and I got at least one failure from an apt-get, so I had to rerun `docker build .`. I attached the iso I'm using to https://gist.github.com/jamshid/05005c1ab90bc51a8715, if you're trusting.

**Comment by andrewgdavis** [comment]
did this work for other folks?  maybe i mangled something in the process (it did not work for me, but technically i used a different AUFS commit)

and if it does work, this means that kernel version 4.1.13 is ok with an older version of AUFS?  thus AUFS should then be git bisected to find the offending commit?

**Comment by jamshid** [comment]
*CORRECTION* that aufs revert fixes the _defunct java_ problem in one environment (server booted off usb boot2docker.iso), but it does *not* fix the problem in my local virtual box on OSX. Sorry for the confusion, I had been trying a couple of different things. I'm going to go back to boot2docker 1.9.0 with only /usr/local/bin/docker replaced with 1.9.1 at startup.

**Comment by stremlenye** [comment]
I've downgraded a little bit deeper sot to say: to boot2docker 1.8.3 and docker 1.7.3 (previous version available via brew)

**Comment by stremlenye** [comment]
@jamshid Does boot2docker 1.9.0 solved java defunct problem?

**Comment by jamshid** [comment]
@stremlenye Yes, I didn't see the defunct java problem with 1.9.0, and I don't see it on boot2docker 1.9.0 with /usr/local/bin/docker upgraded to 1.9.1.

**Comment by bjaglin** [comment]
Until this is fixed (do we have to wait for a Docker release for boot2docker to be updated?), this one-liner should do the trick without having to ask users to mess with the local `boot2docker.iso`.
```
VIRTUALBOX_BOOT2DOCKER_URL="https://github.com/boot2docker/boot2docker/releases/download/v1.9.0/boot2docker.iso" docker-machine upgrade boot2docker-vm
```

**Comment by krishna81m** [comment]
@bjaglin , what is the equivalent for windows docker-machine upgrade?

```
$ VIRTUALBOX_BOOT2DOCKER_URL=https://github.com/boot2docker/boot2docker/releases/download/v1.9.0/boot2docker.iso

$ docker-machine upgrade boot2docker-vm
Could not load host "boot2docker-vm": Loading host from store failed: Host does not exist: "boot2docker-vm"

$ docker-machine upgrade default
Stopping machine to do the upgrade...
Upgrading machine default...
Latest release for github.com/boot2docker/boot2docker is v1.9.1

Downloading https://github.com/boot2docker/boot2docker/releases/download/v1.9.1/boot2docker.iso to C:\Users\.docker\machine\cache\boot2docker.iso...
Starting machine back up...
```

**Comment by AkihiroSuda** [comment]
v1.10.0 should have fixed this. I suggest closing this issue.

**Comment by tianon** [comment]
Indeed, thanks @AkihiroSuda. :+1:

**Comment by Nickology** [comment]
Nope, sorry @tianon. Just ran into this with Docker 1.10.3 on Ubuntu 14.04.3.
