### ISSUE TITLE
udev for persistent storage not working

### ISSUE THREAD

**Issue by clintonskitson** [boot2docker/boot2docker#1111]
I am working towards trying to ensure that `docker-machine` and boot2docker with VirtualBox can leverage external volumes a VB volume plugin with the Virtual Media manager.  This works fine when using Ubuntu and other Linux distributions but I am running into a couple of challenges with the distribution present in the boot2docker.iso.

When mapping external drivers using VirtualBox, these devices typically would show up and udev would be responsible for mapping them appropriately in `/dev/disk`.  For most distributions, `/dev/disk/by-id` is populated.  

Re boot2docker, I am running into two distinct but somewhat related issues.

1) The link that gets populated by udev for new devices overwrites existing links instead of creating new ones.

```
root@default:/dev/disk# ls -l /dev/disk/by-path/
total 0
lrwxrwxrwx    1 root     root             9 Jan  7 21:14 pci-0000:00:0d.0-scsi-0:0:0:0 -> ../../sdb
lrwxrwxrwx    1 root     root            10 Jan  7 21:14 pci-0000:00:0d.0-scsi-0:0:0:0-part1 -> ../../sda1
lrwxrwxrwx    1 root     root            10 Jan  7 21:14 pci-0000:00:0d.0-scsi-0:0:0:0-part2 -> ../../sda2
```

Notice how the `../../sdb` is populated where the identifiers are for the device from `../../sda1`.  I believe I have narrowed this down to information no properly being returned when requested by udev.  Notice how the ID_PATH field (used in udev rules) is incorrect.

```
root@default:/dev/disk# udevadm info -q property --name=/dev/sdb
DEVLINKS=/dev/disk/by-path/pci-0000:00:0d.0-scsi-0:0:0:0
DEVNAME=/dev/sdb
DEVPATH=/devices/pci0000:00/0000:00:0d.0/ata3/host2/target2:0:0/2:0:0:0/block/sdb
DEVTYPE=disk
ID_PATH=pci-0000:00:0d.0-scsi-0:0:0:0
ID_PATH_TAG=pci-0000_00_0d_0-scsi-0_0_0_0
MAJOR=8
MINOR=16
SUBSYSTEM=block
USEC_INITIALIZED=15589878
```

2) The related problem is that the `/dev/disk/by-id` is not being populated at all.  In typical udev rule files for other distributions this is done via a rule and by using `ID_SERIAL` which isn't present.

**Comment by AkihiroSuda** [comment]
@clintonskitson Please try #1114?

**Comment by clintonskitson** [comment]
Tested, and merged by @tianon.  Thank you!
