### ISSUE TITLE
help me. if i need yum apt-get dnf make,What should I do

### ISSUE THREAD

**Issue by smalleyes** [boot2docker/boot2docker#1122]
help me. if i need yum apt-get dnf make,What should I do.thank you very much.

**Comment by AkihiroSuda** [comment]
Use tce-load: http://wiki.tinycorelinux.net/wiki:tce-load

**Comment by smalleyes** [comment]
thank you AkihiroSuda for help. i use tce command.
http://distro.ibiblio.org/tinycorelinux/download_howto.html
