### ISSUE TITLE
Guidance Requested: Custom Root CA Certificates

### ISSUE THREAD

**Issue by valentinbud** [boot2docker/boot2docker#1129]
I am trying to insert inside boot2docker.iso some custom Root CAs, [[Intermediate #2 (SHA-2)] Comodo RSA Domain Validation Secure Server CA](https://support.comodo.com/index.php?/Knowledgebase/Article/View/970/0/intermediate-2-sha-2-comodo-rsa-domain-validation-secure-server-ca) because it's missing from installed certs and docker can't pull from a custom registry which uses a TLS certificate issued by the above mentioned Root CA.

I have read the [BUILD](https://github.com/boot2docker/boot2docker/blob/master/doc/BUILD.md) document and inspected files in [rootfs/etc/rc.d](https://github.com/boot2docker/boot2docker/blob/master/rootfs/rootfs/etc/rc.d). 

I couldn't figure it out where should I place certificates so they end up in `/var/lib/boot2docker/certs` and configured by `install-ca-certs` rc.d script at machine first boot. All of this via the awesome BUILD mechanism that boot2docker has.

Can someone please shed some light. Thanks :).

**Comment by valentinbud** [comment]
#347 is related but it doesn't clarify the above. I would like the Root CA to be inserted at build inside the boot2docker.iso and at startup to be automatically inserted by `install-ca-certs`.

**Comment by valentinbud** [comment]
For other boot2docker-ers out there I will post here a hack to achieve the above. In fact I will post my custom Dockerfile.

```
FROM boot2docker/boot2docker

# COPY docker/ $ROOTFS/etc/docker/
COPY ca-certificates $ROOTFS/opt/ca-certificates
COPY custom-ca-certificates $ROOTFS/opt/
RUN chmod +x $ROOTFS/opt/custom-ca-certificates \
    && echo "/opt/custom-ca-certificates" >> $ROOTFS/opt/bootlocal.sh \
    && echo "# Custom Root CA Certificates" >> $ROOTFS/opt/bootscript.sh \
    && echo "if [ -e /opt/bootlocal.sh ]; then" >> $ROOTFS/opt/bootscript.sh \
    && echo "    /bin/sh /opt/bootlocal.sh > /var/log/bootlocal.log 2>&1 &" >> $ROOTFS/opt/bootscript.sh \
    && echo '    echo "------------------- ran /var/lib/boot2docker/bootlocal.sh"' >> $ROOTFS/opt/bootscript.sh \
    && echo "fi" >> $ROOTFS/opt/bootscript.sh

RUN /make_iso.sh

CMD ["cat", "boot2docker.iso"]

```

`custom-ca-certificates` is a shell script which content can be found at the following gist:  https://gist.github.com/irgeek/afb2e05775fff532f960. I have changed `BOOT2DOCKER_CERTS_DIR=/var/lib/boot2docker/certs` to `BOOT2DOCKER_CERTS_DIR=/opt/ca-certificates`.

Happy hacking :).

**Comment by jenxie** [comment]
Small question, what is the content of ca-certificates file?
