### ISSUE TITLE
installing kvm on ubuntu docker machine

### ISSUE THREAD

**Issue by iam-peekay** [boot2docker/boot2docker#1138]
I need to install kvm on my ubuntu docker machine, which requirea that I install kvm_intel as noted here: https://wiki.ubuntu.com/kvm

I tried to install the linux-headers as noted in
http://askubuntu.com/questions/564910/kvm-is-not-installed-on-this-machine-dev-kvm-is-missing and https://wiki.ubuntu.com/kvm

I am running 
```
RUN apt-get install kvm qemu
RUN depmod
RUN modprobe kvm_intel
```

However, i get the error: 
**depmod: ERROR: could not open directory /lib/modules/4.1.13-boot2docker: No such file or directory
depmod: FATAL: could not search modules: No such file or directory**

So I installed the linux headers 

```
RUN apt-get install -y linux-headers-$(uname -r)
RUN ln -s /usr/src/linux-headers-$(uname -r)/ /lib/modules/$(uname -r)/build
RUN ln -s /usr/src/linux-headers-$(uname -r)/ /lib/modules/$(uname -r)/build
RUN depmod
RUN modprobe kvm_intel
```
but then I keep getting an error saying
**E: Unable to locate package linux-headers-4.1.13-boot2docker
E: Couldn't find any package by regex 'linux-headers-4.1.13-boot2docker**

which makes sense. So I tried the "linux-headers-generic" build, which installs with no issues, but I get the same error
**depmod: ERROR: could not open directory /lib/modules/4.1.13-boot2docker: No such file or directory
depmod: FATAL: could not search modules: No such file or directory**

What do I need to install to be able to run: 
```
RUN depmod
RUN modprobe kvm_intel
```

Thank you!

**Comment by AkihiroSuda** [comment]
Please try `modprobe kvm_intel` _outside_ the container.

**Comment by iam-peekay** [comment]
@AkihiroSuda what did you mean by outside the container? The commands I wrote above are executed in my Dockerfile. 

Sorry if I misunderstood you.

**Comment by AkihiroSuda** [comment]
I meant like this:
```
host$ docker-machine ssh your-docker-machine
your-docker-machine$ sudo modprobe kvm_intel
your-docker-machine$ exit
```

Then, you can use Dockerfile which only contains `RUN apt-get install -y kvm qemu`.

Note that `kvm_intel.ko` module is tied with Boot2Docker kernel rather than Ubuntu container.
So you can't load `kvm_intel.ko` inside the Ubuntu container.

**Comment by iam-peekay** [comment]
@AkihiroSuda thank you. I got the error 
**modprobe: can't load module kvm_intel (kernel/arch/x86/kvm/kvm-intel.ko): Operation not supported**

**Comment by AkihiroSuda** [comment]
Perhaps are you trying to running KVM on VirtualBox?
It doesn't work because VirtualBox does not support nested virtualization.
Please consider using VMware instead of VirtualBox.

(Sorry if you are not using VirtualBox)

**Comment by iam-peekay** [comment]
@AkihiroSuda  I ran the command on Vmware Fusion docker machine as well, and I get the same error.

**Comment by AkihiroSuda** [comment]
@iam-peekay https://communities.vmware.com/docs/DOC-8970

**Comment by iam-peekay** [comment]
Yup. Even though I've configured the options:
vhv.enable = TRUE
vcpu.hotadd = FALSE

I still get the error.
![image](https://cloud.githubusercontent.com/assets/5421194/13018704/07d8b7a2-d180-11e5-85ba-c10e4e7df96c.png)

**Comment by AkihiroSuda** [comment]
Is there vmx flag in /proc/cpuinfo?
If exists, it's a B2D misconfiguration, if not, it's a VMware misconfiguration.

**Comment by iam-peekay** [comment]
@AkihiroSuda  I was able to run ```sudo madprobe kvm_intel``` after checking the box next to  "Virtualize Intel VT-x/EPT" in vm settings

However, when I run my container with the emulator, I still get the error that KVM is not installed and the docker container exits/stops:
![image](https://cloud.githubusercontent.com/assets/5421194/13021452/19e99924-d190-11e5-93a4-6e78f78aa4ee.png)

**Comment by AkihiroSuda** [comment]
You need to run `mknod /dev/kvm c 10 232` _inside_ the container.
You also need to add`--privileged` flag when you execute `docker run`.

**Comment by iam-peekay** [comment]
thank you so much! that helped solve the issue with it saying that the KVM is not installed. Now I get error saying that the /dev/kvm is missing 

![image](https://cloud.githubusercontent.com/assets/5421194/13021900/928b34b2-d192-11e5-8c80-c44019d3a79f.png)

**Comment by iam-peekay** [comment]
@AkihiroSuda it might have to do with KVM (vmx) being disabled by the BIOS. Haven't yet figured out how to enter the BIOS setup and enable Virtualization Technology (VT)

**Comment by AkihiroSuda** [comment]
If you ran `modprobe kvm_intel` successfully, it means VT is enabled.
(All the recent Macintoshes support VT by default: https://support.apple.com/en-gb/HT203296)

* Make sure you check "Virtualize Intel VT-x/EPT" in the configuration dialog of VMware Fusion.
* Make sure you run `modprobe kvm_intel` (_outside_ the container).
* Make sure you run `docker run` with `--privileged`.
* Make sure `vmx` is shown when you run `cat /proc/cpuinfo` _inside_ the container
* Make sure `kvm_intel` is shown when you run `lsmod` _inside_ the container
* Make sure you run `mknod /dev/kvm c 10 232` _inside_ the container

Sorry actually I don't have VMware Fusion and I can't try your workload locally.

**Comment by iam-peekay** [comment]
thank you! I've done #1, #2, # 3 outside the container.
For #4, #5, #6, I am not able to get inside the container because it exits immediately after I run the container due to the KVM error message from above.

**Comment by AkihiroSuda** [comment]
```
$ docker run -it --privileged YOUR_CONTAINER
container# cat /proc/cpuinfo
container# lsmod
container# mknod /dev/kvm c 10 232
container# /YOUR-INIT
```

**Comment by iam-peekay** [comment]
Thank you! After shutting off and restarting the vm, and then running ```docker run -it --privileged IMAGE_NAME``` I no longer have that error about the kvm. 

my only issue now is that I'm not able to connect to the emulator running inside the container at IP address 172.17.0.2 on port 5902 (which is what I set the VNC display port to).. I'll figure out what's happening.

Thank you so much for all the help! Really appreciated. 

![image](https://cloud.githubusercontent.com/assets/5421194/13023304/89c46fe2-d19c-11e5-924e-acebde8b6eea.png)
