### ISSUE TITLE
slow developing packet loss when access the docker host as part of Docker ToolBox on Windows

### ISSUE THREAD

**Issue by wu105** [boot2docker/boot2docker#1154]
I installed Docker ToolBox on a Windows 7 Professional.
For access a docker machine, I added a 3rd network adaptor in VirtualBox, bridged.
The adaptor type is "PCnet-FAST III (Bridged Adapter, Intel(R) Ethernet Connection 1217-LM)", the VirtualBox default.
This docker machine can be accessed from the same subnet ok, 
but would slowly develop an access problem from other subnets.
The telltale is pinging the docker machine from different subnets would show increasingly more packet loss, util 100% loss.
Restarting the docker machine would not impact the packet loss.
The docker machine created by the Docker ToolBox uses dhcp on the new network adaptor, and changing to static ip had no obvious impact on the packet loss situation.
Removing or re-adding a default gateway on the docker machine would instantly fix the packet loss for a few hours, and the gateway being tweaked does not have to be the one associated with the new adaptor, e.g., removing the gateway 10.0.2.2 (via command route del default) alone would fix the packet loss.

Our network support says this is a problem with the docker machine and provided the "workaround" of removing/re-adding default gateways.

Any help?

Here is some information about the docker machine:
docker@xyz:~$ cat /etc/*-release
NAME=Boot2Docker
VERSION=1.10.3
ID=boot2docker
ID_LIKE=tcl
VERSION_ID=1.10.3
PRETTY_NAME="Boot2Docker 1.10.3 (TCL 6.4.1); master : 625117e - Thu Mar 10 22:09:02 UTC 2016"
ANSI_COLOR="1;34"
HOME_URL="http://boot2docker.io"
SUPPORT_URL="https://github.com/boot2docker/boot2docker"
BUG_REPORT_URL="https://github.com/boot2docker/boot2docker/issues"

The VirtualBox is Version 5.0.16 r105871.
The windows os is Windows 7 Professional with Service Pack 1.

**Comment by heuvel** [comment]
I have the same problem with boot2docker on a Mac with the following versions:
* OS X El Capitan 10.11.5
* VirtualBox 5.1.0 r108711
* docker-machine version 0.8.0-rc2, build 4ca1b85
* Boot2Docker 1.12.0.rc5
* 3rd network adapter: bridged, PC-Net Fast III

Removing and re-adding the gateway fixes the problem.

**Comment by tianon** [comment]
Sorry for the long delay -- this is definitely something to do with VirtualBox (not the boot2docker ISO).  I'd recommend trying a VirtualBox-specific support forum/community for help determining the root cause.
