### ISSUE TITLE
usr/local/bin/vmhgfs-fuse: error while loading shared libraries: libtirpc.so.1

### ISSUE THREAD

**Issue by kaosagnt** [boot2docker/boot2docker#1157]
```
# Install build dependencies for VMware Tools

        libtirpc1 \

/usr/local/bin/vmhgfs-fuse: error while loading shared libraries: libtirpc.so.1: cannot open shared object file: No such file or directory
/usr/local/bin/vmtoolsd: error while loading shared libraries: libtirpc.so.1: cannot open shared object file: No such file or directory
/usr/local/bin/vmhgfs-fuse: error while loading shared libraries: libtirpc.so.1: cannot open shared object file: No such file or directory
```

TCL 7 supplies

```
/usr/local/lib/

libtirpc.so -> libtirpc.so.3.0.0
lrwxrwxrwx    1 root     root            17 Apr 15 00:37 libtirpc.so.3 -> libtirpc.so.3.0.0
-rwxr-xr-x    1 root     root        137064 Apr 10 14:38 libtirpc.so.3.0.0
```

Therefore I am unable to mount volumes via vmware fusion like I once did. This seems to have happen ed after the docker 1.11.0 update. Previously this was working fine.

**Comment by SchwarzM** [comment]
Linking libtirpc.so.1 to libtirpc.so.3.0.0 works for me.

**Comment by tianon** [comment]
:scream: cc @frapposelli

**Comment by kaosagnt** [comment]
Yup your correct. If I build an iso with the following

# TCL 7 doesn't ship with libtirpc.so.1 Dummy it up so the
# VMWare tools work again.
RUN cd $ROOTFS/usr/local/lib; \
    ln -s libtirpc.so.3.0.0 libtirpc.so.1; \
    ldconfig

then things work correctly again. Previously the ISO would take ages to boot and not shutdown correctly as well as not mount volumes via the vmware tools. No all the tools are running it boots in normal time and shutdown down correctly as well.

**Comment by frapposelli** [comment]
Fix https://github.com/boot2docker/boot2docker/pull/1161 waiting to be merged, thanks @kaosagnt for reporting and testing this out.
