### ISSUE TITLE
Memory leak when using Parallels + volumes

### ISSUE THREAD

**Issue by kane-c** [boot2docker/boot2docker#1164]
I've been using latest [the Parallels driver](https://github.com/Parallels/docker-machine-parallels) with the latest Parallels on OS X 10.10.4 with boot2docker from v1.10.0 up to the latest version, and it's been working well except for a frustrating memory leak problem.

After some trial and error, the problem seems to be caused by volumes.

After running a container with a mounted volume from the host (i.e. directory within `/Users`), memory is allocated by the kernel and it is never freed. Starting and stopping a container a few more times causes the memory to continue increasing, until eventually there is no memory left and the VM grinds to a halt.

Running `free` shows an ever-growing buffers/cache use.
Running `top` does not show any processes using much memory. I can stop all services such as Docker and the memory does not free.
Running `echo 1 (or 2-4) > /proc/sys/vm/drop_caches` does not help
Running `slabtop` shows all the memory is going to `kmalloc-4096`.
Building a totally new Docker Machine does not help.

I have tried running the same setup with VMWare and the memory issue is not present there (however I have a file permission problem with volumes so I would prefer to continue using Parallels).

My workaround at the moment is to allocate more memory to the VM (4GB instead of the default 1GB) to buy some more time between restarts. If I'm lucky, I only need to restart the VM once or twice a day this way, but I would love to never have to restart it.

Any ideas?

**Comment by thaJeztah** [comment]
ping @legal90 perhaps you have an idea?

**Comment by legal90** [comment]
Ping @romankulikov. Do we need a problem report being sent to Parallels? I've reproduced the similar issue just by listing files in shared folders:

```bash
[osx] $ docker-machine create -d parallels prl-test
#...
[osx] $ docker-machine ssh prl-test
[b2d] $ find /Users
#...
```
The allocated memory is never freed.

**Comment by kane-c** [comment]
I have switched to [Dinghy](https://github.com/codekitchen/dinghy) for now - it uses boot2docker but NFS rather than Parallels shared folders. It's been running perfectly.

**Comment by thaJeztah** [comment]
@kane-c you may also be interested in https://blog.docker.com/2016/03/docker-for-mac-windows-beta/ if you didn't register yet (beta.docker.com)

**Comment by kane-c** [comment]
@thaJeztah yep, I've got the beta but haven't tried it yet :) I'll give it a go, thanks!

**Comment by legal90** [comment]
@kane-c Could you please provide some scenario (for example, Dockerfile) how to reproduce this issue in Docker use case? It would really help us to fix it.
My case with `find` mentioned above seems to be not relevant.

**Comment by kane-c** [comment]
I haven't tested this following #1217 but I am now using [dinghy](https://github.com/codekitchen/dinghy) which works perfectly.
