### ISSUE TITLE
Removing /bin/tar prevents Docker from running containers

### ISSUE THREAD

**Issue by boucher** [boot2docker/boot2docker#1175]
Upfront, I admit this is a bit of a strange issue and may be slightly out of scope. That being said, I'm trying to create a custom boot2docker image for use with testing my Checkpoint/Restore support in Docker. For some reason, the process involve is picking up busybox at `/bin/tar` instead of gnutar at `/usr/local/bin/tar`, and busybox tar is not supported. I thought I could just swap out the file at `/bin/tar` in the image, but unfortunately that results in Docker being unable to start containers at all, with this failure:

```
docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: pivot_root invalid argument".
exit status 125
```

Here's a minimal Dockerfile you can use to build a broken image (based on the README):

```
FROM boot2docker/boot2docker

RUN rm $ROOTFS/bin/tar && cp -a $ROOTFS/usr/local/bin/tar $ROOTFS/bin/tar

RUN /make_iso.sh
CMD ["cat", "boot2docker.iso"]
```

I've already built such an image and put it on dropbox for ease of testing:

```
docker-machine create --driver=virtualbox --virtualbox-boot2docker-url="https://dl.dropboxusercontent.com/u/927666/boot2docker-test.iso" t1

docker-machine ssh t1 docker run -d busybox top
```

Running that should produce the error in question. Notably, removing `/bin/tar` after the machine boots works absolutely fine. The results don't matter if you remove or replace `/bin/tar` during creation as far as I can tell.

**Comment by tianon** [comment]
Sorry for the long delay -- I think newer versions of Docker have stopped shelling out to `tar` on the host and use `archive/tar` from Go's stdlib directly. :+1:

**Comment by tianon** [comment]
(It could also be the usage of `tar` during boot2docker's boot process which is causing this failure -- I assume you managed to find a workaround by now though. :man_facepalming:)
