### ISSUE TITLE
Boot2Docker recognizing only 8 cpu's from Windows 8 host workstation, with virtualbox drivers

### ISSUE THREAD

**Issue by kjkunte** [boot2docker/boot2docker#1178]
Output of docker version:
Docker version
Client:
Version: 1.11.2
API version: 1.23
Go version: go1.5.4
Git commit: b9f10c9
Built: Wed Jun 1 21:20:08 2016
OS/Arch: windows/amd64

Output of docker info:
Server:
Version: 1.11.2
API version: 1.23
Go version: go1.5.4
Git commit: b9f10c9
Built: Wed Jun 1 21:20:08 2016
OS/Arch: linux/amd64

Additional environment details (AWS, VirtualBox, physical, etc.):
Windows 8.1 pro workstation, with 24 virtual processors and 12 actual cores
![taskmanager](https://cloud.githubusercontent.com/assets/4727323/16841358/6ebade66-49f6-11e6-85cb-6bc3499b27bf.png)

Steps to reproduce the issue:
1. docker-machine create --virtualbox-cpu-count -1 -d virtualbox dev1
2. docker-machine ssh dev cat /proc/cpuinfo>log

Describe the results you received:
1. Step 1 descibed above should create a docker-machine called dev1 with 24 virtual processors, which shown in the image below
![dev1](https://cloud.githubusercontent.com/assets/4727323/16841375/7c501e92-49f6-11e6-8d08-b0d101b29c80.png)

2. The result of the step 2 is attached in the log file here : 
[log1.txt](https://github.com/boot2docker/boot2docker/files/363835/log1.txt)

Please let me know, how I can solve this ?
Thanks,
Kshitij

**Comment by yosifkit** [comment]
It looks like `CONFIG_NR_CPUS` is only [set to 8](https://github.com/boot2docker/boot2docker/blob/master/kernel_config#L420) and has been since the beginning.  I think it would be a fine change, especially given that Debian sets it to [512 for amd64](https://sources.debian.net/src/linux/4.6.3-1/debian/config/amd64/config/#L10).  There is a small penalty for setting it higher, so we should probably only set it up to 64.

> This allows you to specify the maximum number of CPUs which this
> kernel will support.  If CPUMASK_OFFSTACK is enabled, the maximum
> supported value is 8192, otherwise the maximum value is 512.  The
> minimum value which makes sense is 2.
>
> This is purely to save memory - each supported CPU adds
> approximately eight kilobytes to the kernel image.

**Comment by kjkunte** [comment]
Hi, 
Thanks for the update I have put a pull request for the same after the commit.
