### ISSUE TITLE
How to set root/docker user password while creating own boot2docker ISO

### ISSUE THREAD

**Issue by anandnevase** [boot2docker/boot2docker#1182]
I am trying to create customised Boot2docker ISO using [How to build](https://github.com/boot2docker/boot2docker/blob/master/doc/BUILD.md) documentation.

Can any one help me how can set root/docker user password while building ISO image??

**Comment by tianon** [comment]
Sorry for the long delay.  As I've noted elsewhere, I'd honestly recommend choosing a different distribution as your base (something designed to be more flexible) if you need something more advanced than what's provided here out-of-the-box.
