### ISSUE TITLE
modprobe autofs4

### ISSUE THREAD

**Issue by cyberjoac** [boot2docker/boot2docker#1189]
Hi,
I'm trying to run autofs module inside a boot2docker VM container.
It doesn't work because it cannot find the kernel module autofs4.
I tried loading it inside the boot2docker VM by doing sudo modprobe autofs4 but I got the error: 
modprobe: module autofs4 not found in modules.dep 
Any hint how to solve that ? Thanks

**Comment by yosifkit** [comment]
It is not a module or compiled in to the kernel in boot2docker: https://github.com/boot2docker/boot2docker/blob/e030bab8fc7e20ea3b50760e4a3e8808f4335ba0/kernel_config#L4034.  So it would require an accepted PR and a new release (or a fork and build for yourself).

**Comment by cyberjoac** [comment]
I think it would make sense for other users as well since it is a feature supported out of the box when Docker host is running in a Unix VM.
What should be in the PR then ? Just changing the line 
`# CONFIG_AUTOFS4_FS is not set` to
`# CONFIG_AUTOFS4_FS=y`

Then regarding the new release, should it be part of the pull request? 

Thanks for your fast answer.
