### ISSUE TITLE
Update curl to 7.40 or later so you can curl the docker unix socket

### ISSUE THREAD

**Issue by veqryn** [boot2docker/boot2docker#1196]
Curl version installed is 7.33.0 (Using Boot2Docker 1.11.1), which does not have the --unix-socket option.
It would be nice if you could curl the /var/run/docker.sock unix socket and use the docker api from inside the boot2docker vm.
This would require a newer version of curl, at least 7.40.0

**Comment by yosifkit** [comment]
The newest release for docker `1.12.1` has curl `7.49.1`. :tada:
