### ISSUE TITLE
unknown symbol in module when loading kernel *.ko modules

### ISSUE THREAD

**Issue by galeksandrp** [boot2docker/boot2docker#1200]
When i tried to load `ip6table_filter.ko` for ip6tables, i saw 

``` sh
docker@default:~$ sudo insmod /lib/modules/4.4.12-boot2docker/kernel/net/ipv6/netfilter/ip6table_filter.ko
insmod: can't insert '/lib/modules/4.4.12-boot2docker/kernel/net/ipv6/netfilter/ip6table_filter.ko': unknown symbol in module, or unknown parameter
```

Is this because kernel modules built for different kernel version? (I'm using boot2docker v1.12.1)

**Comment by simonvanderveldt** [comment]
@galeksandrp you should use `modprobe` to load modules, not `insmod`. `modprobe` will load dependencies whereas `insmod` doesn't, which is the issues you're seeing here.
`modprobe ip6table_filter` works fine (using 1.12.5, but won't be any different on your version).
