### ISSUE TITLE
Permission denied although correctly set

### ISSUE THREAD

**Issue by nsams** [boot2docker/boot2docker#1202]
When I do the following inside a boot2docker VM (Running with virtualbox)

    $ docker --version
    Docker version 1.11.2, build b9f10c9
    $ docker pull centos/php-56-centos7
    ....
    $ docker run -ti --rm centos/php-56-centos7 bash
    $ ls -l /opt/rh/httpd24/root/var/run
    drwxrwxrwx 4 root apache 4096 Aug 24 09:23 httpd
    $ touch /opt/rh/httpd24/root/var/run/httpd/foo
    touch: cannot touch 'foo': Permission denied

I get a Permission denied :(

Works fine on my archlinux with same docker version.

**Comment by yosifkit** [comment]
I am not sure why that would work on one system and not the other, but that is the permissions of the image and not a problem with boot2docker.

```console
$ docker run -it --rm centos/php-56-centos7 bash
bash-4.2$ id -u
1001
bash-4.2$ ls -lan /opt/rh/httpd24/root/var/run/
total 12
drwxr-xr-x  3 0  0 4096 Aug 31 23:02 .
drwxr-xr-x 19 0  0 4096 Aug 31 23:02 ..
drwxrwxrwx  3 0 48 4096 Aug 31 23:02 httpd
```
User `1001` does not have permission to write to `/opt/rh/httpd24/root/var/run/`; perhaps you meant `/opt/rh/httpd24/root/var/run/httpd/`?

**Comment by nsams** [comment]
Yes, you are right - sorry for the confusion. I updated the path in the first message.

**Comment by yosifkit** [comment]
Closing as this seems to be resolved.  If you feel this issue was closed prematurely, please comment and let us know.
