### ISSUE TITLE
Unable to see non-Latin filename in manually created host volume

### ISSUE THREAD

**Issue by chen-xin** [boot2docker/boot2docker#1205]
Host: Windows 10 
Docker: 1.12.0
VirtureBox: 5.1.4
I did the following to share my host folder for docker:

1. add vbox sharefolder with:
> C:/Program Files/Oracle/VirtualBox/VBoxManage sharedfolder add default -name projects -hostpath d:/Documents/Projects -automount

2. ssh to docker-machine and add file /mnt/sda1/var/lib/boot2docker/bootlocal.sh as:

> mkdir -p /d/Documents/projects
> mount -t vboxsf -o defaults,uid=`id -u docker`,gid=`id -g docker` projects /d/Documents/projects

3. restart docker-machine.
4. ssh to docker-machine to see my file:

> ls /d/Documents/projects
>    .. only filename with full latin characters showed
> ls /c/Users/myname/Desktop
>     .. all files showd, although non-latin characters display as ?, this is no problem

How can I make my new created host volume work with non-latin filenames as the default one?

**Comment by ailispaw** [comment]
I guess you need `iocharset=utf8` as an additional mount option for non-latin filenames.
https://github.com/boot2docker/boot2docker/blob/master/rootfs/rootfs/etc/rc.d/vbox#L11
https://github.com/boot2docker/boot2docker/pull/1044

**Comment by chen-xin** [comment]
Thank you @ailispaw , it worked!
