### ISSUE TITLE
kernel: enable eBPF options

### ISSUE THREAD

**Issue by iaguis** [boot2docker/boot2docker#1206]
We'd need eBPF support to use some [Weave Scope](https://github.com/weaveworks/scope) plugins like the [http-requests](https://github.com/weaveworks/scope/tree/master/examples/plugins/http-requests) one and for an upcoming new implementation of the probe component.

As documented in https://github.com/iovisor/bcc/blob/master/INSTALL.md#kernel-configuration, the options needed are:

```
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
# [optional, for tc filters]
CONFIG_NET_CLS_BPF=m
# [optional, for tc actions]
CONFIG_NET_ACT_BPF=m
CONFIG_BPF_JIT=y
CONFIG_HAVE_BPF_JIT=y
# [optional, for kprobes]
CONFIG_BPF_EVENTS=y
```

Would it be possible to enable them in the default configuration?

cc @alban @asymmetric

**Comment by iaguis** [comment]
I can prepare a PR if there's interest.

**Comment by yosifkit** [comment]
Those are the same values as a Debian kernel (http://sources.debian.net/src/linux/4.7.5-1/debian/config/config/?hl=5553#L5553).  So, it seems fine to me.  cc @tianon

We could also add `CONFIG_NETFILTER_XT_MATCH_BPF=m` if that is in Debian and might be helpful too.
