### ISSUE TITLE
Can't Unzip Files in Docker VM (Boot2Docker) / Windows 7 / CRC Error

### ISSUE THREAD

**Issue by JoThomsen** [boot2docker/boot2docker#1213]
Moin moin,

I'm unable to unzip files like eclipse.tar.gz with e.g gunzip. Neither in DockerFiles with ADD url nore when I use wget on the File.

```
$ wget http://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/neon/1a/eclipse-jee-neon-1a-linux-gtk.tar.gz&mirror_id=96 
$ gunzip eclipse-jee-neon-1a-linux-gtk.tar.gz
```

I always get a CRC error. When I unzip the File with Windows there is no CRC error. They have the same CRC and the same MD5sum. I already changed the baseimage (debian/ubuntu), I used tar/gunzip and it happens when I build the images and when I unzip it in the bash from the Image.

This is my current system

```
 Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:00:50 2016
 OS/Arch:      linux/amd64
Kernel Version: 4.4.24-boot2docker
Operating System: Boot2Docker 1.12.2 (TCL 7.2); HEAD : 9d8e41b - 
```

**Comment by AkihiroSuda** [comment]
What's your storage driver?
Eg AUFS Overlay..

What happens if you change the driver?

**Comment by JoThomsen** [comment]
Thanks for the quick reply,
i use AUFS, trying to switch to overlay

**Comment by yosifkit** [comment]
The url you provided only gets me the web page that says "thanks for downloading", but on that page is a direct link for the tar.gz file. It gave me a ~300MB download at [this url](http://www.mirrorservice.org/sites/download.eclipse.org/eclipseMirror/technology/epp/downloads/release/neon/1a/eclipse-jee-neon-1a-linux-gtk.tar.gz).  Downloading that file, I can then `tar -xf eclipse-jee-neon-1a-linux-gtk.tar.gz` and end up with a directory for `eclipse`.

I tested this in a `buildpack-deps:curl` container.

**Comment by cbergau** [comment]
I am not 100% sure if it is the same issue or related to boot2docker at all. If it is not related, then ignore my comment. I just updated my boot2docker vm and i get similiar issues:

My Dockerfile:

    FROM php:7-apache

    #XDebug
    RUN yes | pecl install xdebug \
        && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini \
        && echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/xdebug.ini \
        && echo "xdebug.profiler_enable=0" >> /usr/local/etc/php/conf.d/xdebug.ini \
        && echo "xdebug.profiler_enable_trigger=1" >> /usr/local/etc/php/conf.d/xdebug.ini \
        && echo "xdebug.profiler_output_dir=/var/www/html" >> /usr/local/etc/php/conf.d/xdebug.ini \
        && echo "xdebug.remote_autostart=off" >> /usr/local/etc/php/conf.d/xdebug.ini

The error i am getting:

    ERROR: unable to unpack /tmp/pear/download/xdebug-2.4.1.tgz

Last week, before i did the update, it worked perfectly fine.

**Comment by JoThomsen** [comment]
I changed the storage-driver in my boot2docker machine, 
now I'm able to unzip Files which I get with the ADD command in the DockerFile or via wget in the container. 
Great Thanks to the Team!
