### ISSUE TITLE
Persisitent /etc/hosts file

### ISSUE THREAD

**Issue by umairaslamm** [boot2docker/boot2docker#1224]
Is it possible for us to have a persistent /etc/hosts file, as every time the vm is restarted, the entries in /etc/hosts file are gone.

**Comment by sergeyglazyrindev** [comment]
I think it's possible if you symlink /etc/hosts to one of directories you mounted to your docker containers

**Comment by tianon** [comment]
Sorry for the long delay -- yes, using `/var/lib/boot2docker/bootsync.sh`, you can replace `/etc/hosts` with your own content or a symlink to the persistent `/var/lib/boot2docker` directory on every VM boot.
