### ISSUE TITLE
proposal about provisioning docker containers with ansible and handling docker configuration with docker-compose

### ISSUE THREAD

**Issue by sergeyglazyrindev** [boot2docker/boot2docker#1228]
Hey guys!
I spent today whole day to understand how to persist my changes to tinycorelinux installed in boot2docker system.
I am using boot2docker as base vagrant box for all my projects
And I prefer to simplify the things, at least for my local development
So, to make a provision of my docker containers I use ansible and to simplify docker things, I use docker-compose
I made a changes to boot2docker rootfs/rootfs folder, actually, I copied there all necessary packages for ansible and docker-compose
I tried to do all changes inside docker containers in the filesystem (folder rootfs/rootfs) but couldn't because to get all necessary things I need to do a real chroot to the system with mounted /usr/ /var/ folders, etc. Unfortunately docker doesn't let us to do it, it may be possible with --privileged but we can use this flag only for docker run, not for docker build, so it's also one more problem
Then I used my .iso in boot2docker-vagrant project and made fully working system with ansible and docker-compose. Would be that interesting for you ? What could you suggest me ? I believe it should be separated repository.

**Comment by tianon** [comment]
Sorry for the long delay -- honestly, your use case is advanced beyond what boot2docker intends to support, and I'd recommend you base your development environment on a more full-featured distribution where this sort of customization is better-supported.
