### ISSUE TITLE
Move host customizations to privileged containers

### ISSUE THREAD

**Issue by shykes** [boot2docker/boot2docker#123]
I would like to remove pipework and other host customizations from the core boot2docker before it's too late, and move to containers as a standard means of expressing and loading customizations into boot2docker.

Once people start relying on various out-of-band tools being present on the host, you just lost the real potential of boot2docker which is to expose 100% of a machine's functionality via a standard docker endpoint. Once you start walking down that slippery slope, suddenly you have 100 new pull requests like https://github.com/steeve/boot2docker/issues/91 and all of sudden you're just another bloated distro.

**Comment by yosifkit** [comment]
Closing as this seems to be resolved.  If you feel this issue was closed prematurely, please comment and let us know.
