### ISSUE TITLE
Performance with Docker ToolBox and Xming as X-Client

### ISSUE THREAD

**Issue by JoThomsen** [boot2docker/boot2docker#1231]
Hello there,

I have a little Problem with my applikation performance. I use the latest Docker ToolBox installation. VirtualBox with the boot2docker Image on Windows 7. I have Xming a an X-Client where I want to use my App from the Docker Container. I works fine, but there is a Lag when I e.g press a button. Maybe there is an option to improve the performance. 
Thanks for help

Virtualbox-> Boot2docker->Docker Container -> GUI App -> Xming 

My Configuration
`Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 139
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.24-boot2docker
Operating System: Boot2Docker 1.12.2 (TCL 7.2); HEAD : 9d8e41b - Tue Oct 11 23:40:08 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.858 GiB`

**Comment by tianon** [comment]
Sorry for the long delay!  I'd recommend trying a VirtualBox specific support forum -- I don't think there's anything we can do in the boot2docker distribution itself to reduce the lag you're seeing.
