### ISSUE TITLE
I start docker and the explorer freezes

### ISSUE THREAD

**Issue by Bandito11** [boot2docker/boot2docker#1238]
Ver: Windows 10

Steps:

> I start "Docker for Windows.exe "

Issue:
 the explorer (as in windows explorer or explorer.exe) just stops working

I still can use applications though. I am not using VirtualBox btw, alas I am using Hyper-V. 

My computer has 8GB and an intel i5 if that helps.

**Comment by yosifkit** [comment]
"Docker for Windows" is a separate project and does not use the iso produced here.  This project is for the "Docker Toolbox" with `docker-machine`.  You'll probably want to file an issue over in their repo: https://github.com/docker/for-win/.
