### ISSUE TITLE
Docker machine stuck in starting vm - start with boot2docker v1.13.0

### ISSUE THREAD

**Issue by omerlh** [boot2docker/boot2docker#1240]
Today I started experiencing errors with `docker-machine create` - each time I run the command failed with the following error:
````
(default) Creating VirtualBox VM...
(default) Creating SSH key...
(default) Starting the VM...
(default) Check network to re-create if needed...
(default) Waiting for an IP...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.105:2376": tls: DialWithDialer timed out
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which might stop running containers.
````
I saw a similar issue in docker-machine repo (docker/machine#1684). I tried all the methods mention in the issue, but nothing helped. Then I noticed that when I create the machine, it also updated the boot2docker image. So I tried to downgrade the version of boot2docker, and it helped - version v1.12.6 worked, the problem started from v1.13.0.

My environment:
````
uname -a Darwin [pc name] 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
Docker version 1.13.1, build 092cba3
docker-machine version 0.9.0, build 15fd4c7
virutal box Version 5.1.14 r112924 (Qt5.6.2)
````

Thanks

**Comment by nathanleclaire** [comment]
Hm, we might need to update the Docker client libraries due to some recent changes in the way TLS stuff works, but the same versions of Machine and boot2docker work OK for me locally...

**Comment by omerlh** [comment]
I can try reproduce this with more logging, if you can instrument me what to check...

**Comment by tianon** [comment]
Sorry for the delay here, but this looks like it's probably resolved -- I've used the latest releases of `docker-machine` against the latest releases of boot2docker successfully recently. :+1:
