### ISSUE TITLE
OSX mounted Volume "/Users"

### ISSUE THREAD

**Issue by peterromfeldhk** [boot2docker/boot2docker#1242]
Hi,

I am using `DockerToolbox-1.13.1a.pkg` on OSX 10.12.3 (but had the same issue on el capitan)

When i change the content in a file on the host machine they are not correct reflected to the docker-machine vm.

1. start you docker-machine and ssh into it
2. on the hostmachine `echo initial > ~/test.txt` 
3. so far so good, on the docker-machine the file (`/Users/<host-username>/test.txt`) appears and has the correct content
4. on the hostmachine change the content `echo change > ~/test.txt` 
5. try to `cat` the file on docker-machine, there will be NO change
6. try to `less` or `tail` the file on the docker-machine and you will see the change

when using `docker` with a mounted volume the files inside the docker container wont update until i go to the docker-machine do `vi` on that file and immediate exit without changing anything with `:wq`. Even after i did the `vi` magic, doing `cat` will still return the old content!

I tested the same thing with a ubuntu VM without this issue, so i am sure it has to do with your custom linux build

Cheers,
Peter

**Comment by yosifkit** [comment]
It seems like this might be the same as https://github.com/boot2docker/boot2docker/issues/652 and related to https://www.virtualbox.org/ticket/9069, but the VirtualBox ticket has Ubuntu VM's having the issue as well.

**Comment by tianon** [comment]
Closing given that this is a VirtualBox issue and thus there's not really anything we can do to fix it.
