### ISSUE TITLE
Wrong version in iso

### ISSUE THREAD

**Issue by TomKeur** [boot2docker/boot2docker#1251]
In the iso from the latest version v17.04.0.ce the version is still: 17.03.1-ce

Docker is also not updated if I create a new machine.

https://github.com/boot2docker/boot2docker/releases/tag/v17.04.0-ce

@tianon Did something went wrong?

**Comment by tianon** [comment]
Doh, I uploaded the wrong ISO!  Good catch, @TomKeur. :heart: :disappointed:

I'll have that artifact updated in just a moment.

**Comment by tianon** [comment]
Ok, want to give it another download and verify that I got the right ISO up there this time? :innocent:

**Comment by TomKeur** [comment]
It's working!
I was building my own iso, but this is much faster! 

Thanks!

**Comment by tianon** [comment]
Sorry for the trouble -- I had the right ISO built, tested the right ISO, even included the right ISO's hashes in the release notes, but then uploaded the wrong one like a doof. :innocent:

**Comment by TomKeur** [comment]
Np! Glad you fixed it this quick 🥇
