### ISSUE TITLE
boot2docker.iso with wireless drivers

### ISSUE THREAD

**Issue by OscarAkaElvis** [boot2docker/boot2docker#1253]
Hi, I'm using docker-toolbox in a Windows environment and I'm trying to create a boot2docker iso with wireless drivers because I need to use it with containers which use usb wireless interfaces connected to them. I already know how to map wireless devices with virtualbox and extension pack using filters. Even inside the linux containers I can see the devices using `lsusb`. The problem is they are not appearing available using ifconfig or iwconfig and I guess is because boot2docker.iso have no drivers for that, so I decided to create a custom boot2docker iso with wireless drivers.

Ok, I saw in the [Dockerfile](https://github.com/boot2docker/boot2docker/blob/master/Dockerfile) is executing a RUN command to delete all wireless drivers for the standard iso:

```
# Remove useless kernel modules, based on unclejack/debian2docker
RUN cd $ROOTFS/lib/modules && \
    rm -rf ./*/kernel/sound/* && \
    rm -rf ./*/kernel/drivers/gpu/* && \
    rm -rf ./*/kernel/drivers/infiniband/* && \
    rm -rf ./*/kernel/drivers/isdn/* && \
    rm -rf ./*/kernel/drivers/media/* && \
    rm -rf ./*/kernel/drivers/staging/lustre/* && \
    rm -rf ./*/kernel/drivers/staging/comedi/* && \
    rm -rf ./*/kernel/fs/ocfs2/* && \
    rm -rf ./*/kernel/net/bluetooth/* && \
    rm -rf ./*/kernel/net/mac80211/* && \
    rm -rf ./*/kernel/net/wireless/*
```

I removed the 3 last lines to keep bluetooth, mac80211 and wireless drivers and I built the image generating a new iso file. After doing this, the first strange thing here is the generated iso have 1Mb less of size than the original....¿? it is suppossed that without removing that drivers the size could be larger... never shorter...

Anyway. I replaced the boot2docker.iso file from the `%userprofile%\.docker\machine\machines\default` folder and I recreated it (deleting the default vm and opening again the Docker Quickstart Terminal again and it recreates it automatically. But After mapping again the usb wifi device into containers, I can't see them as availables because I guess the drivers are not available at default vm. Opening a console into default vm I can see the `/lib/../blablabla/../kernel/net/wireless/` doesn't exist. Only exist `net` but not `wireless` dir.

I even tested to create the `wireless` dir on that location and copy driver files ther... but after a reboot of the vm, the dir and files disappeared. Why is this happening? What should be done to keep wireless drivers on boot2docker machine? thank you.

**Comment by rolandoislas** [comment]
The kernel wireless drivers are not installed by default in Tiny Core Linux. There is a package in the [TC repo](http://distro.ibiblio.org/tinycorelinux/7.x/x86_64/tcz/) for `wireless-4.2.9-tinycore64`, but boot2docker is currently at kernel version 4.4.66.

**Comment by OscarAkaElvis** [comment]
Hi, thanks for your response. I'm pretty close to achieve it. I forked boot2docker project and I modified a lot of times kernel_config in a try and error loop until get a kernel fully supporting wireless features (as much drivers as possible and monitor features). Then, after adding to Dockerfile all tinycore wireless related packages, finally I can see the wireless interfaces inside the container!!! that's a good step I think!

Then, the goal is to be able to put card on monitor mode. At the beginning it was impossible but after some tweaking on kernel_config finally I did it. Ok, Now I have a card in monitor mode on container, now the problem is after launching an airodump no packets are shown... so there must be a problem with the driver.

In my opinion I think the problem now is the driver and not related to kernel. Probably because of what you are saying... it seems the driver packages available maybe are not matching the kernel version.

If you agree, I can share here my advances... showing the url of the forked repo with my custom Dockerfile and kernel_config files... to see if we can create a boot2docker iso working for wireless devices.

**Comment by OscarAkaElvis** [comment]
I did it. This is my forked [boot2docker repository](https://github.com/OscarAkaElvis/boot2docker).

I pushed my changes on Dockerfile and kernel_config files. If anybody want to try something is welcome... as I said, at this point using virtualbox extension pack to connect usb devices into default boot2docker machine, we are able to see wireless interfaces inside container and to put them on monitor mode... but no packets captured. Something related to driver is wrong... I'll keep trying with different chipsets.

**Comment by gbraad** [comment]
Can you close this issue, as this does not seem to be a use-case that boot2docker will support... and it seems you have solved it with a fork.

**Comment by OscarAkaElvis** [comment]
I can close it but it is not working at all... It's almost working... but was unsuccessful in the end.
 Any help or suggestion?

**Comment by JBalanza** [comment]
Same problem here. I'd like to know if boot2docker does support already wireless capabilities with host USB interfaces?

**Comment by tianon** [comment]
Given the life-support-only status of boot2docker, I'm unfortunately going to close this -- we have no plans to support wireless drivers in boot2docker, and recommend folks use a more full-featured distribution such as Debian or Ubuntu if this is something necessary for your development use-case.
