### ISSUE TITLE
Include CEPH kernel support

### ISSUE THREAD

**Issue by alvarosimon** [boot2docker/boot2docker#1254]
It seems that CEPH filesystem is not supported from boot2docker kernel module:
`# CONFIG_CEPH_FS is not set`

It would be possible to include this? Ceph backend is quite common and it could be useful to mount a shared file system from the docker service.

**Comment by tianon** [comment]
It's still marked as "experimental" in the kernel, but Debian enables it as a module which is pretty decent justification for us doing the same.

For reference:

```
-- /usr/src/linux/fs/ceph/Kconfig:1 --
config CEPH_FS
	tristate "Ceph distributed file system"
	depends on INET
	select CEPH_LIB
	select LIBCRC32C
	select CRYPTO_AES
	select CRYPTO
	default n
	help
	  Choose Y or M here to include support for mounting the
	  experimental Ceph distributed file system.  Ceph is an extremely
	  scalable file system designed to provide high performance,
	  reliable access to petabytes of storage.

	  More information at http://ceph.newdream.net/.

	  If unsure, say N.

```

**Comment by tianon** [comment]
Also for reference, Debian's current config from unstable:
```ini
##
## file: fs/ceph/Kconfig
##
CONFIG_CEPH_FS=m
CONFIG_CEPH_FSCACHE=y
CONFIG_CEPH_FS_POSIX_ACL=y
```
