### ISSUE TITLE
/var/lib/boot2docker/docker.log eats up disk space

### ISSUE THREAD

**Issue by marcuslinke** [boot2docker/boot2docker#1256]
boot2docker starts the docker daemon with `-D` option which turns on daemons debug logging. When make use of the docker internal DNS from within a container this log is polluted with a lot of the following and eats up the disk space as it is never rotated/compacted. It seems when `-D` is set adding `--log-level` option (https://docs.docker.com/engine/reference/commandline/dockerd/#options) via EXTRA_ARGS is ignored also, so currently there is no possibility to workaround this issue.

```
time="2017-04-24T13:35:19.934517879Z" level=debug msg="Query consul.service.[1] from 172.19.0.2:42510, forwarding to udp:10.32.22.8" 
time="2017-04-24T13:35:19.934531018Z" level=debug msg="client dns id 21237, changed id 30334" 
time="2017-04-24T13:35:19.934960021Z" level=debug msg="dns msg id 30334, client id 21237" 
time="2017-04-24T13:35:19.935035817Z" level=debug msg="dns msg id 63750, client id 13980" 
time="2017-04-24T13:35:19.935213951Z" level=debug msg="Name To resolve: consul.service.ddev.natest.de." 
time="2017-04-24T13:35:19.935243753Z" level=debug msg="Query consul.service.ddev.natest.de.[28] from 172.19.0.2:42510, forwarding to udp:10.32.22.8" 
time="2017-04-24T13:35:19.935255641Z" level=debug msg="client dns id 58516, changed id 9838" 
time="2017-04-24T13:35:19.935442030Z" level=debug msg="Name To resolve: consul.service.ddev.natest.de." 
time="2017-04-24T13:35:19.935500127Z" level=debug msg="Query consul.service.ddev.natest.de.[1] from 172.19.0.2:42510, forwarding to udp:10.32.22.8" 
time="2017-04-24T13:35:19.935525097Z" level=debug msg="client dns id 24865, changed id 37952" 
time="2017-04-24T13:35:19.937609606Z" level=debug msg="dns msg id 9838, client id 58516" 
time="2017-04-24T13:35:19.937818770Z" level=debug msg="dns msg id 37952, client id 24865" 
time="2017-04-24T13:35:19.966334536Z" level=debug msg="Name To resolve: consul.service." 
time="2017-04-24T13:35:19.966496400Z" level=debug msg="Query consul.service.[1] from 172.19.0.2:42510, forwarding to udp:10.32.22.8" 
time="2017-04-24T13:35:19.966516747Z" level=debug msg="client dns id 44347, changed id 49139" 
time="2017-04-24T13:35:19.966442560Z" level=debug msg="Name To resolve: consul.service." 
```

**Comment by jolz** [comment]
same problem here. 
file has ~5.5G after few month.
logrotate would be fine.

**Comment by philippe-granet** [comment]
**Workaround:**
Create a persisted script /var/lib/boot2docker/bootsync.sh:
```
sed -i 's/dockerd -D /dockerd /' /usr/local/etc/init.d/docker
```
https://github.com/boot2docker/boot2docker/blob/master/doc/FAQ.md#local-customisation-with-persistent-partition
From Boot2Docker version 1.6.0, you can also specify steps that are run before the Docker daemon is started, using /var/lib/boot2docker/bootsync.sh.
Allow local bootsync.sh customisation run before docker started

**Comment by tianon** [comment]
Closing since this has a solid workaround and we don't set `-D` on `dockerd` anymore (https://github.com/boot2docker/boot2docker/blob/e02f5fa5fdd4e26adc4b8dbd10b413fbf2c39b76/files/init.d/docker#L227). :+1:
