### ISSUE TITLE
Why to restart boot2docker users to create all the files will disappear?

### ISSUE THREAD

**Issue by MrNsfocus** [boot2docker/boot2docker#1260]
M-2:docker $ docker-machine ssh docker
docker@docker:~$ 
docker@docker:~$ 
docker@docker:~$ ls
1111/
docker@docker:~$ mkdir 123
docker@docker:~$ ls
1111/ 123/
docker@docker:~$ exit
M-2:docker $ docker-machine stop docker
Stopping "docker"...
Machine "docker" was stopped.
M-2:docker $ docker-machine start docker
Starting "docker"...
(docker) Waiting for VM to start...
Machine "docker" was started.
Waiting for SSH to be available...
Detecting the provisioner...
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
M-2:docker $ docker-machine ssh docker
docker@docker:~$ ls
docker@docker:~$ ls
docker@docker:~$

**Comment by yosifkit** [comment]
It is the design of the boot2docker VM to save as little state as possible between restarts. 
 `/var/lib/boot2docker` would be the place to put persistent things.
