### ISSUE TITLE
Increase virtual box memory on windows environment

### ISSUE THREAD

**Issue by aashray-a-chetan** [boot2docker/boot2docker#1264]
I'm trying to change the virtual box memory each time the dockerfile is built using the following commands in the dockerfile:

docker-machine stop
VBoxManage modifyvm default --cpus 2
VBoxManage modifyvm default --memory 4096
docker-machine start

docker-machine command is not recognized. How do I go about doing this on windows environment?

**Comment by yosifkit** [comment]
If you installed boot2docker with docker-toolbox, then it should be in the path when you run the "Docker Quickstart terminal" (instead of cmd or Powershell).

**Comment by kishor-gujar** [comment]
The easiest way.
open VirtualBox stop VM
Select default and click on settings 
Make changes As you want.
Launch your Docker Quickstart Terminal.
