### ISSUE TITLE
REX-Ray support

### ISSUE THREAD

**Issue by FirefoxMetzger** [boot2docker/boot2docker#1267]
Over the past few days I've been testing REX-ray together with docker swarm on boot2docker.

One issue that I've had was that whenever I restart, I would have to reinstall rexray. While I could drop a script into `/var/lib/boot2docker/bootlocal.sh`, this is impractical. It means modifying each swarm node individually, as the script is stored on the node's local disk.

So what I did instead is I've created a custom boot2docker image, that comes with rexray 0.9.2 installed and starts the service during boot. Much more convenient and easier to keep the nodes normalized.

A few questions / issues are still open:

- only start rexray during boot if a config.yml is supplied -- where to best put that? Currently I am thinking of creating a symlink to `/var/lib/boot2docker/rexray/config.yml` but then I might as well revert to installing it during boot using `/var/lib/boot2docker/bootlocal.sh`
- the image now requires more than 500MB in memory, mainly because the rexray binary is ~55MB. The .iso is 64MB
- the install script could be improved to install the latest rexray version automatically during build.

I was wondering if people are interested in this approach. 
Also if there is a less troublesome way that I don't know about, please let me know :)

**Comment by purplesrl** [comment]
+1

**Comment by tianon** [comment]
Sorry for the delay here -- I'm honestly really surprised REX-Ray doesn't have a method of setting itself up via something like a `--restart=always` container (which would then be persistent even on distros like boot2docker), but I'd really recommend folks who need more complicated storage out of their solution move to a distribution more well-suited to handle such things (such as a Debian or Ubuntu VM -- `docker-machine` can manage those just as well as it manages `boot2docker` :+1:).
