### ISSUE TITLE
Mount additional disk to store docker volumes

### ISSUE THREAD

**Issue by rafaelsoaresbr** [boot2docker/boot2docker#1269]
Hello, is there a way to add additional disks (or NFS shares) and mount then inside the VM. There are cases that using vbox shared folders causes issues (wrong permissions, ownership).

The [issue](https://gitlab.com/gitlab-org/omnibus-gitlab/issues/2252) I'm having:

**Comment by gbraad** [comment]
You have two options that get triggered from the `bootscript.sh`

Before "Launch Docker"
https://github.com/boot2docker/boot2docker/blob/8c3082d16a1491e85c794e5e4a1fa37db3f1fc83/rootfs/rootfs/opt/bootscript.sh#L69

After "Launch Docker"
https://github.com/boot2docker/boot2docker/blob/8c3082d16a1491e85c794e5e4a1fa37db3f1fc83/rootfs/rootfs/opt/bootscript.sh#L78

**Comment by strarsis** [comment]
@gbraad: So I have to add the extra mount commands to the bootscript.sh?
Is there an alternative that avoids writing into this file, e.g. a user directory that boot2docker reads for additonal config?

**Comment by strarsis** [comment]
@gbraad: Where to find these configuration files in Docker Toolbox for Windows?
I am using WSL, but these configuration files are probably located at the Windows program files?

**Comment by tianon** [comment]
They're inside the boot2docker virtual machine, not on the host.

**Comment by strarsis** [comment]
@tianon: Thanks. But what if the docker-machine is removed and re-created? Can I somehow persist the config files?

**Comment by tianon** [comment]
I don't think so, unless you also persist the persistent storage of the VM.
