### ISSUE TITLE
Add support for docker-volume-vsphere

### ISSUE THREAD

**Issue by blop** [boot2docker/boot2docker#1270]
Hello,

It seems boot2docker already has VMware open-vm-tools preinstalled which is great.
However it lacks a least one kernel module in order to support the docker-volume-vsphere plugin.

https://github.com/vmware/open-vm-tools
https://github.com/vmware/docker-volume-vsphere

See details here : https://github.com/vmware/docker-volume-vsphere/issues/1744#issuecomment-322022123

Is possible to add support for that `vmw_vsock_vmci_transport` kernel module in boot2docker ?

Thanks.

**Comment by blop** [comment]
Got it working by forking boot2docker and enabling these modules in `kernel_config` : 

```
CONFIG_VSOCKETS=m
CONFIG_VMWARE_VMCI_VSOCKETS=m
```

Would be nice if this can be included as default ;)

**Comment by anonymez** [comment]
Is there any reason why this suggestion was not applied to the kernel_config in the master branch?

Thanks.

**Comment by tianon** [comment]
@frapposelli are you still the best point of contact for `open-vm-tools` integration? (and possibly willing to take a look at this and see if our `open-vm-tools` integration is still working or needs updates?)

**Comment by frapposelli** [comment]
@tianon I probably am 😄 what @blop makes sense, is there a PR open for that change?
