### ISSUE TITLE
On Hyper-V the keyvalue pool probably gets cleared when the HV-KVP module loads

### ISSUE THREAD

**Issue by gbraad** [boot2docker/boot2docker#1274]
We are implementing a way to provide settings using KVP to boot2docker, which can be used during the startup to influence the behaviour, like setting a static IP address. However, unlike the CentOS setup we use: https://github.com/minishift/minishift-centos-iso/pull/138, this seems to be problematic on B2D: https://github.com/minishift/minishift-b2d-iso/pull/61

What seems to happen is that the pool gets cleared on start... and will not be usable until about the module has been loaded (and some additional time). This means that our code needs to continuously re-send the values for an additional amount of seconds until it gets received: https://github.com/minishift/minishift/pull/1391/files#diff-46ad30f5b81c3b234d72a27dc2a8fac4R50 While the confirmation from WMI already indicates success, the value is not usable and available until the module is loaded. This is however not an issue to read the network values from the VM, it is an issue when writing values to the VM.

However, it is then still very unreliable to use the value to for instance set an IP address on startup.

**Comment by tianon** [comment]
Man, sorry for the huge delay here.

I'm not sure what it would take to fix this, but I do have concerns that doing so might encourage folks to use boot2docker in more places than they perhaps should, given the life-support-only and not-recommended-for-production status of its current maintenance.

**Comment by gbraad** [comment]
The Hyper-V integration should be compiled as part of the kernel. This
way the pool does not get cleared...

This is not meant for production use at all, but for integration and
convenience use with Minikube, Minishift, etc

On Thu, Apr 25, 2019 at 10:55 PM Tianon Gravi <notifications@github.com> wrote:
>
> Man, sorry for the huge delay here.
>
> I'm not sure what it would take to fix this, but I do have concerns that doing so might encourage folks to use boot2docker in more places than they perhaps should, given the life-support-only and not-recommended-for-production status of its current maintenance.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by tianon** [comment]
The latest releases include several bits specific to Hyper-V: https://github.com/boot2docker/boot2docker/blob/e02f5fa5fdd4e26adc4b8dbd10b413fbf2c39b76/files/kernel-config.d/hyperv

Is there a chance one of those is the one you're referring to?

**Comment by gbraad** [comment]
I'll have a look again, but we have since dropped support for boot2docker.

Not sure about the status for minikube, but since they have also since moved to their own distro, I think it is actually save to close this.

**Comment by tianon** [comment]
Honestly I think that's for the best. :+1: :heart:
