### ISSUE TITLE
How to configure static IP address for boot2dock VM

### ISSUE THREAD

**Issue by ngocphamm** [boot2docker/boot2docker#129]
Hi,

I would like to ask about configuring a static IP address for the `boot2docker` VM. I'm sorry if it's a dumb question.

My case is I cannot use VirtualBox because I have Parallels Desktop and it's a irresolvable (for now) issue for using the 2 platforms at the same time. That I cannot use the `boot2docker` init script, I need a way to configure static IP address for the VM, so I don't have to actually go to VM console and see the IP address every time I boot it up.

I tried to follow the guide [here](http://forum.tinycorelinux.net/index.php?topic=13781.0), but apparently because `boot2docker` is run from RAM so everything's lost except the persistent volume.

Could anyone please tell me how to achieve this?

Thank you.
Best.

**Comment by far-blue** [comment]
Just to add my thoughts and my 'hack':

I've currently got a couple of lines in bootlocal.sh that kills the dhcp process for the interfaces I don't want it on, sets a static IP address and then restarts the docker daemon. With the release of 1.6.0 boot2docker iso I'll move this all to the bootsync.sh script so I don't need to restart docker :) This is the code I currently use:

```
kill `more /var/run/udhcpc.eth1.pid`
ifconfig eth1 192.168.99.102 netmask 255.255.255.0 broadcast 192.168.99.255 up
```

**Comment by StalkAlex** [comment]
For me with lines above internet inside docker machine isn't working, so I added this command `route add default gw 192.168.1.1` to specify correct gateway.

**Comment by gurushantj** [comment]
Hello,
Is there any to get the next ip (of a network) for a container ?
Or how docker chooses IP to be assigned to the container.
Actually i have written a script to generate the valid IP set from the subnet ip range.
However , some time i get an error saying " context deadline exceeded" 
Thanks,
Gurushant

**Comment by suresh1566** [comment]
We can set permanet ip address for docker machine in two way:

Option 1:
Start the docker machine then use below command:

[suresh@suresh ~]$ docker-machine start manager1

echo "ifconfig eth1 <ip address> netmask <netmask ip> broadcast <broadcast ip>" | docker-machine ssh <docker machine name> sudo tee /var/lib/boot2docker/bootsync.sh > /dev/null

echo "ifconfig eth1 192.168.99.100 netmask 255.255.255.0 broadcast 192.168.99.255 up" | docker-machine ssh manager1 sudo tee /var/lib/boot2docker/bootsync.sh > /dev/null

Restart docker machine:

[suresh@suresh ~]$ docker-machine stop worker1

[suresh@suresh ~]$ docker-machine start worker1

Veify ip address:
[suresh@suresh ~]$ docker-machine ip worker1 
192.168.99.100

Option 2:
Start the docker machine then connect to docker machine and make the following changes:

[suresh@suresh ~]$ docker-machine start worker1

[suresh@suresh ~]$ docker-machine ssh worker1

Create the bootsync.sh file and make following changes:
docker@worker1:~$ sudo vi /var/lib/boot2docker/bootsync.sh
ifconfig eth1 192.168.99.101 netmask 255.255.255.0 broadcast 192.168.99.255 up

[suresh@suresh ~]$ docker-machine stop worker1

[suresh@suresh ~]$ docker-machine start worker1

Veify ip address:
[suresh@suresh ~]$ docker-machine ip worker1 
192.168.99.101
