### ISSUE TITLE
How to change mount from /mnt/vda1 to something else? 

### ISSUE THREAD

**Issue by retraut** [boot2docker/boot2docker#1295]
I have some reasons to change mountpoint for persistance data in boot2docker. 
I see that now I have the next links in my machine
```
/var/lib/boot2docker -> /mnt/vda1/var/lib/boot2docker
/var/lib/docker      -> /mnt/vda1/var/lib/docker

```
I want change my disk mount to something like `/disk`, and change my mountpoints to the next values

```
/var/lib/boot2docker -> /disk/var/lib/boot2docker
/var/lib/docker      -> /disk/var/lib/docker
```

How can I do this?

**Comment by tianon** [comment]
You'll want to modify something in:

https://github.com/boot2docker/boot2docker/blob/e81861979593e5c2692888fdd5d022ddbf39615b/rootfs/rootfs/etc/rc.d/automount#L95-L137

Not sure I understand the use case, but hopefully that gives you enough to get something started and/or working!  It's definitely not something we're going to officially support, so I'm going to close this issue. :heart:
