### ISSUE TITLE
build Dockfile: `cgroups: cannot found cgroup mount destination: unknown`

### ISSUE THREAD

**Issue by lazysa** [boot2docker/boot2docker#1296]
Env:  Windows7 X86_64 / Windows10 X86_64 / Docker tools 
When:  docker build Dockerfile
Last released (v17.09.1-ce / boot2docker.iso) is ok

**Comment by tianon** [comment]
I just tested with the v17.12.0-ce release ISO and cannot reproduce:

```console
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 17.12.0-ce, build HEAD : 378b049 - Wed Dec 27 23:39:20 UTC 2017
Docker version 17.12.0-ce, build c97c6d6
docker@boot2docker:~$ docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:05:38 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	false
docker@boot2docker:~$ echo -e 'FROM bash\nRUN echo hi' | docker build -
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM bash
latest: Pulling from library/bash
1160f4abea84: Pull complete 
35c12c862670: Pull complete 
50313e686d4e: Pull complete 
Digest: sha256:b146a2e9aadaf2ed4a540324094412f2cd3f609f8a2f55ed608285f85f12a0f1
Status: Downloaded newer image for bash:latest
 ---> a853bea42baa
Step 2/2 : RUN echo hi
 ---> Running in e70203793a03
hi
Removing intermediate container e70203793a03
 ---> 9b44a2bc9c39
Successfully built 9b44a2bc9c39
```

**Comment by lazysa** [comment]
thanks , I don't known this is or not a bug .
I copy old release(boot2docker.iso) to `C:\Users\work\.docker\machine\machines\default\`
looks runing well.
___
**root@default:/c/Users/work/docker/ansible/dockfile#** docker version
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:38 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: false

**root@default:/c/Users/work/docker/ansible/dockfile#** docker build -t ansible/test:v1 .
Sending build context to Docker daemon  3.584kB
Step 1/2 : FROM ansible/centos7-ansible:latest
 ---> 688353a31fde
Step 2/2 : RUN baseApps='openssh-server net-tools lsof vim'     && yum install -y $baseApps     ; sed -i.bak 's/^#PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config     ; echo 'set encoding=utf-8' > /root/.vimrc     ; echo "alias ad='ansible-playbook -i /mnt/ansible/hosts /mnt/ansible/deploy/site.yml'" >> /root/.bashrc     && echo 'export PATH=$PATH:/opt/ansible/ansible/bin' >> /root/.bash_profile
 ---> Running in c5e8c5acadfb
**cgroups: cannot found cgroup mount destination: unknown**

___
**root@default:/c/Users/work/docker/ansible/dockfile#** docker version
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:21:47 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:28:28 2017
 OS/Arch:      linux/amd64
 Experimental: false

**root@default:/c/Users/work/docker/ansible/dockfile#** docker build -t ansible/test:v1 .
...
Complete!
 ---> f3e00045e69c
Removing intermediate container c67d1c4c2f25
Successfully built f3e00045e69c
Successfully tagged ansible/test:v1
