### ISSUE TITLE
Version 17.12.0-ce-rc2 introduced key binding problems for bash

### ISSUE THREAD

**Issue by beikov** [boot2docker/boot2docker#1299]
So I played around with different versions and noticed that 17.12.0-ce-rc1 was the last version that had proper support for key bindings in bash.
On Windows with Docker Toolbox I use `docker-machine ssh` and then after installing bash via `tce-load -wi bash` I start bash. Within bash, if I enter some text and then press the backspace key, but the cursor doesn't move back anymore since 17.12.0-ce-rc2. I'm using a proper .inputrc file that looks like the following

```
set completion-ignore-case on

# ctrl-left/right
"\e[1;5C": forward-word   # ctrl + right
"\e[1;5D": backward-word  # ctrl + left 
"\e\e": kill-whole-line

DEL: delete-char
"\e[1~": beginning-of-line
"\e[4~": end-of-line
```

I tested up to version v18.01.0-ce and all have the same problem. Seems to be a problem with Tiny Core Linux 8.x.

**Comment by tianon** [comment]
If you also install `ncurses-terminfo`, the problem should go away (since then Bash will have a proper terminfo file for your `TERM` value). :+1:
