### ISSUE TITLE
Cannot login in docker registry from docker-machine

### ISSUE THREAD

**Issue by MaxCCC** [boot2docker/boot2docker#1302]
I've running a docker registry in Artifactory on https://server/artifactory.
When I bypass the reverse proxy I'm able to login on the registry using:
`$ docker login http://server:8081`

Now it's forbidden to bypass the reverse proxy. So I need to trust the cert inside my docker machine before I can login in my docker registry.

```
$ docker login https://server/artifactory
Error response from daemon: Get https://server/v2/: x509: certificate signed by unknown authority
```

Now I've created a folder certs:  `/var/lib/boot2docker/certs/` and copied my rootca.pem in it. Rebooted the machine:
Now I get the following error after a `docker login`:
`Error response from daemon: login attempt to https://server/v2/ failed with status: 404 Not Found
`

Where do I have to import my root CA? Is this enough to accept the certs and to make authenticating possible?

**Comment by tianon** [comment]
The argument for `docker login` should be just the hostname and port, just like it would be specified in the image names for pushing to it (ala `server:8081/image/name`).  Try `docker login server:8081`.

You could also try configuring Docker to allow insecure registries to avoid dealing with certificates at all: https://docs.docker.com/registry/insecure/

Regardless, this doesn't seem to be an issue with boot2docker itself, and more an issue of usage.
