### ISSUE TITLE
Can not use --registry-mirror using subpath

### ISSUE THREAD

**Issue by MaxCCC** [boot2docker/boot2docker#1303]
We have a mirror on `https://server/docker`. We can pull images using `docker pull server/docker/image`.
Now I want to add https://server/docker as my mirror in docker machine so when I pull docker busybox it will actually pull `server/docker/busybox`.

The problem is the daemon does not want to restart after adding:

`--registry-mirror https://server/docker`

to my boot2docker profile + restarting. When I remove the `/docker` it works and I can pull the image using docker pull `docker/busybox` but this is not the behaviour I want to use.

**Comment by yosifkit** [comment]
That looks like a general limitation of Docker's `registry-mirror` setting and not something specific to Boot2Docker.  So it should be filed on the main Docker repo: https://github.com/moby/moby/issues.

**Comment by tianon** [comment]
Looks like the proposed solution for https://github.com/moby/moby/pull/34319 _might_ allow for this sort of thing, so I'd recommend following along over there (and perhaps testing the implementation). :+1:
