### ISSUE TITLE
losetup fails on versions >= v17.12.0-ce with I/O errors in dmesg

### ISSUE THREAD

**Issue by chacal** [boot2docker/boot2docker#1304]
I'm using a docker container to build an SD card image using loopback devices. After upgrading boot2docker I noticed that my build was failing and further investigation suggests that something was changed between boot2docker versions v17.11.0-ce and v17.12.0-ce that causes partition scans on loopback devices to fail.

I was able to reproduce the issue by manually creating an empty disk image, adding a single partition on it and then trying to create a loopback device out of it. Creation with properly recognised partition succeeds on boot2docker v17.11.0-ce, but not on any more recent version.

Steps to reproduce the problem:

1. Download the .zipped [sample disk image file](https://github.com/boot2docker/boot2docker/files/1723552/disk_image.bin.zip) (contains one partition, but no file systems)
1. Unzip the disk image file to some temporary location
1. Setup boot2docker Docker machine
1. Run `docker run --privileged -it --rm -v /dev:/dev -v $(pwd):/tmp ubuntu /bin/bash -c "losetup --partscan --show --find /tmp/disk_image.bin; sync; sleep 5; ls -la /dev/loop*; lsblk"`

On a working boot2docker version the output is something like:
```
/dev/loop0
crw------T 1 root root   10, 237 Feb 14 10:27 /dev/loop-control
brw-rw---- 1 root staff   7,   0 Feb 14 10:28 /dev/loop0
brw-rw---- 1 root staff 259,   0 Feb 14 10:28 /dev/loop0p1
brw-rw---- 1 root staff   7,   1 Feb 14 10:27 /dev/loop1
brw-rw---- 1 root staff   7,   2 Feb 14 10:27 /dev/loop2
brw-rw---- 1 root staff   7,   3 Feb 14 10:27 /dev/loop3
brw-rw---- 1 root staff   7,   4 Feb 14 10:27 /dev/loop4
brw-rw---- 1 root staff   7,   5 Feb 14 10:27 /dev/loop5
brw-rw---- 1 root staff   7,   6 Feb 14 10:27 /dev/loop6
brw-rw---- 1 root staff   7,   7 Feb 14 10:27 /dev/loop7
NAME      MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda         8:0    0  19.5G  0 disk
|-sda1      8:1    0  18.6G  0 part /etc/hosts
`-sda2      8:2    0 964.8M  0 part [SWAP]
sr0        11:0    1    39M  0 rom
loop0       7:0    0     3M  0 loop
`-loop0p1 259:0    0     2M  0 loop
zram0     251:0    0 193.4M  0 disk [SWAP]
```

With boot2docker >= v17.12.0-ce the output is:
```/dev/loop0
crw------T 1 root root  10, 237 Feb 14 10:30 /dev/loop-control
brw-rw---- 1 root staff  7,   0 Feb 14 10:30 /dev/loop0
brw-rw---- 1 root staff  7,   1 Feb 14 10:30 /dev/loop1
brw-rw---- 1 root staff  7,   2 Feb 14 10:30 /dev/loop2
brw-rw---- 1 root staff  7,   3 Feb 14 10:30 /dev/loop3
brw-rw---- 1 root staff  7,   4 Feb 14 10:30 /dev/loop4
brw-rw---- 1 root staff  7,   5 Feb 14 10:30 /dev/loop5
brw-rw---- 1 root staff  7,   6 Feb 14 10:30 /dev/loop6
brw-rw---- 1 root staff  7,   7 Feb 14 10:30 /dev/loop7
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    0  19.5G  0 disk
|-sda1   8:1    0  18.6G  0 part /etc/hosts
`-sda2   8:2    0 964.8M  0 part [SWAP]
sr0     11:0    1    45M  0 rom
loop0    7:0    0     3M  1 loop
zram0  251:0    0 162.5M  0 disk [SWAP]
```

In addition to missing partition, I/O errors can be found in the dmesg of the failing boot2docker:
```blk_update_request: I/O error, dev loop0, sector 0
Buffer I/O error on dev loop0, logical block 0, async page read
blk_update_request: I/O error, dev loop0, sector 0
Buffer I/O error on dev loop0, logical block 0, async page read
 loop0: unable to read partition table
loop_reread_partitions: partition scan of loop0 (/tmp/disk_image.bin) failed (rc=-5)
blk_update_request: I/O error, dev loop0, sector 6016
blk_update_request: I/O error, dev loop0, sector 6016
Buffer I/O error on dev loop0, logical block 752, async page read
blk_update_request: I/O error, dev loop0, sector 6016
blk_update_request: I/O error, dev loop0, sector 6016
Buffer I/O error on dev loop0, logical block 752, async page read
```

Any ideas what could cause these failures?

**Comment by tianon** [comment]
https://github.com/boot2docker/boot2docker/compare/v17.11.0-ce...v17.12.0-ce isn't very big, but includes a switch of our build environment from Jessie to Stretch _and_ a TCL update from 7.x to 8.x, so there must be something between those that's caused this to change (since the kernel version and kernel config didn't really change much)

Another possibility could be the VBox guest addition update causing other strange changes, but that seems a lot less likely.

**Comment by tianon** [comment]
Is this still an issue on the latest releases?
