### ISSUE TITLE
cifs install error

### ISSUE THREAD

**Issue by jianbosu** [boot2docker/boot2docker#1312]
i install needed packages by cli:
--------------------------------------------------------------------------------
#!/bin/sh
#安装所有需要的包
su - docker -c "tce-load -i /var/lib/boot2docker/tczpacks/*.tcz"

#挂载外部共享目录
if [ ! -e /mnt/ws ]; then
    sudo mkdir /mnt/ws
fi
sudo mount -t cifs //wingate-sking/D /mnt/ws -o user=1,pass=1
------------------------------------------------------------------------------------------
root@nct1:/mnt/sda1/var/lib/boot2docker/tczpacks# ls
cifs-utils.tcz                      filesystems-4.14.10-tinycore64.tcz
docker-compose-Linux-x86_64         mtd-4.14.10-tinycore64.tcz
------------------------------------------------------------------------------------------
/dev/loop0 on /mnt/sda1/tmp/tcloop/cifs-utils type squashfs (ro,relatime)
/dev/loop1 on /mnt/sda1/tmp/tcloop/filesystems-4.14.10-tinycore64 type squashfs (ro,relatime)
/dev/loop2 on /mnt/sda1/tmp/tcloop/mtd-4.14.10-tinycore64 type squashfs (ro,relatime)
-----------------------------------------------------------------------------------------
ls -la /sbin 
mount.cifs -> /mnt/sda1/tmp/tcloop/cifs-utils/usr/local/sbin/mount.cifs.
root@nct1:/mnt/sda1/tmp/tcloop/cifs-utils/usr/local/sbin# ls -al
total 48
drwxr-xr-x    2 root     staff           70 Apr  6  2012 .
drwxr-sr-x    6 root     staff           72 Apr  6  2012 ..
-rwxr-xr-x    1 root     root          4448 Apr  6  2012 cifs.idmap
-rwxr-xr-x    1 root     root         21468 Apr  6  2012 cifs.upcall
-rwsr-xr-x    1 root     root         22752 Apr  6  2012 mount.cifs
----------------------------------------------------------------------------------------
root@nct1:/mnt/sda1/tmp/tcloop/cifs-utils/usr/local/sbin# mount.cifs
-sh: mount.cifs: not found

why?

**Comment by tianon** [comment]
Officially, we don't support `tce-load`.

The best I can do is recommend checking the output of `ldd /mnt/sda1/tmp/tcloop/cifs-utils/usr/local/sbin/mount.cifs` and see if you're missing any `.so` files it requires (because that's the mostly likely cause of the error you see).

It could also be that the `tcloop` path isn't in your `PATH`, so you should try doing `./mount.cifs` directly too and see if that works any better.

**Comment by tianon** [comment]
(Closing since this is an issue with usage, not with the ISO/distro itself.)
