### ISSUE TITLE
Can't create machine with 'vmwarefusion' driver

### ISSUE THREAD

**Issue by KamilKopaczyk** [boot2docker/boot2docker#1315]
Hello,

currently there is not way to create 'vmarefusion' machine. 
I checked it on boot2docker versions: 
* v18.03.0
* v18.04.0-ce-rc2

with docker-machine:
* 0.14.0
* 0.13.0 (it works with this version - see description below)

Here's the log without 'debug' enabled

```
docker-machine create --driver vmwarefusion --vmwarefusion-boot2docker-url https://github.com/boot2docker/boot2docker/releases/download/v18.04.0-ce-rc2/boot2docker.iso default1

Running pre-create checks...
(default1) Boot2Docker URL was explicitly set to "https://github.com/boot2docker/boot2docker/releases/download/v18.04.0-ce-rc2/boot2docker.iso" at create time, so Docker Machine cannot upgrade this machine to the latest version.
Creating machine...
(default1) Boot2Docker URL was explicitly set to "https://github.com/boot2docker/boot2docker/releases/download/v18.04.0-ce-rc2/boot2docker.iso" at create time, so Docker Machine cannot upgrade this machine to the latest version.
(default1) Downloading /Users/kamil/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v18.04.0-ce-rc2/boot2docker.iso...
(default1) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
(default1) Creating SSH key...
(default1) Creating VM...
(default1) Creating disk '/Users/kamil/.docker/machine/machines/default1/default1.vmdk'
(default1) Virtual disk creation successful.
(default1) Starting default1...
(default1) Waiting for VM to come online...
Error creating machine: Error in driver during machine creation: exit status 255
```

Here are last few and essential lines from output with 'debug' enabled

```
[...]
(default1) DBG | executing: /Applications/VMware Fusion.app/Contents/Library/vmrun -gu docker -gp tcuser CopyFileFromHostToGuest /Users/kamil/.docker/machine/machines/default1/default1.vmx /Users/kamil/.docker/machine/machines/default1/userdata.tar /home/docker/userdata.tar
(default1) DBG | executing: /Applications/VMware Fusion.app/Contents/Library/vmrun -gu docker -gp tcuser runScriptInGuest /Users/kamil/.docker/machine/machines/default1/default1.vmx /bin/sh sudo sh -c "tar xvf /home/docker/userdata.tar -C /home/docker > /var/log/userdata.log 2>&1 && chown -R docker:staff /home/docker"
(default1) DBG | executing: /Applications/VMware Fusion.app/Contents/Library/vmrun -gu docker -gp tcuser runScriptInGuest /Users/kamil/.docker/machine/machines/default1/default1.vmx /bin/sh sudo /bin/mv /home/docker/userdata.tar /var/lib/boot2docker/userdata.tar
(default1) DBG | executing: /Applications/VMware Fusion.app/Contents/Library/vmrun -gu docker -gp tcuser enableSharedFolders /Users/kamil/.docker/machine/machines/default1/default1.vmx
Error creating machine: Error in driver during machine creation: exit status 255
notifying bugsnag: [Error creating machine: Error in driver during machine creation: exit status 255]
```

From what i found out, this issue could be present for a very long time. With docker-machine upgrade from 0.13.0 to 0.14.0 they started checking for errors from command outputs, so previously this issue might have popped up, but was ignored.

I'm able to reproduce it, so if you have any further request please let me know.

This might be related: https://github.com/wplib/wplib-box/issues/98#issuecomment-229820096

**Comment by tianon** [comment]
cc @frapposelli 😇

**Comment by KamilKopaczyk** [comment]
Good to know that there is a working solution, thanks!

Have you looked at the link i included at the end of my report? Maybe this issue can be fixed by installing newer open-vm-tools? (newest version is 10.2.5-8068406 vs currently used v10.0.0-3000743 from August 2015)
If there is some easy way for me to check it, please let me know. There's no manual on how to do it, but i guess that .iso file can be built, by running Dockerfile?

**Comment by jgangemi** [comment]
i'm experiencing this issue which i think is related: https://github.com/docker/machine/issues/4479

**Comment by mraligorithm** [comment]
I have had the same issue but I was able to resolve it by regenerating the certs for my docker-machine that failed in the creation process. `docker-machine regenerate-certs [NAME OF THE FAILED Docker Machine]`, I am running it on 2015 Mac OS Mojave hope this helps.

**Comment by jgangemi** [comment]
are you saying that regenerating the certs successfully enables shared folders?

**Comment by koksin** [comment]
my problem seem to resolve after regenerate-certs as what mraligorithm stated.  Please see this link
https://github.com/sparkfabrik/sparkdock/issues/14

**Comment by jgangemi** [comment]
@koksin i don't know if what you referenced is the same problem unless some how regenerating the certs causes mounting of the volume to some how be successful.

sad that there hasn't been any movement on this issue either way.

**Comment by tianon** [comment]
Closing since this is really a bug in `docker-machine`'s built-in `vmwarefusion` driver, not boot2docker.

(See https://github.com/boot2docker/boot2docker/issues/1340 and https://github.com/boot2docker/boot2docker/pull/1350 for a more recent VMware-related issue that will be fixed in the next ISO release.)

**Comment by koksin** [comment]
Ok noted.

Sent from Mail for Windows 10

**Comment by dexguitar** [comment]
@mraligorithm thanks a lot! That's a viable solution!
