### ISSUE TITLE
/etc/sysconfig/language

### ISSUE THREAD

**Issue by kudzuu** [boot2docker/boot2docker#1320]
Any way to generate locale in UTF8?

**Comment by tianon** [comment]
This is going to need to be accomplished in whatever way one would normally do so in Tiny Core Linux (which from http://forum.tinycorelinux.net/index.php?topic=19547.0, appears to be via the "getlocale" package, but I wasn't able to get much success with that).

Honestly, I'd recommend using a different distribution if you need more from the Docker VM host than what's provided by boot2docker (one more focused on customization such as Debian or Ubuntu).
