### ISSUE TITLE
Trying to run it in bochs

### ISSUE THREAD

**Issue by wasiher** [boot2docker/boot2docker#1327]
Hi, I am trying to run it in bochs
It always launches like this:
![screen shot 2018-08-05 at 02 45 52](https://user-images.githubusercontent.com/3988683/43681360-cf6c4a52-9859-11e8-8a94-619108d02a2a.png)
It quicky prints following lines, and stays like this forever.
No kernel panics etc

Have any ideas what is wrong?

**Comment by tianon** [comment]
When you say "forever", how long did you wait?  There are a number of
things that run at startup that can take a really long time depending on
certain factors.

**Comment by wasiher** [comment]
Maybe an hour I think. I can retest in needed invironment if it is needed.
I also launched in qemu. And it worked fine.
And I noticed 1 strange thing. Not sure if it is important.
While I was using qemu "Loading /boot/initrd.img" line was loading for some time.
And when I was using bochs it was instant.

**Comment by tianon** [comment]
No an hour should've been enough 😕

**Comment by tianon** [comment]
Is this still an issue with the latest (18.09.0) release?

**Comment by tianon** [comment]
(If so, steps for reproducing would be helpful. :+1:)

**Comment by tianon** [comment]
I tried with https://packages.debian.org/stretch/bochs, and got further, but I get a bochs CPU PANIC after `Booting the kernel.`:

```
71111876734i[IOAP ] IOAPIC: arbitration ID unsupported, returned 0
71533658315e[CPU0 ] RDMSR: Unknown register 0x1a0
71533658372e[CPU0 ] WRMSR: Unknown register 0x8b
71533658377e[CPU0 ] RDMSR: Unknown register 0x8b
71533658433e[CPU0 ] RDMSR: Unknown register 0x1a0
71533662147i[CPU0 ] WARNING: Architectural Performance Monitoring is not implemented
71533662173e[CPU0 ] RDMSR: Unknown register 0x1a0
71533664345e[CPU0 ] RDMSR: Unknown register 0x1b0
71533667430e[CPU0 ] WRMSR: Unknown register 0x1b0
71533667442e[CPU0 ] RDMSR: Unknown register 0x140
71533667465e[CPU0 ] RDMSR: Unknown register 0xce
71533667499e[CPU0 ] WRMSR: Unknown register 0x140
71533667919e[CPU0 ] RDMSR: Unknown register 0x179
71533670019e[CPU0 ] RDMSR: Unknown register 0x179
71533670048e[CPU0 ] RDMSR: Unknown register 0x17a
71533670108e[CPU0 ] RDMSR: Unknown register 0x179
71533670153e[CPU0 ] RDMSR: Unknown register 0x1a0
71533670194e[CPU0 ] RDMSR: Unknown register 0x19b
71533670219e[CPU0 ] WRMSR: Unknown register 0x19b
71533670231e[CPU0 ] RDMSR: Unknown register 0x1b2
71533670256e[CPU0 ] WRMSR: Unknown register 0x1b2
71533670266e[CPU0 ] RDMSR: Unknown register 0x1a0
71533670284e[CPU0 ] WRMSR: Unknown register 0x1a0
71533671869e[CPU0 ] RDMSR: Unknown register 0x179
71539791498i[CPU0 ] Enter to System Management Mode
71539791498i[CPU0 ] enter_system_management_mode: temporary disable VMX while in SMM mode
71539791508i[CPU0 ] RSM: Resuming from System Management Mode
71539791508e[CPU0 ] check_CR4(): attempt to set CR4.PCIDE when EFER.LMA=0
71539791508p[CPU0 ] >>PANIC<< SMM restore: CR4 consistency check failed !
71539791508p[CPU0 ] >>PANIC<< RSM: Incorrect state when restoring CPU state - shutdown !
71539791508p[CPU0 ] >>PANIC<< Entering to shutdown state still not implemented
```

Not sure if my `bochsrc` file is just bad or what's up -- I don't think this is something specific to boot2docker, though.

**Comment by tianon** [comment]
![image](https://user-images.githubusercontent.com/161631/48923745-18814500-ee66-11e8-9008-1d09543d4256.png)

**Comment by wasiher** [comment]
Looks similar. But never finishes loading.
![screenshot 2018-12-03 at 03 01 18](https://user-images.githubusercontent.com/3988683/49343161-d1862180-f6a7-11e8-8882-14e82739a3af.png)

**Comment by wasiher** [comment]
Maybe I am doing something wrong too. Thx for response. I will write if I'll get any info more.

**Comment by wasiher** [comment]
I lied, everything works. Thank you.
![screenshot 2018-12-03 at 03 36 43](https://user-images.githubusercontent.com/3988683/49343448-ae11a580-f6ac-11e8-9dbc-7135b0799da1.png)
