### ISSUE TITLE
race-condition: ssh-login possible before system boot has completed

### ISSUE THREAD

**Issue by umlaeute** [boot2docker/boot2docker#1331]
I'm running `boot2docker` as a VirtualBox VM to be used as a [gitlab-runner](https://docs.gitlab.com/runner/) (for securely building docker images, without built-in privilege escalation...).

For this to work, I need to install some additional files (`bash`, a local `gitlab-runner`) inside the VM.

Currently the only way (I know of) to install additional packages, is by running `tce-load` in the `/var/lib/boot2docker/bootsync.sh` script.

Unfortunately, this gives me a race-condition, as the `GitLab-CI` keeps trying to login via ssh while my VM boots - and as soon as it succeeds it wants to execute `/bin/bash`, which might not be there yet (depending on whether the `/bootsync.sh` has already been executed or not).

It would be great to be able to run a user-provided script before anybody (locally or remotely) is allowed to log into the system, possibly before *any* daemon is started.

This might also allow me to do something about #1330.

**Comment by kaosagnt** [comment]
Your only option is to modify /etc/init.d/tc-config directly and copy it into a new build.

The boot system is not upstart or systemd.....

```
FROM boot2docker/boot2docker:latest

ADD files/etc/init.d/tc-config $ROOTFS/etc/init.d/

RUN /tmp/make_iso.sh

CMD ["cat", "boot2docker.iso"]
```
files/etc/init.d/tc-config is your modified version.

**Comment by tianon** [comment]
While I agree this sounds less than ideal (and likely something we should
try to fix if we can), I'd really recommend that you should probably be
looking at something like Debian, Ubuntu, Fedora, etc instead of
boot2docker for the project you're working on -- boot2docker is really only
still maintained to ensure that "docker-machine" users still have their
default environment available.

**Comment by umlaeute** [comment]
hmm, well fair enough.
(although, my need is really for a minimal VM that allows me to run docker containers and which boots *fast*...this awfully sounds like `boot2docker` and not at all like Debian/Fedora/...)

**Comment by tianon** [comment]
If you're willing to use systemd, my experience with Debian has been
that it boots really fast.  If you're wanting _really_ minimal,
something based on Alpine Linux might be easier to use/maintain long
term.

If you just want something that has Docker out of the box, RancherOS
and CoreOS are both decent options (RancherOS having the benefit of
also being very lightweight).

**Comment by tianon** [comment]
Can you try this again on the new 18.09 ISO to verify that it's still an issue with the latest release? (which includes a pretty major rewrite of many of the boot processes / ISO creation)

**Comment by tianon** [comment]
Closing due to lack of reproducer.  If this is something we can reliably reproduce, it'd be a lot easier to work on a fix. :smile:
