### ISSUE TITLE
Nvidia Docker 

### ISSUE THREAD

**Issue by Bit-Beast** [boot2docker/boot2docker#1335]
How can I run nvidia docker in boot2docker?

**Comment by yosifkit** [comment]
As far as I understand it, that would involve first giving your VM access to the video card of the host machine (assuming running on a laptop or desktop) and then installing nvidia drivers and cuda support in boot2docker which is based on Tiny Core Linux, but it seems the [Nvidia-docker installation instructions](https://github.com/NVIDIA/nvidia-docker/tree/9f3d92ec63a5cb74a923af44e4740c624f869a65#quickstart) only support running on `apt` or `yum` based systems so I would recommend using one of those instead (Debian, Ubuntu, CentOS, Oracle Linux, etc).
