### ISSUE TITLE
Keep boot2docker alive! (?)

### ISSUE THREAD

**Issue by michael-lachmann** [boot2docker/boot2docker#1337]
I think there is one important feature that boot2docker allows, which as far as I know Docker for Mac and Docker for Windows do not provide:
It is very useful that one can give boot2docker as an iso on which people many years from now will be sure to be able to run a particular image. This is especially useful for reproducibility of programs in scientific papers. A Dockerfile will probably work for a few months/years, an image maybe for as long as docker doesn't change image format and computers maintain binary compatibility to intel, but an iso will probably run for a long time, even if docker itself disappears.

So please keep this project up! It is quite important!

**Comment by tianon** [comment]
If you look at https://github.com/boot2docker/boot2docker/graphs/contributors and https://github.com/boot2docker/boot2docker/releases, you'll see we're still pretty active.  Mostly we don't want a lot of new features or new use cases.

Don't despair, we haven't gone anywhere. :+1:
