### ISSUE TITLE
tinycore default "top" not work with batch mode (-b) 

### ISSUE THREAD

**Issue by qxo** [boot2docker/boot2docker#1339]
top -bn1==>
'dumb': unknown terminal type
==>  /usr/local/bin/top
but  "busybox top -bn1" work fine

in boot2docker should link top to busybox

**Comment by tianon** [comment]
I just tested on 18.09.0 and cannot reproduce -- are you sure you're running this from a properly configured terminal?  via `ssh`?  It's definitely not a given for `top` to be provided by BusyBox, so it would be entirely reasonable for it to require `TERM` to be set appropriately.

**Comment by qxo** [comment]
Yes,It's cannot reproduce on 18.09
I'm tested on 18.06 and before version

**Comment by tianon** [comment]
Awesome, thanks for confirming!
