### ISSUE TITLE
Mapping port not exposed by stack deploy!

### ISSUE THREAD

**Issue by supermanHub** [boot2docker/boot2docker#1349]
## Issue description
I create a docker swarm cluster by docker-machine, and stack deploy a service to the cluster. After service start, I can't access it from `node IP:service port`. This issue is only exist on the version `v18.09.0`.

I'd test it on version `v18.09.0-rc1`, there is no  such issue. 

## Environment
Boot2Docker Version: `v18.09.0`
Docker version: 18.06.1-ce, build e68fc7a
DockerMachine version: 0.15.0, build b48dc28d
Virtualbox version: 5.2.22 r126460
OS version: macOS Mojave v10.14.1

## How to re-produce

Open a terminal and execute the following command one by one

1. `docker-machine create --driver virtualbox vm1`, 
2. `docker-machine ls` and make sure the **ip of vm1 is 192.168.99.100**
3. `docker-machine ssh vm1 "docker swarm init --advertise-addr 192.168.99.100"`
4. `eval $(docker-machine env vm1)`
5. `docker stack deploy -c docker-compose.yaml nimabi` docker-compose.yaml is in below
6. `docker stack ps nimabi` to make sure service container is running!
7. Open browser and access [http://192.168.99.100](http://192.168.99.100) and you will find the connection is refused! when your goto the service container to check the log, there is no income request!

## Resources

1. docker-compose.yaml

```js
version: "3.6"
services:
  nginx:
    image: nginx:1.15.6
    ports:
      - 80:80
    networks:
      - webnet
networks:
  webnet:
```

**Comment by nguyenngoctranvu** [comment]
I got same problem.

**Comment by sampeson** [comment]
I can also confirm

**Comment by tianon** [comment]
Please use the "thumbs up" reaction feature instead of spamming the issue with additional comments.

Is this a known issue in Docker 18.09.0 or is this definitely a bug in boot2docker? (that's the first place to start to narrow down where the fix for this might belong)

**Comment by supermanHub** [comment]
Because of docker 18.09.0 stable for mac is not release yet, so i am not sure whether is it a bug of docker or not! 

BTW, I test it on docker edge version(should be 18.09.0)for mac, the issue is exist too!



发自我的 iPhone

**Comment by supermanHub** [comment]
**Please use the "thumbs up" reaction feature instead of spamming the issue with additional comments.**

for upon, I am not sure what I have todo, could you please give me some guidelines or demo? Thanks 

Send from Jackie’s iPhone

**Comment by yosifkit** [comment]
This is an upstream Docker issue and not a problem specific to boot2docker.  It should be fixed in the next release (18.09.1).

Two possible workarounds are to downgrade to 18.06.1 or use host mode publishing (https://docs.docker.com/compose/compose-file/#long-syntax-1).

**Comment by schoeppe** [comment]
Do you have more information about this upstream issue?
Any link would be appreciated, thank you!

**Comment by tianon** [comment]
Well, good news, I've narrowed it down.  Bad news, Docker's `check-config.sh` script needs to be updated.

One of these is necessary (when added, I can create a service and `curl 127.0.0.1` successfully):

```diff
+CONFIG_IP_VS_IPV6=y
+CONFIG_IP_VS_PROTO_TCP=y
+CONFIG_IP_VS_PROTO_UDP=y
+CONFIG_IP_VS_PROTO_AH_ESP=y
+CONFIG_IP_VS_PROTO_ESP=y
+CONFIG_IP_VS_PROTO_AH=y
+CONFIG_IP_VS_PROTO_SCTP=y
```

For reference, here's my entire testing process: (which breaks on current `b2d.iso`, and works when adding all those, of which I'm sure we can narrow down to a smaller set)

```console
$ docker swarm init
$ docker service create -p 80:80 nginx:alpine
$ curl -vvv 127.0.0.1
```

**Comment by tianon** [comment]
Narrowed down even further:
```diff
+CONFIG_IP_VS_PROTO_TCP=y
+CONFIG_IP_VS_PROTO_UDP=y
```

@thajeztah any idea why `check-config.sh` doesn't check for these?  Are these all that are necessary, or might Docker use more of these protos?  Maybe someone else we should ping? :innocent:

**Comment by supermanHub** [comment]
@schoeppe 

> Do you have more information about this upstream issue?
> Any link would be appreciated, thank you!

Sorry, i don't have enough time to get much more information about this upstream issue, i have some urgent to do at the moment. I will inspect it when I am free. ~_~

**Comment by tianon** [comment]
Just mirroring the salient bit of my comment from https://github.com/moby/moby/pull/38204#issuecomment-438725454:

> In the b2d issue, it turns out that "what changed" is the kernel config in b2d (much more minimal now), and it's still not totally working while passing `check-config.sh` with flying colors.

:sweat_smile: :heart:

**Comment by thaJeztah** [comment]
Thanks for clearing that up @tianon - so this has always been a requirement, just not checked in the check-config.sh 👍 🤗 ❤️

**Comment by tianon** [comment]
New PR here open at https://github.com/boot2docker/boot2docker/pull/1353 -- will wait for https://github.com/moby/moby/pull/38204 before merging though (especially in case there are others we need to add :heart:).

**Comment by tianon** [comment]
Ok, this might not actually be a full solution -- I think there's more missing.  If I switch my example above to be `-p 8080:80` instead of `-p 80:80` (and adjust `curl` to use `:8080` accordingly), it still fails. :sweat:

**Comment by alexivkin** [comment]
Actually it has to do with the boot2docker missing the REDIRECT module in the kernel.
So the check needs to be done for `CONFIG_IP_NF_TARGET_REDIRECT=m`
I found the same "No chain/target/match by that name" error in the swarm on docker-machines with the latest boot2docker

**Comment by tianon** [comment]
See https://github.com/boot2docker/boot2docker/releases/tag/v18.09.1-beta1 and https://github.com/boot2docker/boot2docker/releases/tag/v18.09.1-beta2 (which include this fix). :+1:

**Comment by wuyuchang** [comment]
I download the latest [boot2docker.iso](https://github.com/boot2docker/boot2docker/releases/download/v18.09.1-rc1/boot2docker.iso) which is the latest version of the boot2docker right the moment.
And I do `docker swarm init --advertise-addr 192.168.99.100 && docker stack deploy -c docker-compose.yml firstlab` again, then access "192.168.99.100" via the chrome. It's work right now.

**Comment by supermanHub** [comment]
Good news. Thanks for your confirmation.
I believe we can close the issue now.
