### ISSUE TITLE
Enable FUSE module

### ISSUE THREAD

**Issue by VasilRomanovich** [boot2docker/boot2docker#1352]
Hi,

It looks like with the latest release v18.09.0 the fuse kernel module is no longer compiled. Fuse was available in the previous release.

Do you plan on enabling it again?

Thanks

**Comment by tianon** [comment]
This got added back in https://github.com/boot2docker/boot2docker/pull/1350. :+1:

**Comment by tianon** [comment]
See https://github.com/boot2docker/boot2docker/releases/tag/v18.09.1-beta1 and https://github.com/boot2docker/boot2docker/releases/tag/v18.09.1-beta2 (which include this fix). :+1:
