### ISSUE TITLE
upgrade from 18.06.1-ce to v18.09.0

### ISSUE THREAD

**Issue by Yackip** [boot2docker/boot2docker#1356]
Hey I have a question regarding the the update from 18.06.1-ce to v18.09.0
Until this release I could just swap out the old iso file and replace it with the new one - happy days.
But the newest release throws an error ( [This Error ](https://github.com/boot2docker/boot2docker/blob/a35a28719c22cf09c844d12d82f6002aa7f72d4d/files/init.d/autoformat#L183))
How can I fix that ? Thank's for the awesome work ! :)

**Comment by tianon** [comment]
That's really odd -- it should be fully compatible.  Any additional details you can provide?

**Comment by sven-carstens** [comment]
I managed to swap it out but had to change /var/lib/boot2docker/profile the overlay filesystem from aufs to overlay2.

**Comment by tianon** [comment]
Ah right, yes -- if you were using AUFS previously, it's now deprecated.  See https://github.com/boot2docker/boot2docker/releases/tag/v18.09.0, specifically:

> **Warning:** the AUFS storage driver is deprecated in boot2docker and AUFS support is removed in 18.09+. You can continue with AUFS in boot2docker 18.06.x, but it is recommended to reset your disk image before updating to 18.09+.
> 
> **See https://github.com/boot2docker/boot2docker/issues/1326 for more discussion.**

Closing since this appears to be resolved. :+1:
