### ISSUE TITLE
USB serial device not working since v18.09

### ISSUE THREAD

**Issue by StefanD986** [boot2docker/boot2docker#1361]
Since v18.09 the USB device sharing for serial devices is not working anymore (which for me is **the reason** to use docker-machine). 

I am not sure what the cause for this is, but to me it looks like either 
 a. USB serial device support is deactivated in the kernel?
 b. kernel modules are not installed by default

Its hard for me to debug any further because as described in #1360 I cannot install any programs that could help me digging deeper.

### Steps to reproduce
0. Create VM with latest boot2docker image: `$ docker-machine create --driver virtualbox default` 
1. Stop VM `$ docker-machine stop`
2. Enable USB support in the boot2docker VM settings, and add filter for USB serial adapter (For reproducing the bug a USB serial adapter is required on the VM Host machine)
3. Start VM `$ docker-machine start`
4. log in to boot2docker VM: `$ docker-machine ssh`
5. First thing to notice that something is broken is that the *usual* device symlink for the USB serial adapter does not exist:
   ```
   docker@default:~$ ls -l /dev/ttyUSB*
   ls: /dev/ttyUSB*: No such file or directory
   ```
6. Listing the usb devices in `/dev/bus/usb/001/` shows that the USB device was enumerated 

### Expected behavior
Following the same steps as above on v18.06 shows the expected behavior:

0. Create VM with boot2docker v18.06: `$ docker-machine create --driver virtualbox --virtualbox-boot2docker-url https://github.com/boot2docker/boot2docker/releases/download/v18.06.1-ce/boot2docker.iso default1806`
1. Stop VM: `docker-machine stop default1806`
2. Enable USB support in the boot2docker VM settings, and add filter for USB serial adapter (For reproducing the bug a USB serial adapter is required on the VM Host machine)
3. Start VM `$ docker-machine start default1806`
4. log in to boot2docker VM: `$ docker-machine ssh default1806`
5. Here the device symlink exists under `/dev/ttyUSB0`:
   ```
   docker@default1806:~$ ls -l /dev/ttyUSB0
   crw-rw----    1 root     staff     188,   0 Nov 25 22:04 /dev/ttyUSB0
   ```
6. (Looking into the the bus/usb subsystem is not here needed as the symlink already shows that the device was found and enumerated)
7. getting the Options for the tty device via stty is successful:
   ```
   docker@default1806:~$ stty -F /dev/ttyUSB0
   speed 9600 baud; line = 0;
   intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; flush = ^O;
   min = 1; time = 0;
   -brkint -imaxbel
   ```

### System info

Operating System: OSX Mojave 10.14.1

```
$ docker --version
Docker version 18.09.0, build 4d60db4

$ docker-machine --version
docker-machine version 0.16.0, build 702c267f
```

**Comment by tianon** [comment]
See https://github.com/boot2docker/boot2docker/releases/tag/v18.09.1-beta1 and https://github.com/boot2docker/boot2docker/releases/tag/v18.09.1-beta2 (which include this fix). :+1:

**Comment by sheezyontrack** [comment]
I am experiencing similar issues, however I have noticed additional issues. When I plug a USB device to the machine and map/add it to the Docker machine using the filter, I start the docker-machine up successfully but I can't list the attached serial devices similar to the issue with @StefanD986 .   In addition to this, when I unplug the device  and run the command `$ docker-machine status`  on another terminal, it says 

> Running

 but if I plug the USB device back to the system and repeat the  command `$ docker-machine status` command. I get the message 

> error getting state for host default: signal: segmentation fault.

Moreover, when I use a USBasp (USB to UART serial interface module adaptor) the situation is completely different.  It's either that:-

(a)The docker-machine gets stucked at 
 > Waiting for an IP... 

or it diisplays 

> Waiting for an IP...
> Maximum number of retries (5) exceeded

I have tried both the _Serial_ _Ports_ and the _USB_ options for mapping the USB to UART on the VirtualBox for this and they both have similar issues

System Info: Operating System: OSX Mojave 10.14.3
`$  docker --version`
Docker version 18.09.3, build 774a1f4

`$  docker-machine --version`
docker-machine version 0.16.1, build cce350d7

**Comment by pklapperich** [comment]
@sheezyontrack That's different set of symptoms and should go in its own issue. But as long as we're here... The original issue was about problems inside the VM (unable to see usb devices). You're experiencing segfaults on the host machine

I think you'll notice that if you unplug the USB device docker-machine will work normally and when you plug it back in, docker-machine starts giving segment fault for commands like `docker-machine ssh` and `docker-machine ip`. But if you ssh in you can THEN plug in the usb device and use your existing ssh connection and can see the usb device is recognized inside the VM.

FWIW, I was experiencing it on one MBP (running VirtualBox 6.0.4) but not on another (running VirtualBox 6.0.8). After upgrading to VirtualBox 6.1 the problem went away.
