### ISSUE TITLE
Hit ip forwarding problem from macOS to container in v18.09.0 while v18.06.1-ce works well

### ISSUE THREAD

**Issue by bearzyj** [boot2docker/boot2docker#1364]
**1 Environment Description**
`Operation System `: macOS majove version 10.14.1
`Docker created by`: "docker-machine" and "docker" CLI, **NOT** "docker for Mac" app.

**2 Reproducing steps in v18.09.0**
1) Create a docker machine "tryIt", command is:
    `docker-machine create tryIt --virtualbox-cpu-count "2" --virtualbox-memory "4096" --virtualbox-disk-size "100000"`
     In this step, hit problem #1347, just workaround it. And successfully created.

2) Create a common ubuntu container, now the situation is:
     macOS------vboxnet1------192.168.99.1
     tryIt---------docker0-------172.17.0.1
     tryIt---------eth1-----------192.168.99.100
     container----eth0----------172.17.0.2

3) Try to ping container(172.17.0.2) from macOS(192.168.99.1) with adding a route
     Failed here in v18.09.0
     Ping successfully in v18.06.1-ce with exactly the same above steps
     
**3 Other information**
With command `cat /etc/issue`, found that:
v18.06.1-ce is based on "Core Linux"
v18.09.0 is based on "TinyCoreLinux 8.2.1"

**Comment by tianon** [comment]
I'm not totally sure why this didn't exhibit sooner, but this appears to have been changed in https://github.com/moby/moby/pull/28257 (back in 2016), and is only now actually exhibiting in boot2docker for some reason: (this is comparing `iptables` from 18.06 to 18.09)

```diff
...
-Chain FORWARD (policy ACCEPT 3 packets, 232 bytes)
+Chain FORWARD (policy DROP 11 packets, 744 bytes)
...
```

Full `iptables` diff:

```diff
--- iptables-18.06.txt	2018-11-28 13:35:31.000000000 -0800
+++ iptables-18.09.txt	2018-11-28 13:39:03.000000000 -0800
@@ -1,16 +1,16 @@
-Chain INPUT (policy ACCEPT 2233 packets, 5158K bytes)
+Chain INPUT (policy ACCEPT 1721 packets, 5130K bytes)
  pkts bytes target     prot opt in     out     source               destination         
 
-Chain FORWARD (policy ACCEPT 3 packets, 232 bytes)
+Chain FORWARD (policy DROP 11 packets, 744 bytes)
  pkts bytes target     prot opt in     out     source               destination         
-   20  1361 DOCKER-USER  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
-   20  1361 DOCKER-ISOLATION-STAGE-1  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
-    8   515 ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
-    3   232 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0           
-    9   614 ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0           
+   11   744 DOCKER-USER  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
+   11   744 DOCKER-ISOLATION-STAGE-1  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
+    0     0 ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
+   11   744 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0           
+    0     0 ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0           
     0     0 ACCEPT     all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0           
 
-Chain OUTPUT (policy ACCEPT 1396 packets, 130K bytes)
+Chain OUTPUT (policy ACCEPT 915 packets, 98123 bytes)
  pkts bytes target     prot opt in     out     source               destination         
 
 Chain DOCKER (1 references)
@@ -18,29 +18,29 @@
 
 Chain DOCKER-ISOLATION-STAGE-1 (1 references)
  pkts bytes target     prot opt in     out     source               destination         
-    9   614 DOCKER-ISOLATION-STAGE-2  all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0           
-   20  1361 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           
+    0     0 DOCKER-ISOLATION-STAGE-2  all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0           
+   11   744 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           
 
 Chain DOCKER-ISOLATION-STAGE-2 (1 references)
  pkts bytes target     prot opt in     out     source               destination         
     0     0 DROP       all  --  *      docker0  0.0.0.0/0            0.0.0.0/0           
-    9   614 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           
+    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           
 
 Chain DOCKER-USER (1 references)
  pkts bytes target     prot opt in     out     source               destination         
-   20  1361 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           
-Chain PREROUTING (policy ACCEPT 15 packets, 880 bytes)
+   11   744 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           
+Chain PREROUTING (policy ACCEPT 20 packets, 1240 bytes)
  pkts bytes target     prot opt in     out     source               destination         
-   12   648 DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
+    9   496 DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
 
-Chain INPUT (policy ACCEPT 12 packets, 648 bytes)
+Chain INPUT (policy ACCEPT 9 packets, 496 bytes)
  pkts bytes target     prot opt in     out     source               destination         
 
-Chain OUTPUT (policy ACCEPT 64 packets, 4584 bytes)
+Chain OUTPUT (policy ACCEPT 32 packets, 2132 bytes)
  pkts bytes target     prot opt in     out     source               destination         
     0     0 DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL
 
-Chain POSTROUTING (policy ACCEPT 67 packets, 4816 bytes)
+Chain POSTROUTING (policy ACCEPT 32 packets, 2132 bytes)
  pkts bytes target     prot opt in     out     source               destination         
     0     0 MASQUERADE  all  --  *      !docker0  172.17.0.0/16        0.0.0.0/0           
 
```

**Comment by tianon** [comment]
You should be able to "fix" this for your use case by enabling `ip_forward` explicitly before Docker starts via `/var/lib/boot2docker/profile`.

As for why this is exhibiting now and hasn't previously, the old boot2docker had https://github.com/boot2docker/boot2docker/commit/c2b60ab21080d15148948fc6536078251dcfa842#diff-5d40f3f9d874ac036eafd3052a2a1d31 in `/etc/sysctl.conf`, applied at boot, which is a really bizarre ancient relic from before Docker applying those necessary bits automatically (and in a much more secure-by-default way):

```ini
net.ipv4.ip_forward=1
net.ipv6.conf.all.forwarding=1
```

So, I'm sorry that this broke your workflow, but the workaround should be relatively simple (`sysctl net.ipv4.ip_forward=1` in `/var/lib/boot2docker/profile`) and this is honestly a bad enough security issue that it's tempting to go backwards and remove all old boot2docker ISOs (but I don't honestly think that would really fix anything -- folks would simply complain they're gone). :scream:

(Yet another reason why we so strongly discourage use of boot2docker in any sort of production environment. :disappointed:)

**Comment by bearzyj** [comment]
Thanks @tianon 

Actually, without any change, value of  `net.ipv4.ip_forward` is already 1 by default in [v18.09.0](https://github.com/boot2docker/boot2docker/releases/tag/v18.09.0).

The crux is about the changes of iptables you mentioned. 
Check "sudo iptables  -L" in v18.09.0, it shows `Chain FORWARD (policy DROP)`

After executing `sudo iptables -P FORWARD ACCEPT`, I can ping the container from macOS.

**Comment by tianon** [comment]
Yep, that's as expected; go re-read through
https://github.com/moby/moby/pull/28257. 👍

**Comment by bearzyj** [comment]
@tianon 
May I ask one more question that:  how to configure `sudo iptables -P FORWARD ACCEPT` into the virtual machine (here is "tryIt") ?

After trying, found files like: `~/.bashrc`, `./.profile`, `/usr/local/etc/bashrc`, `/etc/profile` will be restored after restart virtual machine. (Watched bootup log and get the idea why this happened)

`/var/lib/boot2docker/profile` will not be restored, but it doesn't run command during bootup.

So, is there any convenient method to allow a user to add a command running during bootup ?

Thanks in advance.
