### ISSUE TITLE
Long boot time on VirtualBox with Docker-Toolbox

### ISSUE THREAD

**Issue by TeeJayD** [boot2docker/boot2docker#1366]
I'm having issues with long boot times while using the latest boot2docker version with Docker-Toolbox.
It is a corporate environment where it blocks dns queries besides our own local dns server, and i've noticed that the ntp server always sends dns queries towards 8.8.8.8, 1.1.1.1 and 1.0.0.1, stalling the boot for at least two minutes. It takes so much time that the "Waiting for IP" step fails.
Is there any way of changing this behaviour? I've tried creating a VM with --engine-opts dns=OUR_DNS and it didn't work.

Verifying the traffic i've noticed it ignores the DNS setting and keeps trying to resolve through Google/Cloudflare.
```
192.168.40.17	1.0.0.1	DNS	86	Standard query 0xc0a0 A 0.boot2docker.pool.ntp.org
192.168.40.17	1.0.0.1	DNS	86	Standard query 0xc0a0 A 0.boot2docker.pool.ntp.org
192.168.40.17	8.8.8.8	DNS	86	Standard query 0xc0a0 A 0.boot2docker.pool.ntp.org
192.168.40.17	8.8.8.8	DNS	86	Standard query 0xc0a0 A 0.boot2docker.pool.ntp.org
```
Edit:
With some further testing, i've noticed it only happens during boot. If i try to do any dns queries using nslookup after it finally boots, it uses the correct DNS server.

**Comment by tianon** [comment]
See https://github.com/boot2docker/boot2docker/pull/1367, which should help with this somewhat.

**Comment by TeeJayD** [comment]
The latest beta with #1367 applied fixes the issue.

**Comment by yosifkit** [comment]
@TeeJayD, Thanks for confirming!
