### ISSUE TITLE
Hard drive is not detected running on VMware ESXi since v18.09

### ISSUE THREAD

**Issue by frol** [boot2docker/boot2docker#1368]
It seems to be related to https://github.com/boot2docker/boot2docker/issues/1361#issuecomment-441785072

It might be solved with #1370.

**Comment by tianon** [comment]
Heh, https://github.com/boot2docker/boot2docker/issues/1369 was a duplicate of this one, resolved by https://github.com/boot2docker/boot2docker/pull/1370. :+1:
