### ISSUE TITLE
Release/Download URL changed?

### ISSUE THREAD

**Issue by febbraro** [boot2docker/boot2docker#1371]
As recently as 18.6.1 the release (and thus the download URL) had the `-ce` in it.  This corresponds to the version string returned from `docker --version` and `docker version`.

However for v18.9.0 the release (and download) no longer has the `-ce` in it.  I discovered this when our tool, Outrigger, composes a URL directly from the docker version to download the corresponding boot2docker version and it has recently broken.

I was wondering if this was an oversight in creating the release? or was this deliberate and a new naming convention for all boot2docker URLs moving forward?

Thanks.

**Comment by thaJeztah** [comment]
See https://github.com/docker/docker-ce/releases/tag/v18.09.0

> Remove -ce / -ee suffix from version string docker-ce-packaging#206

**Comment by tianon** [comment]
Yep this was intentional (thanks for snagging the appropriate link for us, @thajeztah ❤️❤️).

We follow Docker's version numbers, so when they added this suffix, we did also, and now that they've removed it, we have also. 👍

**Comment by febbraro** [comment]
Thanks for the explanation, however it doesn't look like actually removed it..

```
~/Projects/
➜ docker --version
Docker version 18.09.0-ce, build 4d60db4

~/Projects/
➜ docker version
Client:
 Version:           18.09.0-ce
 API version:       1.38 (downgraded from 1.39)
 Go version:        go1.11.2
 Git commit:        4d60db4
 Built:             unknown-buildtime
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:28:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

Not your problem, but thought I'd point it out. Thanks for getting back to me (and sorry I did not see it in the changelog)

**Comment by febbraro** [comment]
I was running the Docker formula installed from Homebrew, not Docker for Mac

**Comment by thaJeztah** [comment]
Ah, I suspect they may have to update their scripts if they build from source

**Comment by thaJeztah** [comment]
Opened https://github.com/Homebrew/homebrew-core/pull/35012
