### ISSUE TITLE
oracle vm box; no access to SAS  Storage Devices since boot2docker >= 18.09

### ISSUE THREAD

**Issue by AnselmD** [boot2docker/boot2docker#1375]
With boot2docker 18.06 I can access SAS Storage devices defined in Oracle VM BOX.
This is not possible with boot2docker >= 18.09

Is there a way to change this?

**Comment by AnselmD** [comment]
Thank you for your help, @tianon 

I have trouble with this in a given environment. I try to breakdown the problem to a hand made example. 
I am running this example in a boot2docker 18.06.01 and a 18.09.01 environment with dockertoolbox.exe and will describe the differences:
Screenshot of the Oracle VM Virtual Box Manager: SAS Controller with a 8 GB Disk:
![2019-01-17 16_52_43-default - settings](https://user-images.githubusercontent.com/6770907/51330813-946bc800-1a78-11e9-8096-1045ce42f84f.png)

![2019-01-17 17_09_05-default - settings](https://user-images.githubusercontent.com/6770907/51332245-aa2ebc80-1a7b-11e9-91cf-7f119c263088.png)



In the following screenshot i am using `fdisk -l ` to list all known disks. As you can see, /dev/sdb is known, but at the moment does not have a partition. this is okay.
![2019-01-17 16_58_14-default running - oracle vm virtualbox](https://user-images.githubusercontent.com/6770907/51331166-62a73100-1a79-11e9-90ba-35ea29d0a60f.png)

Now i exchanged the boot2docker image to 18.09.01, as you can see `fdisk -l` does not list the SAS drive:
![2019-01-17 17_05_16-default running - oracle vm virtualbox](https://user-images.githubusercontent.com/6770907/51331713-9afb3f00-1a7a-11e9-925c-fac7bda20608.png)

And now using parted with `print devices`:
![2019-01-17 17_13_19-default running - oracle vm virtualbox](https://user-images.githubusercontent.com/6770907/51332113-62a83080-1a7b-11e9-8cd2-ef452090899e.png)

Is this the information you expected?

**Comment by tianon** [comment]
Ah, that's really, really helpful, thanks!

Any chance I could get the output of both `lsmod` and `docker run -it --rm alpine:3.8 lspci -k` in the 18.06 VM? :pray:

(This will help me figure out exactly which kernel module it's using / needs so I can include it in the next release. :+1:)

**Comment by AnselmD** [comment]
2nd result, docker run -it --rm alpine:3.8 lspci -k:
```
00:00.0 Class 0600: 8086:1237
00:03.0 Class 0200: 8086:100e e1000
00:02.0 Class 0300: 80ee:beef
00:05.0 Class 0401: 8086:2415
00:08.0 Class 0200: 8086:100e e1000
00:0d.0 Class 0106: 8086:2829 ahci
00:01.0 Class 0601: 8086:7000
00:04.0 Class 0880: 80ee:cafe vboxguest
00:16.0 Class 0100: 1000:0054 mptsas
00:07.0 Class 0680: 8086:7113 piix4_smbus

```

Thank you! :-) :smiley:
