### ISSUE TITLE
Why can't show the "whale" when the boot2docker.iso start

### ISSUE THREAD

**Issue by unihon** [boot2docker/boot2docker#1378]
- boot2docker v18.09.2
- Virtualbox 6

---

The screen is like follwing picture when I start boot2docker.iso on the VBox6.

![aa](https://user-images.githubusercontent.com/42078581/52850366-40730280-314e-11e9-9182-f71ccd711ed1.png)

But I found an example which will show the "whale" when the boot2docker start and login, like follwing picture.

![untitled](https://user-images.githubusercontent.com/42078581/52850711-1a9a2d80-314f-11e9-89f4-a44e47d81ec7.png)

Why?

**Comment by tianon** [comment]
When we refactored how the ISO gets built to improve the long-term maintainability, preserving cosmetic details like this whale wasn't a high priority.

I agree that the whale was cute, but I'm still inclined to not add the maintenance of bringing it back unless there's a good concrete problem not having it causes? (Besides nostalgia 😅)

**Comment by unihon** [comment]
> When we refactored how the ISO gets built to improve the long-term maintainability, preserving cosmetic details like this whale wasn't a high priority.
> 
> I agree that the whale was cute, but I'm still inclined to not add the maintenance of bringing it back unless there's a good concrete problem not having it causes? (Besides nostalgia 😅)

Oh,This means that the "whale" has been removed in the new version. I have thought about it before, but I am not sure. (I think that the "b2d" without the "whale" is soulless.🤣)

Thank you！😄
