### ISSUE TITLE
`filetool.sh -b` exit status 1

### ISSUE THREAD

**Issue by cpu100** [boot2docker/boot2docker#1380]
`filetool.sh -b /dev/sda1`  is work, but it seem `filetool.sh -r` failed at boot.
`filetool.sh -r /dev/sda1` should work, arg `/dev/sda1` is missing when boot.

**Comment by tianon** [comment]
This is the first I've ever heard of `filetool.sh`, so I'm frankly
unsurprised it doesn't work, and have no plans to support it.

**Comment by hiobama** [comment]
I want to add my ssh key to `authorized_keys`, but it restore after reboot. How ?

**Comment by hiobama** [comment]
I want to add my ssh key to `authorized_keys`, but the changes restore after reboot.
What's the right way? @tianon

**Comment by hiobama** [comment]
> This is the first I've ever heard of `filetool.sh`, so I'm frankly unsurprised it doesn't work, and have no plans to support it.

`filetool.sh` is a tool from tinycore, No plan is needed to support it, but some boot options are missing.

**Comment by hiobama** [comment]
https://github.com/boot2docker/boot2docker/blob/8bf3daa2bd19b84a5908218f423c8a790bb46ad5/files/isolinux.cfg#L14

you guys disable `/etc/init.d/tc-restore.sh` by `norestore` added and bring in  `/mnt/sda1/var/lib/boot2docker/userdata.tar` , this is repetitive work.

@tianon

**Comment by hiobama** [comment]
https://github.com/boot2docker/boot2docker/pull/1381/files

**Comment by tianon** [comment]
I'd recommend doing some research into what userdata.tar is, where it comes
from, and why we do that insanity before blindly discarding it as duplicate
effort. 😉

(It's neat that tiny core has "restore" functionality, but that's not what
userdata.tar is for.)

**Comment by hiobama** [comment]
I use `restore=sda1/tce` myselft for a while, it works great.

**Comment by tianon** [comment]
Closing given https://github.com/boot2docker/boot2docker/pull/1381#issuecomment-465991073 and the documented workarounds for folks that want to do this.
