### ISSUE TITLE
lack of entropy

### ISSUE THREAD

**Issue by zhangyoufu** [boot2docker/boot2docker#1392]
after boot finished
```
$ docker info
crypto/rand: blocked for 60 seconds waiting to read random data from the kernel
```

I tried to add a virtio-rng device like this
```
    <rng model='virtio'>
      <rate bytes='1024' period='2000'/>
      <backend model='random'>/dev/random</backend>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x08' function='0x0'/>
    </rng>
```
but
```
$ cat /sys/devices/virtual/misc/hw_random/rng_current
none
$ cat /sys/devices/virtual/misc/hw_random/rng_available

```

I configured CPUID like this and I'm pretty sure it has rdrand feature flag
```
  <cpu mode='host-model' check='partial'>
    <model fallback='allow'/>
  </cpu>
```
but `/proc/sys/kernel/random/entropy_avail` is still increasing very slowly at ~3/second.

If I intentionally disable rdrand like this
```
  <cpu mode='host-model' check='partial'>
    <model fallback='allow'/>
    <feature policy='disable' name='rdrand'/>
  </cpu>
```
I have haveged and a lot of entropy.

**Comment by tianon** [comment]
We do include `haveged` inside the ISO for generating entropy, but we try to be very conservative in when we'll start it, especially given that it could have unintended impacts on the users of the system:

https://github.com/boot2docker/boot2docker/blob/e61c69392a4a145f299bc3fd76e1c70c446a4384/files/init.d/haveged#L53-L73

**Comment by zhangyoufu** [comment]
Yes, I understand and agree with the behavior of `boot2docker/files/init.d/haveged`. I just wonder why virtio-rng & rdrand cannot provide enough entropy in my setup. Is this a configuration problem on my side? Or we need to enable some kernel config or include some extra kmods?

**Comment by zhangyoufu** [comment]
@tianon I think `kernel/drivers/char/hw_random/virtio-rng.ko` should be included in boot2docker.

**Comment by zhangyoufu** [comment]
`RANDOM_TRUST_CPU` is also not not set in boot2docker and defaults to `n` which renders rdrand useless.

**Comment by tianon** [comment]
Definitely agree on the `virtio` RNG driver, although we're still on Linux 4.14 and `CONFIG_RANDOM_TRUST_CPU` wasn't introduced until 4.19+ so that shouldn't be relevant.

**Comment by zhangyoufu** [comment]
Thanks. virtio-rng now works out-of-box.
