### ISSUE TITLE
after update boot2docker.iso,my data lost

### ISSUE THREAD

**Issue by hhymyi** [boot2docker/boot2docker#1393]
hi,
win7 os,run Docker Quickstart Terminal,then auto-update
![1](https://user-images.githubusercontent.com/25222094/59579156-1af70500-90fe-11e9-8e15-d327ccfdbd65.jpg)
when compelete,my cotainer is missing
![3](https://user-images.githubusercontent.com/25222094/59579162-24806d00-90fe-11e9-8d31-d6610242cd57.png)
![2](https://user-images.githubusercontent.com/25222094/59579169-2c401180-90fe-11e9-9482-ccb42bbb8702.jpg)

look forward to your answer

**Comment by tianon** [comment]
My guess is AUFS, see the note at the top of the release notes: https://github.com/boot2docker/boot2docker/releases/tag/v18.09.6

**Comment by hhymyi** [comment]
move this file to other place,can it work?
when next time auto-update boot2docker.iso,can i keep my data?
![TIM图片20190617142839](https://user-images.githubusercontent.com/25222094/59582943-61536080-910c-11e9-9612-2d4457514a09.png)

**Comment by tianon** [comment]
If you move off AUFS to overlay, yes.

**Comment by hhymyi** [comment]
but use "docker info",it show i'm using overlay2 storage driver
![1](https://user-images.githubusercontent.com/25222094/59646468-b09b9e80-91a9-11e9-8a8b-f51d556fb7de.png)

**Comment by tianon** [comment]
Yep, then you should be good.

**Comment by tianon** [comment]
Closing given this appears to be the known AUFS deprecation.

**Comment by hhymyi** [comment]
@tianon thank you!
![1](https://user-images.githubusercontent.com/25222094/59647119-9ca56c00-91ac-11e9-90b5-0f6009eeecd7.gif)
