### ISSUE TITLE
boot2docker 19.03 image does not automount Users directory w/ Virtualbox 5.x

### ISSUE THREAD

**Issue by abelcheung** [boot2docker/boot2docker#1398]
The symptom is the same as #1395 , where user directory is not mounted after booting the image. However the underlying cause is not the same.

#1395 indicates a change of `VBoxControl` automount option, but for this issue, no automount option is involved, and I'm using Docker Toolbox + Virtualbox 5.2.26 under Windows 7.

### Reproduction steps
1. `docker-machine start default`
2. `ssh` into the boot2docker VM
3. `sudo` and obtain root privilege
4. `VBoxControl --nologo sharedfolder list`

### Error output
```
root@default:~# VBoxControl --nologo sharedfolder list
Shared Folder mappings (2):

VBoxControl: error: Error while getting the shared folder name for root node = 0, rc = VERR_NOT_IMPLEMENTED
VBoxControl: error: Error while getting the shared folder name for root node = 1, rc = VERR_NOT_IMPLEMENTED
```

I'm aware of recent change in #1396, so removed the `--automount` option to emphasize it's unrelated.

https://github.com/boot2docker/boot2docker/commit/b5def189c5a5b577387090671651f5dee9576fde#diff-143faf222471f00b186177a1a20ebe0b

Besides, there are 2 combinations where such error would be resolved:
1. Downgrade boot2docker.iso to 18.09, and use it with Virtualbox 5.2.26
2. Keep boot2docker.iso 19.03, and upgrade Virtualbox to 6.0.10 (haven't tested earlier 6.0.x versions)

Is this desired behavior? If yes, is there any need to really stress (and document the situation) that boot2docker.iso and Virtualbox versions must match?

**Comment by abelcheung** [comment]
BTW, I have added extra shared folder to this default VM using Virtualbox GUI, so there are 2 shared folder entries. With default setting there should only be one.

**Comment by Ajedi32** [comment]
I suspect I am experiencing a symptom of this problem: I'm no longer able to mount Docker volumes on Windows when running Docker via docker-machine, unless I explicitly specify `--virtualbox-boot2docker-url https://github.com/boot2docker/boot2docker/releases/download/v18.09.8/boot2docker.iso` when creating the VM.

I too am running VirtualBox 5.2.

**Comment by tianon** [comment]
Gah, we've previously had really good success with older versions of VirtualBox still being compatible with the newer version of the guest additions. :disappointed:

**Comment by Nuru** [comment]
I confirmed that the `guest additions` version was the issue by rebuilding `boot2docker` version 19.03.1 with guest additions version 5.2.32 and that fixed the problem. The file is too big to attach to this comment or I would. If someone has a place to host the file, I will upload it, but it would be better if the owners of this repo did the alternate build and included it as a release artifact. 

If you want to build it yourself, it's a simple change to the Dockerfile, but be warned that the build took over 2 hours on my not-too-shabby workstation. 
```
diff --git a/Dockerfile b/Dockerfile
index 2513694..b20160a 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -355,9 +355,11 @@ RUN ( cd /usr/src/haveged && ./configure LDFLAGS='-static --static' ); \
 
 # http://download.virtualbox.org/virtualbox/
 # updated via "update.sh"
-ENV VBOX_VERSION 6.0.10
+# ENV VBOX_VERSION 6.0.10
+ENV VBOX_VERSION 5.2.32
 # https://www.virtualbox.org/download/hashes/$VBOX_VERSION/SHA256SUMS
-ENV VBOX_SHA256 c8a686f8c7ad9ca8375961ab19815cec6b1f0d2496900a356a38ce86fe8a1325
+#ENV VBOX_SHA256 c8a686f8c7ad9ca8375961ab19815cec6b1f0d2496900a356a38ce86fe8a1325
+ENV VBOX_SHA256 4311c7408a3410e6a33264a9062347d9eec04f58339a49f0a60488c0cabc8996
 # (VBoxGuestAdditions_X.Y.Z.iso SHA256, for verification)
 
 RUN wget -O /vbox.iso "https://download.virtualbox.org/virtualbox/$VBOX_VERSION/VBoxGuestAdditions_$VBOX_VERSION.iso"; \
```

**Comment by Ajedi32** [comment]
So if the guest additions version is the problem, what's the best way to fix this? Should there be two ISOs in the next release, one with VirtualBox 5.2 guest additions, and one with VirtualBox 6.0 guest additions?

**Comment by Nuru** [comment]
> So if the guest additions version is the problem, what's the best way to fix this? Should there be two ISOs in the next release, one with VirtualBox 5.2 guest additions, and one with VirtualBox 6.0 guest additions?

I think so. It would also be nice to have a version with `open-vm-tools` version 10.1.5, so that I can use VMware Fusion 8.5 (the last version that runs on El Capitan).

**Comment by tianon** [comment]
If we can verify that the VirtualBox 5.x guest additions still work fine on 6.x, I think we should just revert to that and stick with 5.x until there's a compelling reason not to (like them not working on a newer version or a newer version committing to still support older versions).

Regarding `open-vm-tools`, I guess the same applies -- it seems weird to me that they'd remove support for older hypervisors in newer tools, but I suppose there's a maintenance burden either way no matter what.

So consider this an official call for help to verify that 5.x guest additions work on VirtualBox 6.x (easiest way to test likely being running https://github.com/boot2docker/boot2docker/releases/tag/v18.09.8 on newer VirtualBox and verifying the automount works).

@Nuru does our 18.09 release work on Fusion 8.5?  (It's on `open-vm-tools` 10.2.x, so it'd be more reasonable to not have to go all the way back to 10.1 IMO for that to be reasonable to consider.)

**Comment by Nuru** [comment]
@tianon No, 18.09.9 does not work on Fusion 8.5. Fusion 8.5 stopped at VMware Tools 10.1.6. I tried to build a version of 19.03 that used `open-vm-tools` 10.1.5 but I could not get that to work either. I am not confident that I built it correctly, though, so don't take my failure as definitive. 

I tried using `docker-machine` version 0.16.1 to create a machine with `boot2docker.iso` from [v18.06.0-ce-rc1](https://github.com/boot2docker/boot2docker/releases/tag/v18.06.0-ce-rc1) (which has open-vm-tools v10.0.0-3000743) and that didn't work either, so I guess don't bother with the support for Fusion 8.5. 

For the record, by "didn't work" I mean the `docker-machine create` fails at the point where it tries to enable file sharing (`vmrun enableSharedFolders`), even if you set `--vmwarefusion-no-share`. I was able to use v18.06.0-ce-rc1 anyway, but I could not mount any directories from the host file system, which is critical for my work, so it's of no use to me.

**Comment by abelcheung** [comment]
> So consider this an official call for help to verify that 5.x guest additions work on VirtualBox 6.x (easiest way to test likely being running https://github.com/boot2docker/boot2docker/releases/tag/v18.09.8 on newer VirtualBox and verifying the automount works).

One :+1: from me, using VirtualBox 6.0.10. `mount` shows shared folder correctly, and there's no problem with read / write access. New VM created with:

`docker-machine.exe create --virtualbox-boot2docker-url https://github.com/boot2docker/boot2docker/releases/download/v18.09.8/boot2docker.iso`

**Comment by tianon** [comment]
Awesome, thank you!  Some testing on https://github.com/boot2docker/boot2docker/pull/1401 would be appreciated! :smile: :+1:

> Test ISO: https://gist.github.com/tianon/829be6a16ade16f9b39be491bc13d0e3
> 
> Direct link: https://gist.github.com/tianon/829be6a16ade16f9b39be491bc13d0e3/raw/cbd58731532c04f6683733442a0eae5cc91f957d/boot2docker.iso

(Especially looking for both VBox 5.x and 6.x verification, if we can get it!)

**Comment by Nuru** [comment]
@tianon  #1401 passes the smoke test running under VirtualBox 5.2.32. Host directories mount as expected.  

I have been running my custom build (which has the same Dockerfile changes as #1401 but nothing else) for 2 days now without problem, using VirtualBox 5.2.32 on OS X 10.11.6

**Comment by tianon** [comment]
For the record, I backported #1401 to both 18.09.x and 19.03.x, so the following pre-releases both include VirtualBox Guest Additions v5.2.32:

- https://github.com/boot2docker/boot2docker/releases/tag/v18.09.9-beta1
- https://github.com/boot2docker/boot2docker/releases/tag/v19.03.2-beta1

**Comment by Nuru** [comment]
Thanks @tianon !
For the record, all of the 18.09 releases had VirtualBox Guest Additions v5.2.32 or earlier. it was only the 19.03.0 and 19.03.1 releases that had VirtualBox Guest Additions v6. (v6.0.10 to be exact).
