### ISSUE TITLE
Docker volume disappeared after a Windows restart

### ISSUE THREAD

**Issue by bgreatfit** [boot2docker/boot2docker#1411]
I lost all my volumes after a computer restart;
The image below shows the error I got after opened Virtual box:
![docker](https://user-images.githubusercontent.com/10434677/88132212-d0846980-cbd6-11ea-9384-a67d4671ac61.JPG)

**Comment by tianon** [comment]
Unfortunately, the boot2docker project is officially deprecated (see https://github.com/boot2docker/boot2docker#deprecated, https://github.com/boot2docker/boot2docker/releases/tag/v19.03.12).
