### ISSUE TITLE
Unable to verify the Docker daemon is listening: Maximum number of retries (10) exceeded

### ISSUE THREAD

**Issue by czhb** [boot2docker/boot2docker#1412]
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Comment by tianon** [comment]
Unfortunately, the boot2docker project is officially deprecated (see https://github.com/boot2docker/boot2docker#deprecated, https://github.com/boot2docker/boot2docker/releases/tag/v19.03.12).
