### ISSUE TITLE
AMD CPUs

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [boot2docker/boot2docker#1413]
When running VirtualBox with boot2docker on AMD Ryzen CPUs (at least on MacOs) adding extra CPU cores to guest machine degrade performance. More core - less performance (especially when going to 8 and more cores). 
Issue described here: https://forums.virtualbox.org/viewtopic.php?f=7&t=93748
Upgrading/downgrading VirtualBox (6.x, 5.x) does not help. 
On other VMs in the the same VirtualBox environment i don's see this issue - only with boot2docker.
CPU: Ryzen 3900x.
quick test command in any linux container: 
```bash
sudo apt update
sudo apt install sysbench
sysbench --test=memory --num-threads=10 --max-time=10 run
```

**Comment by tianon** [comment]
Unfortunately, the boot2docker project is officially deprecated (see https://github.com/boot2docker/boot2docker#deprecated, https://github.com/boot2docker/boot2docker/releases/tag/v19.03.12).

**Comment by Vasiliy-Bondarenko** [comment]
Yes, i have seen it, but where is no other __viable__ way i can find to run docker on AMD hackintosh :( 
Docker desktop does not work because Apple virtualisation does not support AMD.
May be you can recommend something?..

**Comment by yosifkit** [comment]
Any broadly supported Linux distribution: Ubuntu, Debian, etc. And then install Docker.

**Comment by Vasiliy-Bondarenko** [comment]
@yosifkit, thanks for the tip.
i have done my homework before posting the issue :) i have tried. it's was not easy to say the least. 
i had to manually setup networks, directory mappings, reinstall docker, because it was not working after initial install for some reason, and in the end it started to work (and runs quite fast)... but volumes mappings failed to start even though i have started docker-compose directly from VM (no docker-machine attached from the host). and i gave up :( was not able to find solution.
