### ISSUE TITLE
Having /tmp as a symlink makes Dockerfile ADD fail with "Forbidden path outside the build context"

### ISSUE THREAD

**Issue by harleyk** [boot2docker/boot2docker#143]
Originally discussed in dotcloud/docker#3980.

It was discovered in the most recent versions of boot2docker that /tmp has been made into a symlink. When the context is uploaded for a build it is put into a random /tmp directory. Since /tmp is a symlink, when the ADD command runs, it gives the error "Forbidden path outside the build context" since the symlink confuses docker into believing it is following a symlink outside the build context.

This is probably actually a bug in docker to expand the symlink for the purposes of the build context but a workaround inside of boot2docker would probably help people for now too.

**Comment by panamantis** [comment]
Or use a mount instead of a ln  mount --bind olddir newdir
