### ISSUE TITLE
Attach failure

### ISSUE THREAD

**Issue by creack** [boot2docker/boot2docker#150]
`docker attach` does not work as expected when used with boot2docker. See dotcloud/docker#3693.
However, it works fine with a 'regular' distro.

**Comment by joallard** [comment]
Current version (cli v1.4.1), with `DOCKER_HOST="tcp://192.168.59.103:2376"`, still no response on `docker attach`. An earlier comment alludes that using IP export with 0.11.1 will work, but I still get the issue on 1.4.1.

**Comment by joallard** [comment]
In fact, 

```
$ boot2docker ssh
docker@boot2docker:~$ docker attach insane_mccarthy
# no response
```

Is this expected/the same issue?

**Comment by eerkel** [comment]
Just to chime in that docker `exec -it my-container bash` is what works for me. Thanks @joallard!
