### ISSUE TITLE
Bridged networking support

### ISSUE THREAD

**Issue by webdev** [boot2docker/boot2docker#160]
Does boot2docker have bridged networking support?

**Comment by majidaldo** [comment]
i didn't get a inet address

**Comment by dominicphillips** [comment]
VBoxManage modifyvm boot2docker-vm --nic3 bridged
VBoxManage modifyvm boot2docker-vm --bridgeadapter3 "en0"

**Comment by k1xme** [comment]
@jdmarshall That works fine! Thank you!

**Comment by fyddaben** [comment]
@jdmarshall  it works for me .very thank u

**Comment by mrvicadai** [comment]
many thanks @jdmarshall

**Comment by dweinstein** [comment]
Has anyone using the approach of adding a bridged network adapter noticed a bit of instability when communicating to the host from another device on the network? I've often gotten "Host is down" errors like when trying to ping or access the services from a system other than the underlying physical host.

**Comment by nick-korsakov** [comment]
Yet another +1 for official bridged network support.

My case. I wish to use Macvlan to access containers via IP from remote hosts.
My current workaround:

- create bridged adapter manually with promisc mode;
- SSH to Docker host and set promisc mode on the bridged eth0 (ip link set eth0 promisc on).

It will be very handy to me to have this ability out of the box (install docker, push container and go).

**Comment by bardware** [comment]
Activating the 3rd network adapter was not enough for me. It also had to be set to promiscous mode.
