### ISSUE TITLE
ARM support.

### ISSUE THREAD

**Issue by pr0xr** [boot2docker/boot2docker#25]
Add ARM support to build for portable devices for example Raspberry Pi. Then we could just dd the iso to sdcard and run in from there. What do you think about this?

**Comment by hlev** [comment]
I appreciate this is a closed issue, but as others (Resin, hypriot) seem to have pulled off Docker on the RPi, has this been ever revisited?

**Comment by tianon** [comment]
Docker itself functioning on ARM is a different thing from Docker being officially supported on ARM.  The official word upstream is still that ARM platforms are strictly on-your-own; there aren't even official daemon-supported binaries available for ARM (they have to be compiled out of band).  I'd love to see people playing around with the idea of boot2docker for ARM, but making it official is something that cannot happen unless and until Docker officially supports ARM.

**Comment by hlev** [comment]
I see, understandable. Thanks for the prompt response!
