### ISSUE TITLE
Kernel panic on VirtualBox 4.3.8 (Mac OS X)

### ISSUE THREAD

**Issue by sardaukar** [boot2docker/boot2docker#260]
Was working fine on 4.3.6, got the prompt to update, now I get this when I start up the VM:

![screenshot 2014-02-27 10 04 12](https://f.cloud.github.com/assets/153407/2280610/5100c152-9f8e-11e3-9e00-eddee178a207.png)

As a trial, I got rid of the existing VM and did "boot2docker init" again, and I get this output:

<pre>
2014-02-27 10:07:39] Creating VM boot2docker-vm
Virtual machine 'boot2docker-vm' is created and registered.
UUID: 850f50bd-6a46-4fc8-9928-73afe052f69b
Settings file: '/Users/bruno/VirtualBox VMs/boot2docker-vm/boot2docker-vm.vbox'
[2014-02-27 10:07:39] Setting VM settings
[2014-02-27 10:07:39] Setting VM networking
[2014-02-27 10:07:39] boot2docker.iso not found.
[2014-02-27 10:07:40] Could not get lastest release name! Cannot download boot2docker.iso.
[2014-02-27 10:07:40] Setting VM disks
[2014-02-27 10:07:40] Creating 40000 Meg hard drive...
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Disk image created. UUID: 82544767-df97-4757-af9d-bdee89e0fbb1
Converting from raw image file="format-flag.txt" to file="format-flag.vmdk"...
Creating dynamic image with size 5242880 bytes (5MB)...
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Clone hard disk created in format 'VMDK'. UUID: 82544767-df97-4757-af9d-bdee89e0fbb1
VBoxManage: error: Could not find file for the medium '/Users/bruno/Downloads/./boot2docker.iso' (VERR_FILE_NOT_FOUND)
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component Medium, interface IMedium, callee nsISupports
VBoxManage: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 178 of file VBoxManageDisk.cpp
VBoxManage: error: Invalid UUID or filename "./boot2docker.iso"
[2014-02-27 10:07:41] Done.
[2014-02-27 10:07:41] You can now type boot2docker up and wait for the VM to start.
</pre>

This creates an empty VM :( so I downloaded the 0.6 boot2docker ISO and put it on the same folder, that works - but the VM crashes as seen above.

Please help?

**Comment by gaolitao** [comment]
Has this issue been fixed in 4.3.20 for Linux?
I met this issue today.
The error message is same with the 1st screen capture:
https://camo.githubusercontent.com/df38f0db4628f6085ecef3d9ae0d1ffeef508a63/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3135333430372f323238303631302f35313030633135322d396638652d313165332d396530302d6564646565313738613230372e706e67
