### ISSUE TITLE
UTF-8

### ISSUE THREAD

**Issue by j0hnsmith** [boot2docker/boot2docker#277]
In a container running in boot2docker I'm mounting a samba share, when I list the filenames in a python script they're encoded with `iso8859-1`, this is a problem for me because our production environments (and every other version of linux I've ever used) use `UTF-8`. 

I'm a little suprised that our container (app) runs differently on different hosts as that's exactly what we're trying to avoid by using docker. Yes we could write some extra lines of code but that seems a bit of an odd thing to do just to get our container to work in a boot2docker environment. Colleagues of mine that use Ubuntu, therefore have no need for boot2docker, see the filenames as UTF-8.

These are the relevant env vars in boot2docker

```
G_FILENAME_ENCODING=iso8859-1
LANG=C
```

This is what I see in Ubuntu

```
LANGUAGE=en_GB.UTF-8
LANG=en_GB.UTF-8
LC_ALL=en_GB.UTF-8
```

I have tried explicitly setting UTF-8 vars in the container's environment but it doesn't seem to make any difference, nor does modifying the values in `/etc/sysconfig/language` and `/etc/sysconfig/language`. I suspect that boot2docker doesn't contain the necessary files (eg language pack or whatever) to handle UTF-8 at all.

Whilst `iso8859-1` is perfectly valid, I suggest that a UTF-8 variant would be a better default since that's what's most commonly used in the wild.

**Comment by yosifkit** [comment]
(Sorry for the long tail)

This was fixed on folders mounted automatically in https://github.com/boot2docker/boot2docker/pull/1044.  I would guess that the same mount option would apply to your Samba share.

**Comment by tianon** [comment]
Closing, since this appears to be resolved. :+1:
