### ISSUE TITLE
trigger b2d to run ntpdate on OSX/WIndows resume events

### ISSUE THREAD

**Issue by amattn** [boot2docker/boot2docker#290]
Mac OS X, when the laptop is closed/sleeping, the b2d VM clock does not tick.

Is it possible to get ntp or some other mechanism of keeping the clock correct in place?

**Comment by cooniur** [comment]
Has this issue been fixed? I just found after sleeping and resuming my Mac, the time in boot2docker VM is 15min behind the host. I'm on the latest version (1.5.0).

**Comment by jmshelby** [comment]
I noticed this still happening to me today. On 1.5.0 as well ...

**Comment by inflector** [comment]
Definitely happens to me too

**Comment by jordi-chacon** [comment]
Happens to me too.

**Comment by frankamp** [comment]
Me too, time to reopen this or #840

**Comment by mickep76** [comment]
Here is an example using the SleepWatcher workaround.

**Install SleepWatcher:**

```bash
brew install SleepWatcher
```

**Launch and enable on login:**

```bash
launchctl load ~/Library/LaunchAgents/de.bernhard-baehr.sleepwatcher-20compatibility-localuser.plist
ln -sfv /usr/local/opt/sleepwatcher/*.plist ~/Library/LaunchAgents
```

**Create wake up script:**

```bash
sudo tee /etc/rc.wakeup << EOF >/dev/null
#!/bin/bash

su - ${USER} -c "PATH=/usr/local/bin; docker-machine ssh <machine> 'sudo ntpclient -s -h pool.ntp.org'"
EOF
sudo chmod +x /etc/rc.wakeup
```

Replace ```<machine>``` with the name of your docker-machine instance.

**Comment by veacks** [comment]
In case of somebody is still looking for the solution an came across this issue, 
`nodemon --lagacy-watch` or `nodemon -L` seems to do the trick for me.
