### ISSUE TITLE
Documentation: How to add a self-signed certificate

### ISSUE THREAD

**Issue by kennu** [boot2docker/boot2docker#347]
I'm trying to use a private Docker image registry with a self-signed certificate. But I can't find documentation how to add the self-signed certificate to boot2docker, so that the Docker client would accept it.

**Comment by hairyhenderson** [comment]
Just wanted to add my experience since it took me so long to figure this out ;)

I decided to follow @steeve's advice and put my certs right in the image. @kfish's followup was also useful, except it took me a head-scratching hour to figure out why this wasn't working in the Dockerfile.

The problem was that `/etc/ssl/certs/ca-certificates.crt` gets overwritten at boot time, so I added a command to the `/etc/init.d/rcS` script.

Here's what I ended up with:
```
FROM boot2docker/boot2docker

RUN mkdir -p $ROOTFS/usr/local/share/ca-certificates/foo.com
COPY foo.crt $ROOTFS/usr/local/share/ca-certificates/foo.com
RUN mkdir -p $ROOTFS/usr/local/etc/ssl/certs && \
  cd $ROOTFS/usr/local/etc/ssl/certs && \
  ln -s /usr/local/share/ca-certificates/foo.com/foo.crt foo.crt && \
  export hash=`openssl x509 -hash -in $ROOTFS/usr/local/share/ca-certificates/foo.com/foo.crt | head -n1` && \
  ln -s foo.crt $hash.0 && \
  echo "cat /usr/local/share/ca-certificates/foo.com/foo.crt >> /usr/lodal/etc/ssl/certs/ca-certificates.crt" >> $ROOTFS/etc/init.d/rcS

RUN /make_iso.sh
CMD ["cat", "boot2docker.iso"]
```

**Comment by irgeek** [comment]
I had to solve this for a second time today as I restarted the VM without realising the way I did it last time wouldn't be persisted. So I created `/var/lib/boot2docker/certs/`, chucked all of the private certs I need in there and added created `/var/lib/boot2docker/bootlocal.sh` to install them. Gisted for everyone's downloading pleasure: https://gist.github.com/irgeek/afb2e05775fff532f960

Some notes about the certs in the `/var/lib/boot2docker/certs/` directory:

* They need to be PEM formatted
* If you're behind a corporate MITM proxy, you should to add all the certificates in the chain.
* One cert per file. If you've been given a chain file, just split out the individual certs. Naming the files based on subject makes figuring out what's there *so* much easier too. For the lazy, the following commands will split a chain file into individual files and rename them based on the certificate subject:

```sh
mkdir certs
split -p BEGIN ${CHAIN_FILE} chain-cert-
for i in chain-cert-*; do mv $i certs/$(openssl x509 -noout -subject -in $i | grep -o "CN=.*" | cut -c4- | tr " /" "_"); done
```

**Comment by kolis** [comment]
@irgeek Thank you, this setup works for me!
Before this I tried adding `EXTRA_ARGS="--insecure-registry my.registry.domain:port"`
to `/var/lib/boot2docker/profile` but this only solves half the problem, I still get the
`x509: certificate signed by unknown authority` response.

**Comment by hordemark** [comment]
@irgeek  +1, works for me

**Comment by rickli1989** [comment]
@irgeek +1, works for me

**Comment by mickep76** [comment]
I got it working in a similar manner:

```bash
boot2docker ssh
sudo tee /var/lib/boot2docker/bootlocal.sh << EOF >/dev/null
#!/bin/sh
curl http://<myserver>/ca.crt >>/etc/ssl/certs/ca-certificates.crt
EOF
sudo chmod +x /var/lib/boot2docker/bootlocal.sh
exit
boot2docker restart
```

**Comment by kevinsimper** [comment]
My files is not copied into boot2docker? Anybody know why? Or is there something else you have to do yo make @irgeek solution work?

**Comment by jacoelho** [comment]
Couldn't we use a container for this?
```docker run -v /etc/ssl/certs/:/etc/ssl/certs/ -v /usr/local/share/ca-certificates:/usr/local/share/ca-certificates ubuntu``` 

add certificates and run all the needed commands

this should work (not tested yet)

**Comment by smielke** [comment]
@jacoelho great approach, thanks! Sometimes the simplest solutions are the best.

**Comment by roma86** [comment]
Add my two cents worth. Connect docker to private registry unexpected hard procedure.
I have installed official docker-registry under nginx ssl proxy with basic auth. 
Testing connection to this registry from my mac:

```bash

# port 80 redirect to 301 as setup
$ curl cwt-registry.com
<head><title>301 Moved Permanently</title></head>

```

```bash
# wrong auth password
$ curl --user kdocker:'**' --cacert ~/Downloads/ca.pem  https://cwt-registry.com
<head><title>401 Authorization Required</title></head>
```

```bash
# correct user/login
$ curl --user kdocker:'*****' --cacert ~/Downloads/ca.pem  https://cwt-registry.com
"\"docker-registry server\""
```

```bash
# v1/_ping also works
$ curl --user kdocker:'Ju3ke*3h499(sdj0)sd5e2' --cacert ~/Downloads/ca.pem  https://cwt-registry.com/v1/_ping
"{}"
```

I used the methods described @mickep76 and @irgeek 

But every time get same error:

```bash
$ docker login cwt-registry.com

"Error response from daemon: v1 ping attempt failed with error: Get https://cwt-registry.com/v1/_ping ...
simply place the CA certificate at /etc/docker/certs.d/cwt-registry.com/ca.crt"

```

Follow this message i try this 

```bash
docker@boot2docker:~$ sudo vi /var/lib/boot2docker/bootlocal.sh
sudo mkdir -p "/etc/docker/certs.d/cwt-registry.com"
sudo cp "/var/lib/boot2docker/certs/ca.pem" "/etc/docker/certs.d/cwt-registry.com/ca.crt"
exit

$ boot2docker restart
$ boot2docker ssh

docker@boot2docker:~$ sudo ls /etc/docker/certs.d/cwt-registry.com/
ca.crt

``` 
Finally same result. 

I can not understand why is so hard. 

I am sorry, @jacoelho can you explain you method of resolve this issue. I can run ubuntu container in way that you describe, but how it should help connect to private registry?

**Comment by tlightsky** [comment]
@mickep76 +1,works well for me

**Comment by lily93** [comment]
in my case nothing is working - i am using boot2docker under windows..
i added the certificate in /etc/docker/certs.d/<registry>/ and in /usr/share/local/ca-certificates as .crt
and also in /etc/ssl/certs as .pem file

i also copied the .pem into .boot2docker/certs/boot2docker-vm..

restarted everything and still cannot login... via firefox i can ping the registry and in ubuntu everything works fine :/

please help!!!

**Comment by mkozjak** [comment]
@mickep76 +1, thanks!!

**Comment by adampats** [comment]
:+1:

**Comment by flychen50** [comment]
@mickep76  thank you,+1

**Comment by daagar** [comment]
The solution presented by @irgeek above worked fine for docker 1.7.1/boot2docker - however, it seems to no longer be sufficient for Docker 1.8.1b via a Toolbox installation. 

I've added the needed cert to /var/lib/boot2docker/certs, and created the necessary bootlocal.sh script. This _does_ allow 'docker pull' to get past the x509 error. However, the pull itself still fails (from the client, with a 'Can't reach any registry endpoint'). The following shows the relevant excerpt form docker.log. Note that once outside of the company network on the same installation, a 'docker pull' works fine. I'm commenting here as I still believe it is something going wonky with the certs, but I can open this as a new issue if that's not the case.

```
time="2015-08-19T14:13:25.025194341Z" level=debug msg="Calling POST /images/crea
te"
time="2015-08-19T14:13:25.025268176Z" level=info msg="POST /v1.20/images/create?
fromImage=hello-world%3Alatest"
time="2015-08-19T14:13:25.025758796Z" level=debug msg="Trying to pull hello-worl
d from https://registry-1.docker.io v2"
time="2015-08-19T14:13:25.576184346Z" level=debug msg="Fetched 1 base graphs at
2015-08-19 14:13:25.57615336 +0000 UTC"
time="2015-08-19T14:13:25.584767097Z" level=debug msg="Reloaded graph with 3 gra
nts expiring at 2017-03-22 19:04:46.713978458 +0000 UTC"
time="2015-08-19T14:13:26.397998709Z" level=debug msg="Pulling tag from V2 regis
try: \"latest\""
time="2015-08-19T14:13:27.414716213Z" level=debug msg="v2 error: errcode.Error u
nauthorized: access to the requested resource is not authorized"
time="2015-08-19T14:13:27.415026858Z" level=debug msg="Error trying v2 registry:
 unauthorized: access to the requested resource is not authorized"
time="2015-08-19T14:13:27.415058513Z" level=debug msg="Trying to pull hello-worl
d from https://index.docker.io v1"
time="2015-08-19T14:13:27.483446594Z" level=debug msg="Fetched 1 base graphs at
2015-08-19 14:13:27.483413884 +0000 UTC"
time="2015-08-19T14:13:27.483511319Z" level=debug msg="hostDir: /etc/docker/cert
s.d/docker.io"
time="2015-08-19T14:13:27.484138172Z" level=debug msg="[registry] Calling GET ht
tps://index.docker.io/v1/repositories/library/hello-world/images"
time="2015-08-19T14:13:27.495658509Z" level=debug msg="Reloaded graph with 3 gra
nts expiring at 2017-03-22 19:04:46.713978458 +0000 UTC"
time="2015-08-19T14:13:29.542515521Z" level=debug msg="Retrieving the tag list"

time="2015-08-19T14:13:29.967607311Z" level=debug msg="Got status code 401 from
https://registry-1.docker.io/v1/repositories/library/hello-world/tags/latest"
time="2015-08-19T14:13:29.967762474Z" level=error msg="unable to get remote tags
: Could not reach any registry endpoint"
time="2015-08-19T14:13:29.968026579Z" level=debug msg="Not continuing with error
: Could not reach any registry endpoint"
```

**Comment by smalltown** [comment]
Just like @daagar  said, I cannot workaround by the same method neither, when Docker version high than 1.8.1 via a Toolbox installation, the only thing I can do is to add ```EXTRA_ARGS="--insecure-registry https://#{Host Name}:#{Port Number}"``` parameter in the **/var/lib/boot2docker/profile**, and using docker-machine to restart the boot2docker, then I can use docker login feature...

**Comment by livecano** [comment]
Can you guys confirm if the actual workaround on the documentation [Using self-signed certificates](https://docs.docker.com/registry/insecure/) is valid for docker > 1.8.1 via Toolbox? I place my ca in the folder /etc/docker/certs.d/domain:8080/ca.crt which points to the private registry and still not working at all, I wonder if there is any way to use the self-signed certificate without having to add the flag --insecure-registry to the configuration.

**Comment by varsy** [comment]
I've installed Docker Toolbox on Mac instead of boot2docker and now it can't work with insecure registry. I haven't any `/var/lib/boot2docker/profile` file and nothing happened even when I created one with `EXTRA_ARGS`. Placing my ca.cert to `/etc/docker/certs.d/.../ca.rt` inside the VM don't work either.
As for me, following workaround helped. Edit `/etc/init.d/docker` inside your virtualbox VM:
```
vars@andreysizov-mbp:~ » docker-machine ssh default
docker@default:~$ sudo vi /etc/init.d/docker
```
Add line:
```
...
test -f '/var/lib/boot2docker/profile' && . '/var/lib/boot2docker/profile'

EXTRA_ARGS="--insecure-registry docker-registry.labs.intellij.net"
...
```
Restart `docker` service:
```
docker@default:~$ sudo /etc/init.d/docker stop
docker@default:~$ sudo /etc/init.d/docker start
```

**Comment by olimsaidov** [comment]
@varsy, Thank you!

**Comment by Shuliyey** [comment]
as far as I now boot2docker doesn't come with any certificate import tools, so this made it a bit difficult to add ssl certificate to your certificate bundle.

But you can still do it manually. 

* make sure you have your selfsigned certificate in PEM format, usually this file has the .crt extension, copy the file to **/usr/local/share/ca-certificates**
```bash
cp <your_crt_file> /usr/local/share/ca-certificates/
```
* check again this crt file of your is in PEM format, the below command should return 1, if it is in PEM format, otherwise you should convert your crt file to PEM format.
```bash
cat /usr/local/share/ca-certificates/<your_crt_file> | grep 'BEGIN.* CERTIFICATE' | wc -l
```
* (optional) you should verify that the fingerprint of this certificate does match the original certificate you created, but this step is not necessary as long as you are sure the crt file you are trying to import to the ca-bundle can be trusted
```bash
openssl x509 -noout -fingerprint -in /usr/local/share/ca-certificates/<your_crt_file>
```
*  create a .pem simlink in /etc/ssl/certs pointing to your original certificate location
```bash
ln -s /usr/local/share/ca-certificate.<your_crt_file> /etc/ssl/certs/<your_crt_file_name_without_extension>.pem
```
* create a hash simlink (this hash simlink should end with .0) in /etc/ssl/certs pointing to the previous .pem simlink you just created
```bash
cd /etc/ssl/certs && ln -s <the_previous_pem_simlink_you_created> `openssl x509 -noout -hash -in /usr/local/share/ca-certificates/<your_crt_file>`.0
```
* last step for extra assurance, append the content of your crt file to the **/etc/ssl/certs/ca-certificates.crt**. Please do this step carefully, it's always a good idea to back up the **/etc/ssl/certs/ca-certificates.crt** file, before doing this step (in case you actually overridden the file, instead of modifying it) 
```bash
cat /usr/local/share/ca-certificates/<your_crt_file> >> /etc/ssl/certs/ca-certificate.crt
```


If you have done all the above step correctly you should get something like this

```bash
infinityadmin@mep-openstack1:/etc/ssl/certs$ ls -l /etc/ssl/certs | grep blue
lrwxrwxrwx 1 root root     12 Feb  5 07:56 37b52fd1.0 -> bluecoat.pem
lrwxrwxrwx 1 root root     45 Feb  5 07:56 bluecoat.pem -> /usr/local/share/ca-certificates/bluecoat.crt
```

In my case
the bluecoat.crt is my <crt_file>, bluecoat.pem is the pem simlink file i created pointing to my bluecoat.crt. 37b52fd1.0 is the hash simlink I created pointing to my pem simlink.

For more information, you can read this article
http://gagravarr.org/writing/openssl-certs/others.shtml

**Comment by tobilarscheid** [comment]
Hi,

thanks for your input. This really helped a lot! Actually, this is the only working way for boot2docker.

Two additions:

Shouldn't this

> ln -s /usr/local/share/ca-certificate.<your_crt_file> /etc/ssl/certs/<your_crt_file_name_without_the_file_type>.pem

rather be

> ln -s /usr/local/share/ca-certificate**s/**<your_crt_file> /etc/ssl/certs/<your_crt_file_name_without_the_file_type>.pem

??

Also, in this statement:

> cat /usr/local/share/ca-certificates/<your_crt_file> >> /etc/ssl/certs/ca-certificate.crt

the last part should be

> cat /usr/local/share/ca-certificates/<your_crt_file> >> /etc/ssl/certs/ca-certificate**s**.crt

**Comment by Shuliyey** [comment]
thanks @tobilarscheid, you are right  :smile: 

I've fixed the typo ;). Cheers :+1:

**Comment by daagar** [comment]
Holy cow, that works @Shuliyey! I do still need a copy of the *.pem files to be in /var/lib/boot2docker/certs as well but otherwise that was the magic voodoo to finally hit the official docker hub from inside a MITM certificate rewrite proxy.

**Comment by Shuliyey** [comment]
thanks you @daagar , glad it worked :smile: .

sorry I'm actually trying to understand the **/var/lib/boot2docker/certs** part, do you mean if the certificate is not in **/var/lib/boot2docker/certs**, you actually won't be able to do docker pull/push?

Interesting case, does it apply for the both the case?
*  doing a docker pull/push from a host terminal (so not in the boot2docker vm, but on the Windows/Mac host)
*  doing a docker pull/push inside the boot2docker vm

I believe the **/var/lib/boot2docker** repository is mainly used to provide the communication between the **boot2docker guest vm** and the **host OS (Windows/Mac)**. So I'm trying to get a better understanding on how boot2docker manages its certificates verification

**Comment by Shuliyey** [comment]
thanks @mickep76 +1 :+1: 

the changes that's made to boot2docker / partition  drive will be overritten everytime docker-machine is restarted. So the /var/lib/boot2docker/bootlocal.sh is useful in this case to keep your changes.


* create the /var/lib/boot2docker/bootlocal.sh file and set the execution permission correctly
```bash
sudo touch /var/lib/boot2docker/bootlocal.sh && sudo chmod +x /var/lib/boot2docker/bootlocal.sh
```
* put your self-signed crt file at **/var/lib/boot2docker/certs/**, this path can actually be any path, that have its files statically saved (instead of dynamically generated). E.g. **/home/docker/** can also be a good choice
```bash
sudo mkdir /var/lib/boot2docker/certs
mv <your_crt_file> /var/lib/boot2docker/certs/
```

* add the changes to be made into /var/lib/boot2docker/bootlocal.sh, (In this case, we're adding the certificate to /etc/docker/certs.d/<registry_url>)
```bash
mkdir -p /etc/docker/certs.d/<your_docker_registry_url> && cp <your_crt_file_location> /etc/docker/certs.d/<your_docker_registry_url>/
```

In my case this is mine contents in **/var/lib/boot2docker/bootlocal.sh**
```bash
mkdir -p /etc/docker/certs.d/registry.mev-rancher.dev.tech.local && cp /var/lib/boot2docker/certs/radiance.crt /etc/docker/certs.d/registry.mev-rancher.dev.tech.local/
```

**Comment by kumlali** [comment]
Thanks @Shuliyey. In my environment(Docker Toolbox 1.9.1i & Windows 7), copying certificate files to `/var/lib/boot2docker/certs` is enough. I do not need to create `/etc/docker/certs.d/<your_docker_registry_url>` and copy files to it.

@all
After I spent significant time to make Docker Toolbox on Windows behind proxy to work, I decided to create a small project to help others: https://github.com/kumlali/windocker. 

Hope you'll find it usefull.

**Comment by Shuliyey** [comment]
@kumlali nice, would be great also to integrate this into kinematic. If we can configure the proxy setting inside the kinematic gui (like in the settings page), would make proxy and certificate configuration much easier.

**Comment by so0k** [comment]
ok, so since Boot2Docker 1.6 any certs you place in `/var/lib/boot2docker/certs` are automatically loaded for you - cool

see: https://github.com/boot2docker/boot2docker/pull/807/files

**Comment by nicklozon** [comment]
@Shuliyey thanks for this. My company performs a man in the middle attack, so I had to export the cert from windows certificate manager, copy it into my vm and use openssl to convert it from DER to PEM format with a .crt extension, then followed your instructions.

**Comment by gotgenes** [comment]
> ok, so since Boot2Docker 1.6 any certs you place in `/var/lib/boot2docker/certs` are automatically loaded for you - cool
> 
> see: https://github.com/boot2docker/boot2docker/pull/807/files

If you're arriving here from Google, the above is the proper solution to "How do I use self-signed certificates when using boot2docker." Note, though, at the moment, **only certificates that end with `.pem` will be processed**. (I have submitted PR #1167 that would also process certificates ending in `.crt` per [the Docker self-signed certificate instructions](https://docs.docker.com/registry/insecure/#using-self-signed-certificates).)

If you place your certificate in `/var/lib/boot2docker/certs/` but it doesn't work, [make sure it's in PEM format](http://stackoverflow.com/a/991772/38140), and make sure the file name ends with ".pem".

**Comment by magnayn** [comment]
I've followed the self-signed cert instructions, used the certificate in an nginx proxy, added the cert in /var/lib/boot2docker/certs (actually in my boot2docker 1.11.2, that directory did not exist) and I *still* get 

x509: certificate signed by unknown authority

**Comment by gotgenes** [comment]
@magnayn Did you reboot your boot2docker instance after adding your certificates to `/var/lib/boot2docker/certs`? boot2docker will not process the certificates until a reboot takes place. In my case, I issued

    docker-machine reboot <boot2docker_instance>

Also, yes, by default there is no `certs` directory in `/var/lib/boot2docker`; I had to create it, too.

**Comment by magnayn** [comment]
Good to know that the need to create the certs directory is normal.

Yes, I rebooted the docker-machine. curl is perfectly happy if I tell it
about the cert on the commandline.

**Comment by so0k** [comment]
Could you try these instructions? http://docker-saigon.github.io/post/Private-Registry-Setup/ it includes adding trust for self signed CA

**Comment by Shuliyey** [comment]
@magnayn  interesting the boot2docker 1.11 version of docker should work if the certificate is placed in the **/var/lib/boot2docker/certs**
did you put the **public** certificate (which is not the **private key**) in the **/var/lib/boot2docker/certs**

if you could do the below and verify your certificate (which you put under **/var/lib/boot2docker/certs**)
```bash
cat /var/lib/boot2docker/certs/<your_crt_file> | grep 'BEGIN.* CERTIFICATE' | wc -l # this should return 1
```
:smile:

**Comment by softwarevamp** [comment]
container does trust the certificate but the certificate not placed in the root of container.
when i  run ruby got below:
```
Fetching source index from https://rubygems.org/

Retrying fetcher due to error (2/4): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://rubygems.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
```

**Comment by so0k** [comment]
@softwarevamp - for containers to trust ca's from the host, mount the host certs dir and run `update-certificates` before boot up?

**Comment by MetinSolmaz** [comment]
In Boot2Docker (version 17.10.0-ce), for me it only worked when the certificate was called 'ca.crt' in a folder with hostname for which the certificate was used.

So copy the certificate as follows:
/var/lib/boot2docker/etc/docker/certs.d/<hostname>/ca.crt

**Comment by leonardochaia** [comment]
In Boot2Docker 18.05.0-ce using self-signed certificates it seems to be enough by copying the `ca.crt` and `cert.pem` to `/etc/docker/certs.d/{hostname}` in a `bootsync.sh` script.

`Boot2Docker version 18.05.0-ce, build HEAD : b5d6989 - Thu May 10 16:35:28 UTC 2018
Docker version 18.05.0-ce, build f150324`
