### ISSUE TITLE
Version inaccuracies

### ISSUE THREAD

**Issue by tt** [boot2docker/boot2docker#359]
I recreated my boot2docker host, but noticed that when connecting to it, it isn't what it say it is.

```
$ cat /etc/boot2docker
master : 17bb8c2 - Thu May  8 02:55:10 UTC 2014

$ cat /etc/version
0.8.1
```

The MD5 checksum of my `~/.boot2docker/boot2docker.iso` is 217301e8e71f0c7479dd577bb3c255de. I have verified that this is also what VirtualBox is using. The Docker version is 0.11.1, which further proves that it is the most recent image.

The commit ID is after the v0.8.1 tag (f2612d3...17bb8c2), but still behind the actual v0.9.0 tag (17bb8c2...41ad76d). Please also note that these some of the release tags are annotated and some aren't.

**Comment by wglambert** [comment]
Issue is resolved

```console
Boot2Docker version 18.05.0-ce, build HEAD : b5d6989 - Thu May 10 16:35:28 UTC 2018
Docker version 18.05.0-ce, build f150324
docker@boot2docker:~$ cat /etc/boot2docker 
HEAD : b5d6989 - Thu May 10 16:35:28 UTC 2018
docker@boot2docker:~$ cat /etc/version 
18.05.0-ce
```
