### ISSUE TITLE
Can't access internet from containers without --net=host

### ISSUE THREAD

**Issue by jojow** [boot2docker/boot2docker#365]
Hi there, I installed docker and boot2docker using homebrew as explained here: http://docs.docker.io/installation/mac

However, when I run a container using

```
docker run -i -t ubuntu bash
```

I can't access the internet. E.g., a

```
ping google.com
```

doesn't work at all.

If I run the container with the '--net=host' option

```
docker run --net=host -i -t ubuntu bash
```

I can access the internet.

But this option doesn't work with 'docker build', so I'm not be able to build images when files have to be downloaded from the internet.

I have a Macbook Pro with the latest OS X version running.

Anyone else having the same issue?

**Comment by ThomasSteinbach** [comment]
I have this issue too. At my home network ```sudo docker run --rm ubuntu ping www.google.de``` works fine. When I am in the network of my university, I have to add ```--net=host```. Otherwise it won't work.

**Comment by bakanov** [comment]
I have same problem too. My host machine is debian 7 with upgrated kernel:
$uname -r
3.16.0-0.bpo.4-amd64
I use latest docker 1.8.1
It works fine:
sudo docker run --net=host debian:jessie ping -c 3 www.yandex.ru
It's not working:
sudo docker run debian:jessie ping -c 3 www.yandex.ru
(ping: unknown host)
It's not working too (ping yandex.ru by ip):
udo docker run debian:jessie ping -c 3 77.88.55.55
(3 packets transmitted, 0 packets received, 100% packet loss)
