### ISSUE TITLE
DOCKER_HOST have a weird tcp

### ISSUE THREAD

**Issue by Freyskeyd** [boot2docker/boot2docker#392]
Hey,

i don't know why, when i use `boot2docker up` to boot the VM, i get this:

``` bash
▶ boot2docker up
2014/06/11 22:49:00 Waiting for VM to be started...
...........2014/06/11 22:49:22 exit status 255

2014/06/11 22:49:22 Started.
2014/06/11 22:49:22 Auto detection of the VM's IP address.
2014/06/11 22:49:22 To connect the Docker client to the Docker daemon, please set:
2014/06/11 22:49:22     export DOCKER_HOST=tcp://:41960
```

I'm on OSX Mavericks with :

``` bash
▶ boot2docker version
Client version: v0.12.0
Git commit: 16abe29
```

**Comment by SvenDowideit** [comment]
yes, you are hopefully misunderstanding. The only reason you might need to set up a port forward, is if you want to access the container from a machine that is _not_ your host box. 

From your host box, you should be able to access all docker port mapped container ports by using the host-only network address (run `boot2docker ip`).

This issue is specific to a very narrow set of users - for whom something in the network setup we do isn't working, so the host-only network doesn't seem to work. Everyone else won't need the `DocekrPort=2375` setting, or to go through any of this pain.

**Comment by tjrivera** [comment]
In most cases setting up port forwarding to facilitate access from a machine that is *not* my host box to  a container on on my host box makes sense. 

In this particular case I'm referring specifically to this workaround (the port-forward rule) that punches a hole through the network rules that Cisco AnyConnect clobbers my machine with during a VPN connection. My understanding is that setting this rule would allow my docker client to communicated to the daemon running in the b2d vm (by forwarding 2376). If I were to run a container in my b2d that exposes a service on port 8000, for example, then I'd *also* have to punch a hole through Cisco's blanket rules to communicate from my host machine to the b2d vm. 

In any case, I understanding this effects a very small slice of users, so I'm already thankful for the amount of attention this issue has received, I'm also unsure how to consistently set host <-> b2d <-> vpn network settings in a sane, usable way.

**Comment by bortels** [comment]
There may be some confusion in the comments just prior to this one - let me clarify, and mention what works for me. 

Apparently boot2docker + OS X 10.10 + Cisco Anyconnect are a witches brew of ugly. Routing-based solutions seem to fail entirely (where they worked on 10.9) - as soon as Anyconnect wakes up, you basically can't talk to the docker vm at all, or at least I couldn't. 

The workaround (hopefully temporary!) is to use port forwarding, then connect to 127.0.0.1, which will bypass Anyconnect and let you thru. Here's what I did that seemed to work:

    ➜  ~  boot2docker init  
    Latest release for boot2docker/boot2docker is v1.4.1
    Downloading boot2docker ISO image...
    Success: downloaded https://github.com/boot2docker/boot2docker/releases/download/v1.4.1/boot2docker.iso
	to /Users/tbortels/.boot2docker/boot2docker.iso
    ➜  ~  vboxmanage modifyvm "boot2docker-vm" --natpf1 "docker,tcp,127.0.0.1,2376,,2376"
    ➜  ~  boot2docker up 
    Waiting for VM and Docker daemon to start..........................oooooooooooooooooooo
    Started.
    Writing /Users/tbortels/.boot2docker/certs/boot2docker-vm/ca.pem
    Writing /Users/tbortels/.boot2docker/certs/boot2docker-vm/cert.pem
    Writing /Users/tbortels/.boot2docker/certs/boot2docker-vm/key.pem

    To connect the Docker client to the Docker daemon, please set:
        export DOCKER_HOST=tcp://192.168.59.104:2376
        export DOCKER_CERT_PATH=/Users/tbortels/.boot2docker/certs/boot2docker-vm
        export DOCKER_TLS_VERIFY=1

    ➜  ~  $(boot2docker shellinit)
    Writing /Users/tbortels/.boot2docker/certs/boot2docker-vm/ca.pem
    Writing /Users/tbortels/.boot2docker/certs/boot2docker-vm/cert.pem
    Writing /Users/tbortels/.boot2docker/certs/boot2docker-vm/key.pem
    ➜  ~  export DOCKER_HOST=tcp://127.0.0.1:2376
    ➜  ~  docker ps 
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
    ➜  ~

(Here's hoping that formats nicely)

Note that the docker containers are all still stuck behind port forwarding, so if you run one you want to connect to "from the outside", you'd need to add more port forwards, so this isn't a great solution. (I suspect, but have not tried yet, that within the VM the IP will work fine). But at least now I can hopefully do some docker builds and so on.

**Comment by SvenDowideit** [comment]
excellent summaries both of you - that leaves me thinking that adding a `boot2docker forward --add/--remove [PORT:PORT]` is still worthwhile - for both the AnyConnect VPN case, and those users that will want to give other computers access to their containers.

anyone want to take it on?

**Comment by christian-blades-cb** [comment]
Until there's a better solution, I [industrialized a hack](https://gist.github.com/christian-blades-cb/16e8ae55697ae65b5318) to get it to work. 

There are 2 stages:

1. Delete the firewall rule (lifted that code from [devopslife.com](http://www.devopslife.com/2014/08/08/docker-boot2docker-and-dns-resolution-of-containers.html#connecting-to-vpn-will-break-things))
2. Modify the routes

You can run this script after connecting or disconnecting from the AnyConnect tunnel and connection to the boot2docker vm will be restored.

Every so often, it will appear to hose all of my network connections, but a quick Turn Off Wifi/Turn On Wifi does the trick. 

Hope some of you find this useful!

**Comment by vitan** [comment]
I also met the similar VPN failed my *boot2docker up* problem, which is ssh issue also. And seem VPN app is removing the *127.0.0.1 localhost* away from */etc/hosts/*. Causing *ssh docker@localhost -p ....* can not loop to *ssh docker@127.0.0.1 -p *.

text it here in case some guys getting the same problem.

**Comment by kylepragerattensity** [comment]
On Mac OSX with Boot2Docker using Virtualbox, I changed Adapter 2 on my VM from "Host-only Adapter" to "Bridged Adapter".  That gave my VM a 10.x.x.x address on my home network (NAT'd of course behind a router), and it works now when I'm connected to my VPN for work.  HTH.

**Comment by ryanwalls** [comment]
@christian-blades-cb Thanks!  You're script helped us a lot!

**Comment by willbuck** [comment]
I've been plauged with this issue for a couple days, thanks to everyone that's posted in this thread for the suggestions.

I compiled the simplest, fewest number of steps I could that repeatably works, here it is (maybe it will help others!)

boot2docker delete
boot2docker download
boot2docker init
vboxmanage modifyvm "boot2docker-vm" --natpf1 "docker,tcp,127.0.0.1,2376,,2376"
boot2docker up
$(boot2docker shellinit)
export DOCKER_HOST=tcp://127.0.0.1:2376

**Comment by connaryscott** [comment]
I find it strange that my boot2docker is completely unusable AFTER I bring my cisco anyconnect down.  At least my vmware does not do this.  I do undertand a bit why local vms are inaccessible DURING the vpn connection.  boot2docker usability should be restored AUTOMATICALLY after anyconnect is brought down.

**Comment by zeroorone13** [comment]
@willbuck Thanks for the simplified steps! After that, this works while I am on the VPN or after I disconnect.

**Comment by willbuck** [comment]
Glad it helped @zeroorone13!

**Comment by dmlond** [comment]
The problem is that cisco anyconnect reroutes every network interface through its utun0 interface.  If you can create the boot2docker or docker-machine interface before you connect to the vpn, you can 'fix' the connection after you connect to vpn by restoring just the network segment that should go to the b2d interface.  You may also have to 'fix' the connection after you disconnect from anyconnect, since I think it tries to be too smart with the way it restores your original network interface connections (in the absence of knowledge about b2d).

For boot2docker, you can use this [script](https://gist.github.com/christian-blades-cb/16e8ae55697ae65b5318) to 'fix' the boot2docker connection.  If you are using docker-machine, I forked and modified the [script](https://gist.github.com/ori-rad-admin/cb3505349de89efe4075) to work with docker-machine.  The idea is the same.  

To connect to cisco vpn and still use docker, do the following:

* start boot2docker or docker-machine
```bash
$ boot2docker up
$ docker-machine start dev
```
* 'fix' the b2d or d-m network interface to make sure there is an interface in the machine routes for it (if you dont do this, and you run fix after connecting to vpn, you will be able to use docker, but your internet will not work).  The d-m version takes an argument for the specific machine you need to fix (you can fix every machine you are running by running this script for each machine).  Also, this requires you to have sudo rights on your mac:
```
# b2d
$ vpn-fix.sh
# d-m
$ vpn-fix.sh dev
```
* connect to vpn
* fix your b2d or d-m again by rerunning the above script

After you disconnect from the vpn, you may need to run the script again to restore the connection to the interface.  

Also, if your internet connection experiences an ephemeral hiccup and causes your anyconnect to reconnect, it will likely reconfigure the network and hose your connection to the b2d.  Just disconnect from vpn, run the fix script, reconnect to vpn, and run the fix script.  Yes, its a pain, but it does work.

**Comment by connaryscott** [comment]
Thank you for this simple and easy to understand fix.  Verified that it works with my anyconnect setup, v3.1.00495 on OSX 10.9.5

**Comment by Shaun1** [comment]
I recently had that problem with a fresh boot2docker install on Windows. Upgrading VirtualBox & VirtualBox Extension Pack solved the problem for me. In VirtualBox Manager go to Help-->Check for updates...

**Comment by xiangzhuyuan** [comment]
FATA[0000] An error occurred trying to connect: Get https://192.168.59.103:2376/v1.17/info: Forbidden

**Comment by tonypujals** [comment]
@nickmarden's solution worked for me. I had to replace 127.0.0.1 with 192.168.59.103 for my host IP, however.

**Comment by lahirug** [comment]
Boot2docker is piece of shit,don't' use it.

**Comment by wanghaisheng** [comment]
@lahirug  what do you suggest instead of boot2docker

**Comment by lahirug** [comment]
Creating your own VM. I have been incredibly having issues with boot2docker when I try to  mount my local file system and decided to move ahead with my own vm. Boot2docker is just a wasting of time of everyone.

**Comment by vitan** [comment]
@lahirug , I am using boot2docker as my development env, and easy-to-use with my terminal. So what's your issues?  You'd better to list them.

**Comment by dmlond** [comment]
I am using docker-machine + virtualbox, which uses the standard boot2docker virtualbox vm under the hood.  it works fine for me if I use [fix_vpn.sh](https://gist.github.com/dmann/f62f2dd17a02293121ed). Note, if you are using Yosemite, it ships without /sbin/ipfw, yet cisco anyconnect seems to be able to create a "deny ip from any to any" firewall rule. Without ipfw, fix_vpn.sh cannot find and remove it. You can find a OSX mavericks machine with /sbin/ipfw and copy the ipfw binary to your Yosemite machine, and this script will work again.  If anyone has suggestions for how to use the new apple pf firewall manager to fix this, that would be great.

**Comment by kevin-king** [comment]
@jchauncey That worked for me. Thanks! I installed using homebrew on Any Connect VPN, which seems to have messed things up. My exact steps were:

Uninstall:
Disconnect from VPN
Virtual Box -> Preferences -> Network -> Host-only Networks -> Delete
`boot2docker down`
`brew uninstall boot2docker`
`brew uninstall docker`
`rm -Rf ~/.boot2docker`
`rm -Rf ~/VirtualBox\ VMs/boot2docker-vm`

Reinstall:
`brew install boot2docker`
`boot2docker init`
`boot2docker up`
`$(boot2docker shellinit)`
`docker version`

**Comment by sk29110** [comment]
@kevin-king  so I shouldn't install docker?

**Comment by sk29110** [comment]
I still have the socket issue after setting Docker 23776 for port forwarding.
After boot2docker up

Trying to get Docker socket one more time
Error requesting socket: exit status 255
Auto detection of the VM's Docker socket failed.
Please run `boot2docker -v up` to diagnose.

tried uninstall reinstall a couple of times. However on my macbook which comes with El Capitain I didn't have the same problem. Is this java problem?

**Comment by Elijen** [comment]
@nickmarden This solution works and I think it's better then fiddling with routes set by AnyConnect (I need both Docker and my VPN working).

**Comment by connaryscott** [comment]
I use my mac for reading e-mails like this or dealing with other apps that corporations force you to use..
I do not use my mac for much of anything else.
Instead, I create a NAT’d vm that is agnostic to the network that my mac may use such as whether my stupid cisco vpn is in use or not…..

I just use docker on my CentOS vm (or whatever O/S you like)

**Comment by eelcocramer** [comment]
So last week I installed the new [Docker toolbox](https://www.docker.com/toolboxset) including docker-machine . I also installed a new version of Cisco AnyConnect (4.1.00028). Things are working without any problems for me at the moment. Before, after and while on the VPN connection.

**Comment by lutaoact** [comment]
worked for me. Thanks.

    sudo route -nv add -net 192.168.99 -interface vboxnet0
