### ISSUE TITLE
"boot2docker up" asking for password

### ISSUE THREAD

**Issue by anderiv** [boot2docker/boot2docker#405]
I recently upgraded (via homebrew) to boot2docker v1.0.0. Since doing this, `boot2docker up` has been asking for a password:

```
$  ~  boot2docker up
2014/06/20 10:19:16 Waiting for VM to be started...
...........docker@localhost's password:
```

The boot2docker disk image is v1.0.1.

Any clues as to why this might be happening?

Additionally, it appears that the docker daemon in the boot2docker disk is not listening on the port I've configured it to use:

```
$  ~  cat .boot2docker/profile
DOCKER_PORT=44243

$  ~  boot2docker ssh
...
docker@boot2docker:~$ sudo netstat -tunlp | grep docker
tcp        0      0 :::2375                 :::*                    LISTEN      632/docker
```

To add one more point of confusion here, the vbox port forwarding mappings are messed up as well:

![screen shot 2014-06-20 at 10 39 22 am](https://cloud.githubusercontent.com/assets/1455490/3342324/37565a76-f891-11e3-8e46-c40a48e402e9.png)

Thank you!

**Comment by xcolwell** [comment]
I'm seeing this problem on OS X 10.10.1 repeatedly when using docker installed via

```brew cask install virtualbox
brew install docker
brew install boot2docker```

I've found the root cause in my case, which is the permissions of the docker private key get changed to `u=rw,go=r`, causing SSH to avoid using it (it requires that the private key be readable by the user only). 

```brien@LGN   ~   : ls -lah ~/.ssh/id_boot2docker
-rw-------@ 1 brien  staff   1.6K Jan  9 12:30 /Users/brien/.ssh/id_boot2docker
brien@LGN   ~   : ls -lah ~/.ssh/id_boot2docker.bak
-rw-r--r--@ 1 brien  staff   1.6K Jan  8 22:42 /Users/brien/.ssh/id_boot2docker.bad```

Fixing the permissions can be done with `chmod u=rw,go= ~/.ssh/id_boot2docker`.

Usually nothing touches my private keys, so I'm wondering if there's a check in boot2docker or some startup script that updates the permissions erroneously?

This is really frustrating, but I reset the permissions in my own init script for now.

**Comment by tj** [comment]
`rm -rf ~/.boot2docker/ ~/.ssh/id_boot2docker*` did it for me as well

**Comment by mgijsberti** [comment]
This worked for me: 
boot2docker delete
rm -rf ~/.boot2docker/ ~/.ssh/id_boot2docker*
boot2docker init
boot2docker up

**Comment by strogonoff** [comment]
In case anyone else happen to come across this, make sure you don’t have `boot2docker` running under another user account on the same machine simultaneously.

As a side note, even after stopping the VM running under first account I still haven’t been able so far to work with Docker from the second account. The VM takes much longer to start for some reason and after that docker client is not able to connect to it, throwing up with an “i/o timeout” error.

**Comment by RomanSaveljev** [comment]
The other issue with running boot2docker concurrently under different accounts is https://github.com/boot2docker/boot2docker-cli/issues/337

**Comment by mcqj** [comment]
This is still a problem in boot2docker 1.5.0

**Comment by nbjahan** [comment]
I had the same issue caused by `PreferredAuthentications password,keyboard-interactive,publickey` under `Host *` in `~/.ssh/config`

**Comment by karlingen** [comment]
+1

**Comment by garthk** [comment]
+1 @enjalot:

> `chmod go-r ~/.ssh/id_boot2docker`

Strikes me quite reasonable that `boot2docker` could check that and/or fix it.

**Comment by secrettriangle** [comment]
boot2docker shouldn't need to auth using an SSH key to connect to localhost. Maybe we should consider turning auth off completely in the VM's SSH daemon, and this issue would go away for free.

**Comment by kermit666** [comment]
OK, for me moving the old .ssh/id_boot2docker* files to a different folder and then running the sequence helped:

    boot2docker delete
    boot2docker download
    boot2docker -v init
    boot2docker start

**Comment by MartinSeeler** [comment]
I had this issue caused by my `./ssh/config` seetings to auto-copy zsh settings to remote by
```bash
Host *
   PermitLocalCommand yes
   LocalCommand tar c -C${HOME} .oh-my-zsh .zshrc .vim .vimrc | ssh -o PermitLocalCommand=no %n "tar mx -C${HOME} ; chsh -s /bin/zsh"
```

Removing these settings fixed it for me.

**Comment by thekarel** [comment]
I had to change the VirtualBox settings to not have a space in Default Machine Folder path:

![screen shot 2015-04-14 at 11 38 16](https://cloud.githubusercontent.com/assets/2061333/7134197/c9d97dbc-e29a-11e4-8b67-2b065b24888a.png)

Before this, running `boot2docker -v init` gave me

```
VBoxManage: error: Invalid UUID or filename "/Users/x/VirtualBox VMs/boot2docker-vm/boot2docker-vm.vmdk"
error in run: Failed to initialize machine "boot2docker-vm": exit status 1
```

Using docker and boot2docker 1.5.0 via brew

(via @jerrymf https://github.com/boot2docker/osx-installer/issues/106#issuecomment-87893137)

**Comment by tonypujals** [comment]
I was tearing my hair out for a while on this one. *Nothing* seemed to work, including everything mentioned in this thread. I had completely removed everything (.boot2docker/, ./ssh/id_boot2docker*, /usr/bin/local/boot2docker, VirtualBox VMs/boot2docker-vm/, VirtualBox application) and still couldn't fix. Installing latest version of boot2docker (1.5.0) didn't help, installing the latest VirtualBox (4.3.26) didn't help ... 

Finally, I opened the VirtualBox GUI and explicitly deleted all previous appliances (including boot2docker-vm and one I had renamed to 'dev'), and that finally did the trick. Argh. Hope this helps someone else.

**Comment by swogger** [comment]
Solution: As strange as it may sound you need to enter the password "tcuser" at least 4 times. Makes no sense but it works.

**Comment by toddlers** [comment]
@swogger  I've done that as well but no help :(
finally ran fours magic commands
```
boot2docker delete
rm -rf ~/.boot2docker/ ~/.ssh/id_boot2docker*
boot2docker init
boot2docker up
```
Worked fine :)

**Comment by shaimr** [comment]
Thanks @toddlers, it worked for me :+1:

**Comment by nerab** [comment]
Finally ... `rm -rf ~/.boot2docker/ ~/.ssh/id_boot2docker*` did the trick. Thanks, @toddlers!

**Comment by LEETcc** [comment]
Had the same error on fresh install following the exact instructions on https://docs.docker.com/installation/mac/

Reboot of the host machine solved my issue.

**Comment by tylercloke** [comment]
@toddlers black magic was effective.

**Comment by eduardopopego** [comment]
@toddlers solution worked for me too. Thanks!
