### ISSUE TITLE
Folder Sharing login

### ISSUE THREAD

**Issue by mgbellaire** [boot2docker/boot2docker#409]
When I start the samba-server box, I get an error.  The container remains running, I try to login and I use the username: docker and the password: tcuser and it fails.

Here is the error:

starting samba server container with my-data /data
add /data
Starting Samba daemons: nmbd smbd.
watching /var/log/samba/*
==> /var/log/samba/cores <==

==> /var/log/samba/log.nmbd <==
[2014/06/25 15:08:45,  0] nmbd/nmbd.c:861(main)
  nmbd version 3.6.6 started.
  Copyright Andrew Tridgell and the Samba Team 1992-2011

==> /var/log/samba/log.smbd <==
[2014/06/25 15:08:45,  0] smbd/server.c:1053(main)
  smbd version 3.6.6 started.
  Copyright Andrew Tridgell and the Samba Team 1992-2011
tail: error reading `/var/log/samba/cores': Is a directory
tail: /var/log/samba/cores: cannot follow end of this type of file; giving up on this name
[2014/06/25 15:08:45.824824,  0] printing/print_cups.c:110(cups_connect)
  Unable to connect to CUPS server localhost:631 - Connection refused
[2014/06/25 15:08:45.825246,  0] printing/print_cups.c:487(cups_async_callback)
  failed to retrieve printer list: NT_STATUS_UNSUCCESSFUL

**Comment by wglambert** [comment]
Issue is resolved, pruning
