### ISSUE TITLE
Can't access exposed port

### ISSUE THREAD

**Issue by Integralist** [boot2docker/boot2docker#412]
I'm playing around with Docker using Boot2Docker and am trying to access a Sinatra Ruby  web application which normally would be available at http://localhost:4567/ but is not possible since being run inside a Docker container handled by Boot2Docker.

The process for building my image is as follows (also all code can be found here: https://github.com/Integralist/Docker-Examples/tree/master/Sinatra/src):

```
docker build -t integralist/sinatra:v3 .
docker images
docker run -p 49161:4567 -d integralist/sinatra:v3
```

> Note: 49161 is just a random port number and I assume this isn't a problem?

If I run `docker ps` then I can see the following:

```
CONTAINER ID        IMAGE                    COMMAND             CREATED             STATUS              PORTS                     NAMES
9197e0fc7ad9        integralist/sinatra:v3   ruby /src/app.rb    x hours ago        Up x hours          0.0.0.0:49161->4567/tcp   tender_bartik 
```

If I run `docker logs {container_id}` then I can see the web server was run successfully:

```
[2014-06-27 22:37:30] INFO  WEBrick 1.3.1
[2014-06-27 22:37:30] INFO  ruby 1.9.3 (2013-11-22) [x86_64-linux]
== Sinatra/1.4.5 has taken the stage on 4567 for development with backup from WEBrick
[2014-06-27 22:37:30] INFO  WEBrick::HTTPServer#start: pid=1 port=4567
```

But running `curl -i $(boot2docker ip):49161` causes the following error:

```
The VM's Host only interface IP address is: 

curl: (7) Failed to connect to 192.168.59.105 port 49160: Connection refused
```

My Dockerfile looks like the following:

``` bash
FROM ubuntu:14.04
MAINTAINER Mark McDonnell <mark.mcdx@gmail.com>

RUN apt-get -qq update
RUN apt-get -qqy install ruby ruby-dev
RUN gem install sinatra

ADD . /src

RUN cd /src

EXPOSE 4567

ENTRYPOINT ["ruby", "/src/app.rb"]
```

Looking at the FAQ it would suggest that I shouldn't need to do anything and that port forwarding (e.g. any exposed ports in the Docker container should be available via the ip provided by `boot2docker ip`) https://github.com/boot2docker/boot2docker#container-port-redirection but that doesn't appear to be the case here (as I've demonstrated above).

Can anyone advise what the solution is to this problem.

**Comment by qguv** [comment]
Googlers: If you're using the Docker Toolbox on OS X, you'll need to use the VM's IP and not localhost.

```bash
open "http://$(docker-machine ip default):3000/"
```

If you've changed the VM name, change "default" above to the new name.

On OS X, Docker actually spins up a Linux VM to act as the docker host machine. When you expose a port from the container, you're actually exposing it to the Linux VM rather than to OS X, so you need to visit the Linux VM's IP to connect to the container inside.

**Comment by jbatte47** [comment]
@qguv : Brilliant, you've fixed my issue. Thanks!

**Comment by dirkjan111** [comment]
@qguv : THANKS!

**Comment by chenrui333** [comment]
@qguv Thanks for this important comment. Thought it should be documented some where! Took me so long to find this useful one.

**Comment by mmahalwy** [comment]
@qguv thanks! This worked! Any idea how to make it work in the OSX versus just the VM? 

Thanks!

**Comment by qguv** [comment]
@mmahalwy: I'm not sure what you mean. Docker in OS X runs in a Linux VM because OS X (based on Darwin BSD) does not directly support lightweight Linux containers.

**Comment by huangtao800** [comment]
@qguv Thank you for point this out! Docker should include this in their tutorial. Otherwise it would be confusing to new starters.

**Comment by qguv** [comment]
I'm happy that people still find this useful!

@huangtao800: This is mentioned in [the boot2docker README](https://github.com/boot2docker/boot2docker#container-port-redirection) and [one of the more popular Docker tutorials](http://prakhar.me/docker-curriculum/#static-site) but not in the official, mainline Docker tutorial. You ought to [contact the Docker team](https://docs.docker.com/opensource/get-help/) to see if they'd be willing to clarify this in their official tutorial!

**Comment by equivalent** [comment]
I'm recommending hiding the Ruby app behind Nginx proxy server so you would map ruby app 4567 to port 80 of Nginx and then map 80 Nginx docker container to host 80

**Comment by wesleyvicthor** [comment]
does anyone knows why I always get connection refused even using the machine ip ?

**Comment by pmatias** [comment]
About @qguv's [comment about the host's ip](https://github.com/boot2docker/boot2docker/issues/412#issuecomment-145242855), it applies the same for the Windows version :)
