### ISSUE TITLE
Q: how can I share a directory in an OS X host to mount as a Docker volume?

### ISSUE THREAD

**Issue by jokeyrhyme** [boot2docker/boot2docker#413]
The [folder sharing instructions in the README.md](https://github.com/boot2docker/boot2docker#folder-sharing) suggest a "sharing outwards" approach: the files are in a Docker volume running a server, and the host connects to the server to access the files.

Is it possible to have this work in the opposite direction? In my use case, my Git credentials and code tools are all installed in the OS X host, as well as the projects I am working on. But I want to execute these projects in Docker containers via boot2docker. Is there a convenient way I can share host directories with boot2docker so that Docker can mount them as volumes?

For my development feedback loop, I don't want to have to rebuild Docker images every time I save a file. And it would be terrific if services running in containers (e.g. Jekyll, grunt-watch, etc) could be notified of file changes in the usual way.

Vagrant uses VirtualBox functionality to share a host folder with the guest VM. What I'm wondering about is that step between the guest VM and containers in the guest VM.

**Comment by Freyskeyd** [comment]
i'm facing very slow performance with symfony app with boot2docker due to `vboxsf` any idea if a solution exists to have a boot2docker with NFS or something?

**Comment by gansbrest** [comment]
Take a look at Hodor - https://github.com/gansbrest/hodor where we use Unison with monitoring for reliable and fast syncing.

**Comment by gansbrest** [comment]
You can build your iso with NFS or Samba, but it still be very slow with lot's of small files, trust me here. If you will decide to go this road I would advice against changing boot2docker.iso but running separate containers on top of it, so you can always use latest .iso version.

**Comment by Freyskeyd** [comment]
In performance side, what's the difference between a Samba server dockerized and a NFS boot2docker image?

**Comment by gansbrest** [comment]
NFS should work a bit faster especially on local interface. But it still
will be slow for reliable use for a big project with lots of files if you
will want to run some kind of files watcher on top of it (like nodemon). My
advice - don't do it, run away if you can. Or try Hodor.

**Comment by madamimadam** [comment]
Incidentally, the performance is amazingly variable. I have boot2docker set up on my MBP for dev work, and running our unit test suite varies between taking 6 to 8 minutes and taking 50 to 80 minutes. I have absolutely no insight into what the variability is caused by, and it is giving me absolute fits. If I copy all the files into the docker container, the tests take 5 minutes or so to run.

**Comment by evanworley** [comment]
+1 for file change events. I'm in a situation that sounds identical to @james-nesbitt in development. Works fine for me in Ubuntu, but I'm hoping to use boot2docker for the mac folks on my team, and one of the hopes would be that this alleviates the need for their build tools to poll.

**Comment by brikis98** [comment]
For folks still struggling with the performance of mounted folders and vboxsf, I put together a small open source project called [docker-osx-dev](https://github.com/brikis98/docker-osx-dev) that uses Vagrant + Docker + Rsync, and I'm seeing build performance with mounted folders that is on par with native performance and file watchers work correctly as well, without any need for polling. See [A productive development environment with Docker on OS X](http://www.ybrikman.com/writing/2015/05/19/docker-osx-dev/) for more info.

**Comment by pencilcheck** [comment]
+1 for docker-osx-dev, using it so far and it is fast and using a lot less CPU

**Comment by israelshirk** [comment]
Similar to @brikis98 docker-osx-dev, using Vagrant to simplify the setup a bit: https://github.com/yeti-support/docker-development-helper
