### ISSUE TITLE
Exit status 255

### ISSUE THREAD

**Issue by jastisatya** [boot2docker/boot2docker#426]
When i try to run start.sh 
i am getting exit status 255, after that nothing is happening

dirname: too many arguments
Try `dirname --help' for more information.
initializing...
2014/07/09 07:45:20 Virtual machine boot2docker-vm already exists
starting...
2014/07/09 07:45:21 Waiting for VM to be started...
.............................
2014/07/09 07:46:48 Started.
2014/07/09 07:46:49   Trying to get IP one more time
2014/07/09 07:48:07 exit status 255
2014/07/09 07:48:07 Docker client does not run on Windows for now. Please use
2014/07/09 07:48:07     "c:\Program Files\Boot2Docker for Windows\boot2docker.ex
e" ssh
2014/07/09 07:48:07 to SSH into the VM instead.
connecting...
2014/07/09 07:49:24 exit status 255

What does exist status 255 means?

**Comment by wglambert** [comment]
Issue seems resolved, going to prune
