### ISSUE TITLE
How to completely uninstall boot2docker?

### ISSUE THREAD

**Issue by ghost** [boot2docker/boot2docker#437]
I've been digging around the internets and I can't find any information on this.

Can someone please tell me how to uninstall boot2docker on osx?

**Comment by cimbriano** [comment]
Arrived at this thread when searching for a boot2docker uninstaller. I don't see anything on the OS X installation page referenced by sindhus about uninstalling and the installer 1.4.1 installer seems to go right into the installation.

I installed boot2docker via the installer before I realized there was a homebrew Formula. So now I'd like to uninstall and reinstall with homebrew. Any advice for a docker newbie?

**Comment by thaJeztah** [comment]
@cimbriano the boot2docker uninstaller for OS X can be found here; https://github.com/boot2docker/osx-installer/blob/master/uninstall.sh

However, (afaik) the installer is the preferred way to install boot2docker on OS X; The homebrew formula is not maintained by boot2docker itself and uses the boot2docker-cli ([see source](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/boot2docker.rb)) script which will be deprecated in the near future (see the [boot2docker-cli README](https://github.com/boot2docker/boot2docker-cli)).

So, unless you have a strong reason to use homebrew instead, I'd stick with the official installer.

Hope this helps!

**Comment by connaryscott** [comment]
i would like to start boot2docker from scratch.   After starting cisco anyconnect and frying it completely ( I understand that clugy routes can be applied, however, this is a mess especially when conveying it to others).  Looking for a decent reset here.

**Comment by michaelsbradleyjr** [comment]
@connaryscott [docker-machine](https://github.com/docker/machine) may be worth a look. I've found it to be a super-easy way to setup and teardown local boot2docker VMs:

```shellsession
docker-machine create -d virtualbox dev1
docker-machine create -d virtualbox dev2

docker-machine upgrade dev1
docker-machine rm dev2

# and so on... see: docker-machine help
```
When using the `virtualbox` driver, `docker-machine` uses (and automatically downloads) the boot2docker iso. I much prefer working with boot2docker in this way as I don't have to think about the particulars of installing, removing or upgrading it.

I cooked up some aliases and a bash function for simple toggling of the "active" machine and its `DOCKER_...` env variables:

https://gist.github.com/michaelsbradleyjr/b179ca7e92838d7f08a1#file-bash_aliases-sh-L19

**Comment by connaryscott** [comment]
Thanks for the tip will investigate...

**Comment by patrickaroo** [comment]
+1
