### ISSUE TITLE
Yosemite returning too many redirects when pulling new image

### ISSUE THREAD

**Issue by josephwinston** [boot2docker/boot2docker#451]
Running 10.10 and boot2docker v1.1.2:

```
$ docker run learn/tutorial /bin/echo "Hello"
Unable to find image 'learn/tutorial' locally
Pulling repository learn/tutorial
8dbd9e392a96: Error pulling image (latest) from learn/tutorial, endpoint: https://cdn-registry-1.docker.io/v1/, Get https://cdn-regi8dbd9e392a96: Error pulling image (latest) from learn/tutorial, Get https://cdn-registry-1.docker.io/v1/images/8dbd9e392a964056420e5d58ca5cc376ef18e2de93b5cc90e868a1bbc8318c1c/ancestry: dial tcp: lookup cdn-registry-1.docker.io on [10.0.2.3]:53: too many redirects2014/07/26 21:10:30 Error pulling image (latest) from learn/tutorial, Get https://cdn-registry-1.docker.io/v1/images/8dbd9e392a964056420e5d58ca5cc376ef18e2de93b5cc90e868a1bbc8318c1c/ancestry: dial tcp: lookup cdn-registry-1.docker.io on [10.0.2.3]:53: too many redirects
```

This seems to be close to https://github.com/coreos/coreos-vagrant/issues/124

**Comment by luebken** [comment]
+1

**Comment by marians** [comment]
`VBoxManage modifyvm boot2docker-vm --natdnsproxy1 off --natdnshostresolver1 off` seems to do the trick for me, too. Thanks @andyshinn!

**Comment by jamescarr** [comment]
Thanks @andyshinn, this worked for me as well!

**Comment by chriscohoat** [comment]
Thanks @andyshinn , works for me too.

**Comment by alph486** [comment]
@andyshinn works here, thanks!

**Comment by pmuntyanu** [comment]
@andyshinn, thank you.

**Comment by masarufuruya** [comment]
@andyshinn works here! thanks.

**Comment by krancour** [comment]
@andyshinn works great!  Thank you!

**Comment by davidgardner11** [comment]
@andyshinn -- brilliant. saved me

**Comment by sbuss** [comment]
The issue you're seeing is due to an underlying bug in virtualbox's DNS resolver. Please see https://github.com/docker/distribution/issues/1292 for more information.

**Comment by akauppi** [comment]
For me, this simply went away with `docker-machine stop default` and `docker-machine start default` (maybe a `docker-machine upgrade` in between). macOS 10.12.2, docker-machine 0.8.2

**Comment by tianon** [comment]
Closing, since this appears solved. :+1:
