### ISSUE TITLE
Can't pull a specific image

### ISSUE THREAD

**Issue by arabold** [boot2docker/boot2docker#462]
I'm running into pulling specific images from the Docker Hub in boot2docker. There's a [bug #6874](https://github.com/docker/docker/issues/6874) reported in Docker. However, it was suggested this might be an issue with boot2docker instead. Is somebody else experiencing the same problems?

I'm running in a "operation not supported" issue with a custom image I've created: [neroinc/golang](https://registry.hub.docker.com/u/neroinc/fedora-golang/)

I'm running docker in [boot2docker with VirtualBox Guest Additions](https://medium.com/boot2docker-lightweight-linux-for-docker/boot2docker-together-with-virtualbox-guest-additions-da1e3ab2465c) with the following command line:
`docker pull neroinc/fedora-golang`

```
Pulling repository neroinc/fedora-golang
0f754aeb0993: Error pulling image (latest) from neroinc/fedora-golang, operation not supported gistry-1.docker.io/v1/, operation not supported
c69cab00d6ef: Download complete
88b42ffd1f7c: Download complete
63797b0413ad: Error downloading dependent layers
2014/07/31 04:06:01 Error pulling image (latest) from neroinc/fedora-golang, operation not supported
```

docker info
```
Containers: 2
Images: 100
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Dirs: 104
Execution Driver: native-0.2
Kernel Version: 3.15.3-tinycore64
Debug mode (server): true
Debug mode (client): false
Fds: 17
Goroutines: 15
EventsListeners: 0
Init Path: /usr/local/bin/docker
Sockets: [unix:///var/run/docker.sock tcp://0.0.0.0:2375]
```

docker version
```
Client version: 1.1.2
Client API version: 1.13
Go version (client): go1.2.1
Git commit (client): d84a070
Server version: 1.1.2
Server API version: 1.13
Go version (server): go1.2.1
Git commit (server): d84a070
```

uname -a
```
Linux boot2docker 3.15.3-tinycore64 #1 SMP Thu Jul 24 03:10:37 UTC 2014 x86_64 GNU/Linux
```

`blkid -o value -s TYPE /dev/sda1` gives me `ext4`

If I build the neroinc/fedora-golang image locally, it will work without problems. It's the download from the hub which gives problems.

The same error happens when pulling `fedora/memcached` after downloading about 4.0 MB of e857e2460362: `e857e2460362: Downloading [========> ] 3.574 MB/22.14 MB 20s`

What can I do to fix this?

**Comment by tobegit3hub** [comment]
I have the same issues and thanks for fixing that :smiley:

**Comment by SvenDowideit** [comment]
yay, I'm glad it fixed it, I wasn't looking forward to tearing out more hair :)

I'm very much looking forward to trying overlayfs tho
