### ISSUE TITLE
Enable configuration of docker bridge

### ISSUE THREAD

**Issue by kmetsalu** [boot2docker/boot2docker#508]
I had an issue of local network also being 172.17.0.0 network. So when docker was using docker0 with ip 172.17.42.1 all containers where unable to contact local servers(something we needed).

I was able to get it working with:

```
boot2docker ssh
sudo ip link add docker1 type bridge
sudo ip addr add 192.168.1.1/24 dev docker1
sudo ip link set docker1 up
sudo kill -TERM `pidof docker`
sudo ip link set docker0 down
sudo /usr/local/bin/docker -d -D -g /var/lib/docker -b docker1 -H unix:// -H tcp://0.0.0.0:2375
```

But it all would be much easier if something like docker network option would be available for boot2docker.

**Comment by Vrakfall** [comment]
A question to the maintainers: Shouldn't it be written in the `doc` that docker is talking to the containers though the `docker0` interface ? Also, does `docker0` always have the ip `172.17.42.1` ?

I can propose a doc PR if needed.

**Comment by farvour** [comment]
There is a profile configuration that inherits command line settings from $EXTRA_ARGS into the docker command on boot.

``bash
echo EXTRA_ARGS="--bip=172.19.42.1/16" >> /var/lib/boot2docker/profile
``

Then restart your boot2docker instance with `boot2docker stop && boot2docker start`.
