### ISSUE TITLE
Enable symlinks on vboxsf

### ISSUE THREAD

**Issue by gaastonsr** [boot2docker/boot2docker#556]
Apparently in Virtual Box 4.1.8, creating symlinks using a guest-OS in a shared folder has been disabled for security reasons. (see http://superuser.com/a/446908/350056)

So people needed to issue

```
VBoxManage setextradata VM_NAME VBoxInternal2/SharedFoldersEnableSymlinksCreate/SHARE_NAME 1
```

to enable them again.

Vagrant faced the same problem (see https://github.com/mitchellh/vagrant/issues/713) and they enabled them by default (https://github.com/mitchellh/vagrant/commit/387692f9c8fa4031050646e2773b3d2d9b2c994e).

So I think we should do the same but I don't know where it goes... I tried to fix it myself. 

I found this problem trying to make a `npm install` in one of my shared folders and getting:

```
npm ERR! Error: EROFS, symlink '../jade/bin/jade'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
```

**Comment by haggen** [comment]
I'm having this issue with `1.7.0`.
