### ISSUE TITLE
Running $(boot2docker shellinit) is not possible anymore with v1.3.0

### ISSUE THREAD

**Issue by rodolfo42** [boot2docker/boot2docker#580]
Hey

Sorry if this is being resolved already, I just didn't find any related issues.

First of all, congrats to all on the `v1.3.0`, this was a very very useful release! :+1: 

However, I just noticed after updating that the `boot2docker shellinit` command now outputs some extra lines:

```
[~] boot2docker shellinit

Writing /Users/Rodolfo/.docker/boot2docker-vm/ca.pem:
Writing /Users/Rodolfo/.docker/boot2docker-vm/cert.pem:
Writing /Users/Rodolfo/.docker/boot2docker-vm/key.pem:
    export DOCKER_HOST=tcp://192.168.59.103:2376
    export DOCKER_CERT_PATH=/Users/Rodolfo/.docker/boot2docker-vm

[~]
```

So now I can't run `$(boot2docker shellinit)` anymore, and that's because it tries to execute that lines and it obviously fails. If this is intended, we should remove the related [line in the README.md](https://github.com/boot2docker/boot2docker/blob/master/README.md#container-port-redirection) that says to run that command (I could make the PR)

I'm curious as to how do you guys use that, do you just copy these `export` lines to your shell's initialization script? What if they change in the future?

I'm asking because I just use a `$(boot2docker shellinit)` line in my `.zshrc`

**Comment by naomik** [comment]
After opening a new shell, I ran

```sh
docker version
```

I got this output:

```plain
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): darwin/amd64
FATA[0000] Get http:///var/run/docker.sock/v1.18/version: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?
```

Wel that's no good ! Let's fix that up !

After doing a little research, I found I have to `export` the `DOCKER_HOST`, `DOCKER_CERT_PATH`, and `DOCKER_TLS_VERIFY` environment vars provided with `boot2docker shellinit`

----- 

:warning: :warning:  **If this is the wrong way to do this, please let me know !** :warning: :warning:

To get everything setup, I opened up my `.zshrc` file and added the following lines

```sh
# boot2docker
$(boot2docker shellinit 2> /dev/null)
```

The `2> /dev/null` bit prevents `shellinit` from dumping text on your screen every time you start a new terminal session.

To verify this works, I started a new shell session and I re-ran:

```sh
docker version
```

Now I get the correct output

```plain
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): darwin/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

Yay !

I hope this helps someone ^.^

**Comment by rossedman** [comment]
@naomik Thank you so much. Committed to my .dotfiles to keep my sanity in check. :+1:

**Comment by edmorley** [comment]
Note for several reasons (see #786), the ``$(boot2docker shellinit)`` form given above is no longer recommended - use ``eval "$(boot2docker shellinit)"`` instead. I'm going to try and make this change in recommendation more obvious, in boot2docker/boot2docker-cli#369.

(Commenting here since the issue was one I stumbled across several times whilst trying to find a solution, so hopefully this may help others who end up here too.)
