### ISSUE TITLE
Disabling TLS does no work

### ISSUE THREAD

**Issue by vrischmann** [boot2docker/boot2docker#589]
Hi,

I need to disable TLS because of a 3rd party app which connects to Docker without TLS support. I tried following the procedure in the README, but it's not working.

I added `DOCKER_TLS=no` to `/var/lib/boot2docker/profile`, but now when I restart the VM with `boot2docker restart` docker doesn't run anymore. This is what I can find in the file `/var/log/docker.log`:

/usr/local/bin/docker -d -D -g "/var/lib/docker" -H unix:// -H tcp://0.0.0.0:2375  no --tlscacert=/var/lib/boot2docker/tls/ca.pem --tlscert=/var/lib/boot2docker/tls/server.pem --tlskey=/var/lib/boot2dock
er/tls/serverkey.pem >> "/var/lib/boot2docker/docker.log"
Usage: docker [OPTIONS] COMMAND [arg...]`

Clearly it's wrong, maybe the README isn't up to date ?

**Comment by heph** [comment]
In case anyone else comes across this, use 'export' in the profile:
```bash
export DOCKER_TLS=no
```
