### ISSUE TITLE
Does "mount -t vboxsf" work on windows?

### ISSUE THREAD

**Issue by flyisland** [boot2docker/boot2docker#611]
env: boot2docker: 1.3.0 on Windows 7 sp1

The user guide says that we could `$ mount -t vboxsf -o uid=1000,gid=50 your-other-share-name /some/mount/location` to share folder between laptop and the vm. But it doesn't work on my Win7

```
docker@boot2docker:/$ sudo mkdir /ramdisk
docker@boot2docker:/$ sudo mount -t vboxsf -o uid=1000,gid=50 R:/ ramdisk
mount.vboxsf: mounting failed with the error: Protocol error
mount: mounting R:/ on ramdisk failed: Protocol error
```

**Comment by dlaberge** [comment]
@tianon is there a tutorial on how to setup the share in VirtualBox ?
