### ISSUE TITLE
Cannot up docker from OSX

### ISSUE THREAD

**Issue by kobayashi** [boot2docker/boot2docker#612]
I'm trying boot2docker in my MBA.
When I run dockerVM, following message appear.
"error in run: Failed to initialize machine "boot2docker-vm": exit status 1"
How could I correct this issue?

I did following steps.
- brew tap homebrew/binary
- brew install boot2docker docker
- boot2docker init

Virtualbox version is
% VBoxManage -v  
4.3.18r96516

detail logs:
% boot2docker up -v  
Boot2Docker-cli version: v1.3.0
Git commit: deafc19
2014/11/01 21:24:42 executing: VBoxManage showvminfo boot2docker-vm --machinereadable
2014/11/01 21:24:42 executing: VBoxManage guestproperty set boot2docker-vm /VirtualBox/GuestAdd/SharedFolders/MountPrefix /
2014/11/01 21:24:42 executing: VBoxManage guestproperty set boot2docker-vm /VirtualBox/GuestAdd/SharedFolders/MountDir /
2014/11/01 21:24:42 executing: VBoxManage sharedfolder add boot2docker-vm --name Users --hostpath /Users --automount
VBoxManage: error: Shared folder named 'Users' already exists
VBoxManage: error: Details: code VBOX_E_OBJECT_IN_USE (0x80bb000c), component SessionMachine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "CreateSharedFolder(Bstr(name).raw(), Bstr(hostpath).raw(), fWritable, fAutoMount)" at line 1009 of file VBoxManageMisc.cpp
2014/11/01 21:24:43 executing: VBoxManage setextradata boot2docker-vm VBoxInternal2/SharedFoldersEnableSymlinksCreate/Users 1
2014/11/01 21:24:43 executing: VBoxManage startvm boot2docker-vm --type headless
Waiting for VM "boot2docker-vm" to power on...
VBoxManage: error: The virtual machine 'boot2docker-vm' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component Machine, interface IMachine
2014/11/01 21:24:43 executing: VBoxManage showvminfo boot2docker-vm --machinereadable
error in run: Failed to start machine "boot2docker-vm" (run again with -v for details)

**Comment by jamshid** [comment]
I also was getting `VBoxManage: error: Shared folder named 'Users' already exists` on `boot2docker start -v`, and `VirtualBoxStartup.sh restart` did not help (see below).

Reinstalling virtualbox fixed it without having to recreate my boot2docker image. I think the real problem was that I somehow lost my "Host only" network adapter. 

Other tips: if you're messing with forwarding ports, make sure the virtual box gui Network tab is not open -- that seems to prevent `vboxmange` changes. Also, check your port forwarding and make sure there is no bogus rule forwarding port 0 -- I think that was causing strange problems.

```
$  sudo /Library/Application\ Support/VirtualBox/LaunchDaemons/VirtualBoxStartup.sh restart
Password:
Unloading VBoxNetFlt.kext
(kernel) Kext org.virtualbox.kext.VBoxNetFlt did not stop (return code 0x5).
(kernel) Kext org.virtualbox.kext.VBoxNetFlt can't unload - module stop returned 0xdc008017.
Failed to unload org.virtualbox.kext.VBoxNetFlt - (libkern/kext) kext (kmod) start/stop routine failed.
Error: Failed to unload VBoxNetFlt.kext
Unloading VBoxDrv.kext
(kernel) Can't remove kext org.virtualbox.kext.VBoxDrv; services failed to terminate - 0xdc008018.
Failed to unload org.virtualbox.kext.VBoxDrv - (libkern/kext) kext is in use or retained (cannot unload).
Error: Failed to unload VBoxDrv.kext
Fatal error: VirtualBox
```

**Comment by mwhooker** [comment]
I was getting this error. I had to run `sudo kextunload -b org.virtualbox.kext.VBoxDrv`

and then I ran into the error listed in #63. repasting my solution here:

> I was running in to this error. Eventually it turned out that /Applications was owned by the incorrect user somehow. Try making sure it's owned by root. see https://forums.virtualbox.org/viewtopic.php?f=7&t=39179
