### ISSUE TITLE
boot2docker tcp i/o timeout on mac os

### ISSUE THREAD

**Issue by nikhilbhardwaj** [boot2docker/boot2docker#619]
Please see http://stackoverflow.com/questions/26686358/docker-cant-connect-to-boot2docker-because-of-tcp-timeout.
Also I'm not the only one facing this issue.

**Comment by mrjcleaver** [comment]
Which answer did you use, @nikhilbhardwaj ?

**Comment by mrjcleaver** [comment]
Looks like https://github.com/docker/machine/issues/986 may be the cause.

**Comment by nikhilbhardwaj** [comment]
The accepted answer by `treehau5` worked for me.
