### ISSUE TITLE
node app running incredibly slow

### ISSUE THREAD

**Issue by allthetime** [boot2docker/boot2docker#632]
I have a very simple test app that uploads 3 photos to s3, and then downloads them and displays them.

Normally the page/server boots up in about 3 seconds with npm start on OSX. Using boot2docker and a docker container set up to run the app the server takes about 1 minute to start and once it finally loads, making the requests to S3 takes about 10 seconds. This seems ridiculous to me, and is completely unusable for development. 

I don't have the app included in the docker image. I am mounting it with docker run -v, this shouldn't make a considerable difference should it?

**Comment by tnrich** [comment]
Hey there @thaJeztah, 
I was wondering if you know if this issue has been solved with Docker Beta for mac, or if it is still facing the same underlying issues?

**Comment by thaJeztah** [comment]
Why don't you give it a try? https://beta.docker.com - you can install it next to boot2docker / VirtualBox, so nothing lost. You need an invite code, but last I heard, those are arriving pretty quick after you registered now

**Comment by tnrich** [comment]
Hey @thaJeztah , I actually am already using it! It seems to work slightly better than boot2docker, but it still goes very slowly for me and I was hoping it would be a lot faster.. Do you know of any tricks that would work for Docker For Mac Beta to speed things up?

**Comment by thaJeztah** [comment]
Hm, not sure if there's ways to "speed it up", but I know they're still working on improvements. if you have more information about your exact use case (e.g. Number of files, exactly what is slow), probably best to post on the Docker for Mac beta forum

**Comment by tnrich** [comment]
Here is a link to a discussion about Docker For Mac Beta:
https://forums.docker.com/t/file-access-in-mounted-volumes-extremely-slow-cpu-bound/8076/33?u=davetucker
