### ISSUE TITLE
To install boot2docker on a 32bit Windows PC

### ISSUE THREAD

**Issue by Suikerspin** [boot2docker/boot2docker#644]
I need to install boot2docker on a 32bit windows pc. 
How can I do this. 
The current  docker-install.exe for Windows is for a 64bit. 
My developers skills are very basic so a simple approach will be appreciated.

**Comment by Govindarj** [comment]
Anyone tell me how to install docker in windows 7 32bit????? Thanks in advance

**Comment by david756** [comment]
i have the same problem

**Comment by parths049** [comment]
I have same problem

**Comment by iamvasim786** [comment]
How to install docker toolbox in win 32-bit OS ?

**Comment by datorse** [comment]
Check https://thesocietea.org/2016/04/installing-the-docker-client-cli-on-32-bit-windows/
