### ISSUE TITLE
FATA [0000] 

### ISSUE THREAD

**Issue by senecahinds** [boot2docker/boot2docker#672]
FATA[0000] Get http:///var/run/docker.sock/v1.16/info: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS? 

this is what i get after i enter sudo docker info on the command line ...

**Comment by pcj** [comment]
I have run into this issue without sudo on osx.  `$(boot2docker shellinit)` seems to fox the issue.  

(If only my `docker push ...` commands would succeed.  Makes the docker.com private repos unusable).

**Comment by dioxys** [comment]
Getting the same error when running boot2docker from the applications folder for the first time.

**Comment by markseddon** [comment]
I also just installed boot2docker as a fresh install on Yosemite 10.10.2

```
➜ boot2docker version
Boot2Docker-cli version: v1.5.0
Git commit: ccd9032
```

```
➜  docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): darwin/amd64
FATA[0000] Get http://192.168.59.103:2375/v1.17/version: dial tcp 192.168.59.103:2375: no route to host. Are you trying to connect to a TLS-enabled daemon without TLS?
```

**Comment by SvenDowideit** [comment]
@markseddon you should see 3 settings when you run `env | grep DOCKER`. If you don't, then run `$(boot2docker shellinit)`

**Comment by markseddon** [comment]
No dice

```
➜  docker  $(boot2docker shellinit)
➜  docker  docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): darwin/amd64
FATA[0000] Get http://192.168.59.103:2375/v1.17/version: dial tcp 192.168.59.103:2375: host is down. Are you trying to connect to a TLS-enabled daemon without TLS?
➜  docker  env | grep DOCKER
DOCKER_HOST=tcp://192.168.59.103:2375
DOCKER_CERT_PATH=
DOCKER_TLS_VERIFY=
```

**Comment by SvenDowideit** [comment]
That looks suspicious - boot2docker 1.3 uses port 2376 - which makes me wonder if your boot2docker.iso is out of date.

what happens if you 
- `boot2docker delete` 
- `boot2docker download` 
- `boot2docker init` 
- `boot2docker start` 

?

**Comment by markseddon** [comment]
Sorry to be a pain...but still not working. 

```
➜  ~  boot2docker delete
➜  ~  boot2docker download
Latest release for boot2docker/boot2docker is v1.5.0
Downloading boot2docker ISO image...
Success: downloaded https://github.com/boot2docker/boot2docker/releases/download/v1.5.0/boot2docker.iso
	to /Users/mark/.boot2docker/boot2docker.iso
➜  ~  boot2docker init
➜  ~  boot2docker start
Waiting for VM and Docker daemon to start...
........................oooooooooooooooooooo
Started.
Writing /Users/mark/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Users/mark/.boot2docker/certs/boot2docker-vm/cert.pem
Writing /Users/mark/.boot2docker/certs/boot2docker-vm/key.pem

To connect the Docker client to the Docker daemon, please set:
    export DOCKER_HOST=tcp://192.168.59.105:2376
    export DOCKER_CERT_PATH=/Users/mark/.boot2docker/certs/boot2docker-vm
    export DOCKER_TLS_VERIFY=1

➜  ~  docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): darwin/amd64
FATA[0032] An error occurred trying to connect: Get https://192.168.59.104:2376/v1.17/version: dial tcp 192.168.59.104:2376: i/o timeout
```

I've checked the info

```
➜  ~  boot2docker info
{
	"Name": "boot2docker-vm",
	"UUID": "2533c67b-ec19-4240-a26d-f1fb81d1bc8a",
	"Iso": "/Users/mark/.boot2docker/boot2docker.iso",
	"State": "running",
	"CPUs": 4,
	"Memory": 2048,
	"VRAM": 8,
	"CfgFile": "/Users/mark/VirtualBox VMs/boot2docker-vm/boot2docker-vm.vbox",
	"BaseFolder": "/Users/mark/VirtualBox VMs/boot2docker-vm",
	"OSType": "",
	"Flag": 0,
	"BootOrder": null,
	"DockerPort": 0,
	"SSHPort": 2022,
	"SerialFile": "/Users/mark/.boot2docker/boot2docker-vm.sock"
}%
```
and it looks like it's using the correct ISO image

**Comment by thaJeztah** [comment]
Looks like you forgot to set the environment-variables, as instructed in the output of `boot2docker start`;

```
To connect the Docker client to the Docker daemon, please set:
    export DOCKER_HOST=tcp://192.168.59.105:2376
    export DOCKER_CERT_PATH=/Users/mark/.boot2docker/certs/boot2docker-vm
    export DOCKER_TLS_VERIFY=1
```

According to that, the DOCKER_HOST is at `192.168.59.105:2376`, but because you didn't set the environment-variables, the client is trying to connect to `192.168.59.104:2376`;

    FATA[0032] An error occurred trying to connect: Get https://192.168.59.104:2376/v1.17/version: dial tcp 192.168.59.104:2376: i/o timeout

**Comment by SvenDowideit** [comment]
y - you definitely need to run `$(boot2docker) shellinit)` before you run `docker version`

**Comment by markseddon** [comment]
Right that didn't work either so I deleted everything by using the uninstall script found [here](https://github.com/boot2docker/osx-installer/blob/master/uninstall.sh) then removed the app from /Applications. 

I then reinstalled using the latest package and everything is now working OK.

Thanks for your help though, much appreciated!

**Comment by thaJeztah** [comment]
Thanks for reporting back, @markseddon, glad you got it working.

@senecahinds are you still having this problem or can this issue be closed?

**Comment by mwlind** [comment]
Hi All
I hit same issue as @markseddon did with same 10.10.2
After running "$ boot2docker shellinit", DOCKER_*  env variables took no effect.

MBA:~ mwlind$ boot2docker shellinit
Writing /Users/mwlind/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Users/mwlind/.boot2docker/certs/boot2docker-vm/cert.pem
Writing /Users/mwlind/.boot2docker/certs/boot2docker-vm/key.pem
    export DOCKER_HOST=tcp://192.168.59.103:2376
    export DOCKER_CERT_PATH=/Users/mwlind/.boot2docker/certs/boot2docker-vm
    export DOCKER_TLS_VERIFY=1
MBA:~ mwlind$ env |grep DOCKER
MBA:~ mwlind$

So manually export it as below, it's fixed in my env.
MBA:~ mwlind$ export DOCKER_HOST=tcp://192.168.59.103:2376
MBA:~ mwlind$ export DOCKER_CERT_PATH=/Users/mwlind/.boot2docker/certs/boot2docker-vm
MBA:~ mwlind$ export DOCKER_TLS_VERIFY=1
MBA:~ mwlind$ env |grep DOCKER
DOCKER_HOST=tcp://192.168.59.103:2376
DOCKER_TLS_VERIFY=1
DOCKER_CERT_PATH=/Users/mwlind/.boot2docker/certs/boot2docker-vm

MBA:~ mwlind$ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): darwin/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

**Comment by SvenDowideit** [comment]
Heya @mwlind you need to run `$(boot2docker shellinit)` - the `$(...)` is part of the command - this causes the strings you see in your above screenshot to be executed in your current shell.

**Comment by ericandrewlewis** [comment]
Should the responsibility of setting environment-variables be on the user? 

Can boot2docker handle this in a way that doesn't expose docker users to a config layer that they may not need to know about?

**Comment by senecahinds** [comment]
thanks for your reply I have it working

**Comment by rwatts3** [comment]
I agree, this is something that needs to be handled by boot2docker. It makes no sense that you run commands, and there is no documentation on these environment variables. 
It is also pointless to have to set export on each item every time I start boot2docker

**Comment by thaJeztah** [comment]
@rwatts3 it's better to open a separate issue for that; but check if one exists first (there may be an existing issue already).

You may be interested in Docker Machine, which will eventually replace the Boot2Docker tools, and the documentation for Docker Machine already has a better description of the environment variables; https://docs.docker.com/machine/. The links for providing feedback on Docker Machine can be found here; https://docs.docker.com/machine/#getting-help
