### ISSUE TITLE
boot2docker can't init because of my network connection

### ISSUE THREAD

**Issue by HughGrant** [boot2docker/boot2docker#679]
it will stuck forever at here.

```
boot2docker init
Latest release for boot2docker/boot2docker is v1.4.1
Downloading boot2docker ISO image...
error in run: Failed to download ISO image: read tcp 54.231.2.144:443: operation timed out
```

But I have shadowsocks on my mac, so is there a way to set proxy?
My proxy address is **localhost:1080**
Also it says operation timed out, so is there a way to set the operation time longer? maybe this could fix the problem?
How can I see the download progress bar or something indicates the download progress?
Any suggestion is much appreciated.

**Comment by pstinghua** [comment]
+1

**Comment by zhkucyb** [comment]
你可以参考下面这篇文章，把shell中的http请求转发到shadowsocks监听的端口。
http://1992s.com/blog/share-shadowsocks-over-lan-on-mac-os-x.html
