### ISSUE TITLE
can't connect to the site - connection refused

### ISSUE THREAD

**Issue by dyatlov** [boot2docker/boot2docker#685]
I know it's old problem..

MBP-Vitaly:dock dyatlov$ `fig ps`
      Name             Command             State              Ports       
-------------------------------------------------------------------------
dock_db_1          /docker-           Up                 0.0.0.0:49157->5 
                   entrypoint.sh                         432/tcp          
                   postgres                                               
dock_web_1         bundle exec        Up                 0.0.0.0:3000->30 
                   rackup -p 3000                        00/tcp           
MBP-Vitaly:dock dyatlov$ `boot2docker ip`
192.168.59.103
MBP-Vitaly:dock dyatlov$ `fig port web 3000`
0.0.0.0:3000
MBP-Vitaly:dock dyatlov$ `curl 192.168.59.103:3000`
curl: (7) Failed to connect to 192.168.59.103 port 3000: Connection refused

Im running latest virtual box and latest boot2docker (installed just 2day)
any idea how to solve this without virtual box cli and port forwarding?

**Comment by dyatlov** [comment]
to add, I tried to use it as described here: http://viget.com/extend/how-to-use-docker-on-os-x-the-missing-guide
but it seems that behavior changed since then?

**Comment by dyatlov** [comment]
rails was listening to localhost, solved this by adding `-b 0.0.0.0` to the start command: `bundle exec rails s -b 0.0.0.0`
now all is working. Sorry for false alarm

**Comment by arun057** [comment]
Whoa this needs more attention!

**Comment by williscool** [comment]
@dyatlov thanks so much. I feel silly for not thinking of that earlier :/
