### ISSUE TITLE
VM / wrong date time

### ISSUE THREAD

**Issue by aheissenberger** [boot2docker/boot2docker#69]
Host System is OSX:
OSX (Host): Fr 10 Jan 2014 04:42:26 CET
VM (Tiny Core Linux): Fri Jan 10 04:41:13 UTC 2014

to fix this you need to set this FLAG for virtual box:
--rtcuseutc on  // This option lets the real-time clock (RTC) operate in UTC time

**Comment by erikprice** [comment]
@brdloush Does #661 fix this for you?

**Comment by aral** [comment]
Hi Erik, I can confirm that #661 does *not* fix this for me. Current time on OS X 23 Jan, 9:08 AM. In the container 23 Jan, 6:22 AM. Running with release 1.4.1.

**Comment by erikprice** [comment]
Same here @aral. In the meantime I've been using this convenience wrapper: https://github.com/beechnut/boot2docker-ntp

**Comment by muneeb-ali** [comment]
+1 to @aral, having the same issue and need to run 

> /usr/local/bin/boot2docker ssh sudo ntpclient -s -h pool.ntp.org

**Comment by gregholland** [comment]
Same issue here, when I sleep my mac and wake it up the next morning the b2d clock does not update.
