### ISSUE TITLE
How to forward Android (USB) device to container?

### ISSUE THREAD

**Issue by mauvm** [boot2docker/boot2docker#707]
I'm building an Android app in a container using the Android SDK and Cordova, but can't get the device forwarding to work. I haven't the slighest idea how to forward the Android device connection from my Mac OS X to the container itself.

I think the problem lies in the missing device descriptor (in `/dev`), since Mac OS X does not make them but uses the IOKit Registry instead (which I read about on http://stackoverflow.com/a/11787544/1453912).

Anyone who can help me out here? I'm unexperienced with device descriptors, mounting, etc. in Mac OS X.

**Comment by RomanSaveljev** [comment]
You need to capture your usb device into virtual machine. Please look up virtualbox usb filtering. Then when you start a container you use --privileged flag and map /dev/bus/usb as a volume.

**Comment by tiborvass** [comment]
Little correction on what @RomanSaveljev said: instead of using --privileged + bind mount, you should be able to simply do `--device=/dev/bus/usb:/dev/bus/usb:rwm`.

**Comment by mauvm** [comment]
Thanks for the quick response! I have tried both before, but without any luck.. Does boot2docker forward the USB devices automatically to the `boot2docker-vm`? When checking the VirtualBox configuration of the VM, under Ports > USB, "Enable USB controller" is disabled.

I hadn't tried the device param with `:rwm` before, but that also doesn't seem to work..

**Comment by tiborvass** [comment]
@mauvm before doing anything with Docker you'll need to forward the USB device into the VM. Boot2docker does not do that automatically as far as i know.

You should be able to modify the VM settings in VirtualBox's UI, if you stop the VM. But if you want it to be scriptable, you should use VBoxManage.

**Comment by mauvm** [comment]
Thanks! I have installed the VirtualBox extension pack, relaunched the VirtualBox daemon, rebuild the `boot2docker-vm`, turned on the USB and USB 2.0 (EHCI) controllers, and added the filter:

    VBoxManage usbfilter add 0 --target boot2docker-vm --name 'Android Device Filter' --product "Android Phone" --action hold

Finally I have tried both `-v /dev/bus/usb:/dev/bus/usb` and `--device=/dev/bus/usb:/dev/bus/usb:rwm`. The first one mounts OK, and makes `/dev/bus/usb/{001,002}/001` available to the container. The latter gives an error:

    FATA[0000] Error response from daemon: Cannot start container 4cfd924d09e399e915345389405d051fe243c00108620d810f66d3957fd0c105: error gathering device information while adding custom device "/dev/bus/usb": not a device node

When the `boot2docker-vm` is running `VBoxManage list usbhost` does not show my Android phone, while if it's turned off, it does get listed. Could this be a conflict between the host and VM?

**Comment by SvenDowideit** [comment]
yes, it could - I'd use the vbox GUI to test - including starting the b2d virtual machine from the GUI, and then using the GUI to attach the USB device.

**Comment by jonbjo** [comment]
Did you manage to solve this? I am also trying to the same thing, plug my Android device into my Macbook and forward the device to my Docker container so that I can launch the app from Cordova on my Android device using cordova run android.

**Comment by mauvm** [comment]
@jonbjo Nope, but haven't tried the suggestion from @SvenDowideit though.

**Comment by jonbjo** [comment]
@mauvm I managed to get it to work by basically following the steps above. The only difference is that I added the usbfilter in Virtualbox's GUI. It listed the connected devices and automatically created a filter for me that works. The settings in the filter automatically created seems to be a lot more specific than what you have in your VBoxManage string. Don't know if that makes a difference, but maybe. I also had to connect the device after starting Boot2Docker to be able to authorise the device. Now when I run "cordova run" in my Docker container it builds and deploys to my Nexus 5 connected to my MacBook. I have a sample Dockerfile at https://github.com/wisobi/leanbean/tree/master/leanbean-docker if that helps.

**Comment by mauvm** [comment]
@jonbjo Thanks. Will definitely check it out!

**Comment by suchja** [comment]
Did you get this working with the `--device=/dev/bus/usb:/dev/bus/usb:rwm`option on docker run? For me this works fine when using `-v /dev/bus/usb:/dev/bus/usb`and privileged, but it does not work with the device option. I had a look into the Dockerfile from jonbjo and it seems he is not using the `--device` option as well.
Any ideas why the suggested `--device` option does not work?

**Comment by mauvm** [comment]
@suchja No, both of them didn't seem to work. Are you also on Mac OS X? I don't think the problem lies in the Boot2Docker > Docker container part. Purely the Mac OS X > Boot2Docker device mounting part.

**Comment by suchja** [comment]
@mauvm Yes, Mac OS X here as well. Okay, that's wired. After establishing the device filter via the GUI it works well for me except for the `--device` part. Do you know of any information how to debug this issue?

**Comment by mauvm** [comment]
@suchja Sorry, but no. Why not keep using the `-v`? Because hey, at the end of the day it simply works!

**Comment by jonbjo** [comment]
I didn't get --device to work either. I think I read somewhere an explanation to why one should use privileged for USB devices, but if I did, I can't find back to that explanation. But at least for me it works with Mac OS X, Boot2Docker and --privileged.

**Comment by felixbanguera** [comment]
If this issue is still happening to someone nowadays on Mac OS X, I fixed it installing the extension package for Virtual box, and then going to >>settings>>ports>>usb and enabling the connection. After that it worked like a charm.

**Comment by kenyee** [comment]
FYI, this doesn't work if you use Docker 1.12 any more because it uses the OSX Hypervisor instead of Virtualbox :-(

**Comment by suchja** [comment]
@kenyee have you found any other way to get it working?

**Comment by kenyee** [comment]
@suchja : nope....AFAIK, the hypervisor doesn't support USB port access.  I'm going back to using an older version of docker so I can run it inside virtual box on the Mac.  What's annoying is it doesn't work on a Windows machine either....HAXM is incompatible w/ Hyper-V and Virtualbox, so again, you're stuck w/ the old version of Docker 1.11 that runs inside Virtualbox.

**Comment by suchja** [comment]
Thanks for clarification!

**Comment by yosifkit** [comment]
If you are using Docker Toolbox to install Docker on OSX/Windows then it will be the most up to date docker (1.12) and use VirtualBox.  The only time you will not be using VirtualBox is when you are using Docker for Mac and Docker for Windows which do not even use the boot2docker project.

**Comment by Manouchehri** [comment]
In VMware Workstation/Fusion, this can be done by adjusting adding `usb.autoConnect.device0 = "0x1234:0x1234"` to the VMX.
