### ISSUE TITLE
Can't connect/run boot2docker

### ISSUE THREAD

**Issue by doron2402** [boot2docker/boot2docker#711]
Hi I'm running:
Yosemite/10.10.1
Virtual box: 4.3.20

When running  `boot2docker up` 
->
```Waiting for VM and Docker daemon to start...
..........................................................................oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
Started.
  Trying to get Docker socket one more time
Error requesting socket: exit status 255
Auto detection of the VM's Docker socket failed.
Please run `boot2docker -v up` to diagnose.
```
Then I'm running : `boot2docker -v up`
->
at first I get this: 
Waiting for VM and Docker daemon to start...
.Connecting to tcp://localhost:2022 (attempt #0).Connecting to tcp://localhost:2022 (attempt #0).Connecting to tcp://localhost:2022 (attempt #0).Connecting to tcp://localhost:2022 (attempt #0).Connecting to tcp://localhost:2022

later on I get this

o2015/01/23 16:26:05 executing: /usr/bin/ssh ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -p 2022 -i /Users/dsegal/.ssh/id_boot2docker docker@localhost grep tcp:// /proc/$(cat /var/run/docker.pid)/cmdline
Error requesting socket: exit status 255
o2015/01/23 16:26:05 executing: /usr/bin/ssh ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -p 2022 -i /Users/dsegal/.ssh/id_boot2docker docker@localhost grep tcp:// /proc/$(cat /var/run/docker.pid)/cmdline
Error requesting socket: exit status 255

Started.
  Trying to get Docker socket one more time
2015/01/23 16:26:06 executing: /usr/bin/ssh ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -p 2022 -i /Users/dsegal/.ssh/id_boot2docker docker@localhost grep tcp:// /proc/$(cat /var/run/docker.pid)/cmdline
Error requesting socket: exit status 255
2015/01/23 16:26:06 executing: /usr/bin/ssh ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -p 2022 -i /Users/dsegal/.ssh/id_boot2docker docker@localhost tar c /home/docker/.docker/*.pem
Auto detection of the VM's Docker socket failed.

I've setup my bash_profile
``
   export DOCKER_HOST=tcp://192.168.59.103:2376
# export DOCKER_HOST=tcp://127.0.0.1:2376
    export DOCKER_CERT_PATH=/Users/dsegal/.boot2docker/certs/boot2docker-vm
    export DOCKER_TLS_VERIFY=1
``

**Comment by doron2402** [comment]
I think its also related when running `docker`

FATA[0000] Couldn't read ca cert /Users/dsegal/.boot2docker/certs/boot2docker-vm/ca.pem: open /Users/dsegal/.boot2docker/certs/boot2docker-vm/ca.pem: no such file or directory  

seems like I'm missing the ssh keys

**Comment by doron2402** [comment]
one last thing, when running boot2docker ssh
-> 
error in run: exit status 255

**Comment by RomanSaveljev** [comment]
I usually experience the same when trying to up from vm's aborted state. Seems like it gets corrupted easily. Would be nice to have cli print some meaningful message suggesting to re-do the vm

**Comment by doron2402** [comment]
@RomanSaveljev yeah I've try to reinstall it after removing the vm but still getting same issue

**Comment by doron2402** [comment]
for some reason boot2docker is not creating this directory on my machine 

.boot2docker/certs/...

**Comment by doron2402** [comment]
Fix:

1. locate boot2docker - remove every file related to it.
2. restart mac.
3. re-install from the site (don't use the brew version, not sure if its related but its works for me and I'm not going to investigate it further )
4. boot2docker init, ...

works!

**Comment by alej0varas** [comment]
For me this worked:

    $ boot2docker remove
    $ boot2docker init
    $ boot2docker up

**Comment by oloo** [comment]
@alej0varas i think you meant
$ boot2docker delete and not $boot2docker remove

otherwise it worked perfectly for me

**Comment by thieman** [comment]
Deleting the entire VM is disruptive and is not an acceptable solution to this problem. This issue should be re-opened.
