### ISSUE TITLE
$(boot2docker shellinit) frequently fails (OSX)

### ISSUE THREAD

**Issue by skozin** [boot2docker/boot2docker#716]
Running

```bash
$(boot2docker shellinit)
```

frequently (but not always) produces this error:

```
-bash: unset: `DOCKER_HOST=tcp://192.168.59.103:2375': not a valid identifier
```

As a result, `DOCKER_HOST` is not getting set to the desired value. The output of `boot2docker shellinit` is the following:

```bash
$ boot2docker shellinit
    export DOCKER_HOST=tcp://192.168.59.103:2375
    unset DOCKER_CERT_PATH
    unset DOCKER_TLS_VERIFY
```

These commands produce no errors when executed directly (by pasting into the command line). I am not sure why command substitution fails.

boot2docker v1.4.1 (Git commit: 43241cb) is installed on OSX 10.10 with GNU Bash 4.3.30(1)-release (x86_64-apple-darwin14.0.0).

This issue seems to be different from #715, as none of my boot2docker-related paths contain whitespace (and there are no paths at all in the `shellinit`-generated output).

**UPD**: I just discovered that `boot2docker shellinit` sometimes produces commands in a different order:

```bash
$ boot2docker shellinit
    unset DOCKER_TLS_VERIFY
    export DOCKER_HOST=tcp://192.168.59.103:2375
    unset DOCKER_CERT_PATH
```

And sometimes, the `export` line is the last one. It seems that command substitution fails in these cases:

```bash
$(echo "
    unset DOCKER_TLS_VERIFY
    export DOCKER_HOST=tcp://192.168.59.103:2375
    unset DOCKER_CERT_PATH
")
# -bash: unset: `DOCKER_HOST=tcp://192.168.59.103:2375': not a valid identifier

$(echo "
    unset DOCKER_TLS_VERIFY
    unset DOCKER_CERT_PATH
    export DOCKER_HOST=tcp://192.168.59.103:2375
")
# -bash: unset: `DOCKER_HOST=tcp://192.168.59.103:2375': not a valid identifier

$(echo "
    export DOCKER_HOST=tcp://192.168.59.103:2375
    unset DOCKER_TLS_VERIFY
    unset DOCKER_CERT_PATH
")
# no error
```

**Comment by skozin** [comment]
This seems like some oddity with using both `unset` and `export` commands inside a command substitution. I've posted a [question on StackExchange](http://unix.stackexchange.com/questions/181579/bash-command-substitution-with-multiple-unset-export-commands) about this behaviour.

**Comment by SvenDowideit** [comment]
oh wow, so its a really easy fix for us to order the commands right

thankyou for the details!

**Comment by skozin** [comment]
@SvenDowideit, unfortunately this cannot be solved by just re-ordering the commands, or any other change in the output of `boot2docker shellinit`. That's because everything produced by an unquoted command substitution is being splitted and interpreted as one command. See my previous comment for details.

The solution is to quote command substitution, and then pass the resulting (non-splitted) string to `eval`:

```bash
eval "$(boot2docker shellinit)"
```

**Comment by SvenDowideit** [comment]
oh. I missread the `export ... unset ...` version, oh boy.

**Comment by SvenDowideit** [comment]
ok, so 

```
mini:~ sven$ $(echo "
    export DOCKER_TLS_VERIFY= 
    export DOCKER_HOST=tcp://10.10.10.2:2375
    export DOCKER_CERT_PATH=
")
``` 

seems to allow the Docker client to correctly not use TLS

can we replace the unset's with export and get away with it?

**Comment by skozin** [comment]
Hmm, using empty strings instead of `unset` commands is a clever idea =)

I think this will be more correct:

```bash
$(echo "export
    DOCKER_TLS_VERIFY='' 
    DOCKER_HOST=tcp://10.10.10.2:2375
    DOCKER_CERT_PATH=''
")
```

because it doesn't performs unneeded export of the `export` variable. Or, better yet:

```bash
$(echo "export DOCKER_TLS_VERIFY='' DOCKER_HOST=tcp://10.10.10.2:2375 DOCKER_CERT_PATH=''")
```

This is completely equivalent to the previous snippet, and is easier to understand.

**Comment by SvenDowideit** [comment]
@tianon should we get this into 1.5.0 too?

**Comment by skozin** [comment]
I think this is also applicable for docker machine's [`env` command](https://github.com/docker/machine/blob/master/commands.go#L339).

**Comment by SvenDowideit** [comment]
ok, over it, I'm implementing this atm.

**Comment by skozin** [comment]
Thanks for fixing this! =)
