### ISSUE TITLE
Fatal error running "docker version" and other commands

### ISSUE THREAD

**Issue by alexpreynolds** [boot2docker/boot2docker#726]
I installed the current release of ``boot2docker``. The installation was successful and no errors were returned. Subsequently, ``docker`` returns fatal errors on basic commands:

```
$ docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): darwin/amd64
FATA[0000] Get http:///var/run/docker.sock/v1.16/version: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS? 
```

This same error occurs when trying to pull down an image from the hub:

```
$ docker run --name wordpress-db -e MYSQL_ROOT_PASSWORD=abcd1234 -d mysql
FATA[0000] Post http:///var/run/docker.sock/v1.16/containers/create?name=wordpress-db: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS? 
```

**Comment by RomanSaveljev** [comment]
Looks like your shell was not provisioned. You should run `boot2docker shellinit`. I usually do it like this:

``` bash
boot2docker shellinit >/tmp/init.sh
. /tmp/init.sh
```

**Comment by alexpreynolds** [comment]
Okay, thanks — that fixed it.

**Comment by sirkkalap** [comment]
You can also use $(boot2docker shellinit) to avoid temp file. It is syntax for subshell execution and evaluation of result in parent shell.
