### ISSUE TITLE
`boot2docker upgrade` on OSX doesn't upgrade client version

### ISSUE THREAD

**Issue by grange74** [boot2docker/boot2docker#732]
I initially installed the Boot2Docker pkg version 1.3.0 a while ago and since then have upgraded each time a new release has come out using boot2docker stop, download & start and later on using boot2docker upgrade.

It seems that each time it downloaded the new ISO and update the VM correctly to the new version but does not update the client version.

I've read on a few other similar issues that i might need to do a reinstall, if so i'd like to know how i can easily keep all my existing containers.

Here is the output i get when i start up:

    Client version: 1.3.0
    Client API version: 1.15
    Go version (client): go1.3.3
    Git commit (client): c78088f
    OS/Arch (client): darwin/amd64
    Server version: 1.5.0
    Server API version: 1.17
    Go version (server): go1.4.1
    Git commit (server): a8a31ef

Btw I am running boot2docker on OSX 10.10.2.

**Comment by SvenDowideit** [comment]
@nathanleclaire I thought you coded this up - do you know what version it was released in?

**Comment by nathanleclaire** [comment]
I did, and it was merged, so I'm quite baffled about this behavior.  I also tried `boot2docker upgrade` yesterday and it didn't work, so I'll investigate.

**Comment by grange74** [comment]
Thanks a lot, that worked. 
I'm very happy that I can now use the new features and still have all my containers and images.

FYI, when i ran the upgrade using the new boot2docker binary i got:

    Backing up existing docker binary...
    Downloading new docker client binary...
    Success: downloaded https://get.docker.com/builds/Darwin/x86_64/docker-latest
	to /usr/local/bin/docker
	The old version is backed up to ~/.boot2docker.
    boot2docker is up to date (v1.5.0), skipping upgrade...
    Latest release for boot2docker/boot2docker is v1.5.0
    Downloading boot2docker ISO image...
    Success: downloaded       
    https://github.com/boot2docker/boot2docker/releases/download/v1.5.0/boot2docker.iso
	to /Users/nic/.boot2docker/boot2docker.iso
    Waiting for VM and Docker daemon to start...
    ..........ooo
    Started.

**Comment by nathanleclaire** [comment]
Yup looks right!  Glad we could help.
