### ISSUE TITLE
Need NTP Pool vendor name

### ISSUE THREAD

**Issue by abh** [boot2docker/boot2docker#736]
https://github.com/boot2docker/boot2docker/blob/master/rootfs/rootfs/etc/rc.d/ntpd

Please see http://www.pool.ntp.org/vendors.html

**Comment by SvenDowideit** [comment]
@tianon gosh.

**Comment by tianon** [comment]
Oh!  I'm applying now; thanks for the heads up!  (and taking care of our ToS non-compliance reported in #789)

**Comment by tianon** [comment]
Status update: I have applied for a vendor zone; just waiting to hear back.

As a side note, has anyone let TCL know that they ought to apply for one too? :smile: (http://git.tinycorelinux.net/index.cgi?url=Core-scripts.git/tree/etc/sysconfig/ntpserver)
