### ISSUE TITLE
Docker build error

### ISSUE THREAD

**Issue by movie4** [boot2docker/boot2docker#738]
Hello.

Run command: win7 - 64-bit
`vagrant up my_app --provider=docker`

A Docker command executed by Vagrant didn't complete successfully!
The command run along with the output from the command is shown
below.

`Command: "docker" "build" "--tag=my_app" "/mnt/docker_build_4bcbee0d7c5db0ace3ccc3b3b952c89d"`

`Stderr: 2015/02/12 11:38:09 stat /mnt/docker_build_4bcbee0d7c5db0ace3ccc3b3b952c89d: no such file or directory`

**Comment by nathanleclaire** [comment]
Hi @movie4, thanks for the bug report.  This looks to me like a Vagrant issue (Usually the last argument to `docker build` is `.`, so `/mnt/docker_build_4bcbee0d7c5db0ace3ccc3b3b952c89d` seems a quite odd choice to me), so please report it here instead: https://github.com/mitchellh/vagrant .

**Comment by movie4** [comment]
Thanks for your answer!
