### ISSUE TITLE
docker.sock: no such file or directory.

### ISSUE THREAD

**Issue by ivanhernandezkwarter** [boot2docker/boot2docker#742]

**Comment by hairyhenderson** [comment]
Can you provide some more details on what you did to get this error? What command(s) you ran, what version of boot2docker, etc...

**Comment by SvenDowideit** [comment]
sounds like you probably did not run `$(boot2docker shellinit)` before you ran the docker client, and so it was looking in the wrong place.

**Comment by ivanhernandezkwarter** [comment]
Exactly Sven. Actually, issue got created by mistake while searching. exports with docker environment variables were not set and therefore docker tried to reach the server on the local unix socket.

Thanks for the help!
