### ISSUE TITLE
Docker daemon in VM does not start

### ISSUE THREAD

**Issue by o-zander** [boot2docker/boot2docker#745]
I'm using boot2docker under Mac OS Yosemite. After `boot2docker up` and exporting the environment variables all docker commands like `docker images` fail with `Cannot connect to the Docker daemon. Is 'docker -d' running on this host?`. So I ssh'd to the host and answered the question myself: No it is not. After manually starting the daemon my docker commands run fine. Why does the docker daemon does not start automatically in the VM? Has anyone encountered this problem before?

**Comment by RomanSaveljev** [comment]
Yes, I saw it quite often daemon fail to start itself after virtual machine abort.

**Comment by iammichiel** [comment]
Confirmed on a clean 1.5.0 install on Mac. Ssh'd into the machine and starting it manually.

**Comment by iammichiel** [comment]
Actually, while digging into the log files, this appears to be the cause of the crash : 
```
time="2015-02-18T20:54:14Z" level="debug" msg="Registering POST, /images/load"
no such device
time="2015-02-18T20:54:14Z" level="info" msg="-job init_networkdriver() = ERR (1)"
time="2015-02-18T20:54:14Z" level="fatal" msg="no such device"
```

Got no clue what it means but it seems to be network related.

**Comment by kyleboyle** [comment]
Im getting the same error
```
time="2015-02-25T01:27:10Z" level="debug" msg="Registering DELETE, /images/{name:.*}" 
time="2015-02-25T01:27:10Z" level="debug" msg="Registering OPTIONS, " 
no such device
time="2015-02-25T01:27:10Z" level="info" msg="-job init_networkdriver() = ERR (1)" 
time="2015-02-25T01:27:10Z" level="fatal" msg="no such device" 
```
I can ssh in and run init.d script and it starts fine.

**Comment by tyrbo** [comment]
I've seen the same thing. Very unpredictable. Doesn't always occur during boot.

**Comment by thedewi** [comment]
I'm seeing the same thing as iammichiel and kyleboyle during most boots. Clean install of boot2docker in Windows 7 with VirtualBox 4.3.22:
```
time="2015-03-04T06:29:14Z" level="debug" msg="docker group found. gid: 100"
no such device
time="2015-03-04T06:29:15Z" level="info" msg="-job init_networkdriver() = ERR (1)"
time="2015-03-04T06:29:15Z" level="fatal" msg="no such device"
```

**Comment by chelin** [comment]
Same here on OS X 10.10.3 with VBox 4.3.24.

**Comment by techsoldaten** [comment]
Same here on OSX 10.9.5 with VBox 4.3.20.

**Comment by albertein** [comment]
Same with OSX 10.10 and Vbox 4.3.20.

**Comment by paolosaudin** [comment]
Same here on Windows7 x64 with VBox 4.3.24

**Comment by jedi4ever** [comment]
Same happening 10.10.2 and Vbox 4.3.26 .

I've logged in manually over ssh:
- saw no docker daemon running
- saw the same fatal network error in the docker.log
- after a couple of minutes waiting the daemon did come up fine

so it might be a timing issue at startup where the network is not yet fully there and docker is started?

**Comment by chelin** [comment]
This worked for me 

boot2docker ssh "sudo /etc/init.d/docker start"

**Comment by deepflame** [comment]
@chelin thanks a ton, this worked!

**Comment by ahmetalpbalkan** [comment]
This problem shouldn't be specific to boot2docker.

We are seeing the same problem very rarely (<1%) on virtual machines created on Azure platform. It happens _only for the first time we run installation script after the VM is booted_ and doesn't reproduce after that.

I've more details here: https://gist.github.com/ahmetalpbalkan/d22b54e231ab4ec8fc66 Basically installation command is just what's documented in Docker User Guide (`curl ... | sh`) and `start docker` gets stuck at some point and if we look at `/var/log/upstart/docker.log` it appears that we got the `"no such device"` error as well and it just keeps polling for the unix socket which would never come up.

**Comment by radu-matei** [comment]
Hi, @ahmetalpbalkan !

Can you please provide some information on how you got a Boot2Docker VM in Azure?

Thanks!

**Comment by radu-matei** [comment]
@ahmetalpbalkan 

I actually managed to deploy a Boot2Docker VM in Azure after creating a VHD as described [here](https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-linux-upload-vhd) and [here](https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-linux-create-upload-generic?toc=%2fazure%2fvirtual-machines%2flinux%2ftoc.json).

As far as I can see, everything works properly, I can SSH into the machine and Docker works fine, but in the portal it shows that the deployment failed due to some timeout.

Assumption ahead: Since the [waagent](https://github.com/Azure/WALinuxAgent) is not present in the Boot2Docker image, I believe it cannot properly communicate with Azure.

Since waagent has a rather long list of dependencies (Python 2.6+, OpenSSL 1.0+, OpenSSH5.3+, Filesystem utilities: sfdisk, fdisk, mkfs, parted, Password tools: chpasswd, sudo, Text processing tools: sed, grep, Network tools: ip-route), do you see it possible to install it for Tiny Core Linux?

Thanks,
Radu

**Comment by yosifkit** [comment]
@radu-matei, boot2docker is meant as a development tool to get docker running on OSX and Windows, which, in most cases, is now superseded by "Docker for Mac" and "Docker for Windows".  For production environments on cloud infrastructure, something better designed for that like CoreOS or RancherOS and even the regular Linux distributions like CentOS, Debian, Fedora, RedHat, and Ubuntu with docker installed would probably be a better choice than boot2docker.
