### ISSUE TITLE
Use docker CLI instead of boot2docker ssh on Windows machines

### ISSUE THREAD

**Issue by bazzilic** [boot2docker/boot2docker#760]
Whenever you try to do `boot2docker start` on a Windows host it says `Docker client does not run on Windows for now`, and suggests to use `boot2docker ssh` to access docker.

However, based on [this](http://azure.microsoft.com/blog/2014/11/18/docker-cli-for-windows-clients/) and [this](https://github.com/docker/docker/pull/9113) I assume that docker CLI actually does work on Windows.

Are there plans to change the boot2docker behavior to use docker CLI on Windows?

**Comment by SvenDowideit** [comment]
yes. When there is an official Docker release containing the Windows Client, then the boot2docekr installer will be updated to include it.

This is expected to happen with the 1.6 release, and the number of fixes that have happened in the last month suggest that its going well :)

(those blog posts assume that you are building your own from source.)

**Comment by bazzilic** [comment]
I see. Thank you for the clarification!
