### ISSUE TITLE
Shellinit sets blank export env var

### ISSUE THREAD

**Issue by MrMMorris** [boot2docker/boot2docker#763]
Just noticed something weird while created a docker setup script:

```
$ env | grep export
$ $(boot2docker shellinit 2>/dev/null)
$ env | grep export
$ export=
```
Not really an issue or anything, but there might be some line that wasn't deleted or something :wink:

**Comment by SvenDowideit** [comment]
this is also changed by https://github.com/boot2docker/boot2docker-cli/pull/351 - which will always print out the settings, even if they're set (its clearer to the user that way)
