### ISSUE TITLE
Space in home directory

### ISSUE THREAD

**Issue by kraney** [boot2docker/boot2docker#768]
On OSX, the command "boot2docker shellinit" is failing when my home directory path has a space in it.

tobenhaus-nb:~ kraney$  $(/usr/local/bin/boot2docker shellinit)
Writing /Volumes/600GB SSD/Users/kraney/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Volumes/600GB SSD/Users/kraney/.boot2docker/certs/boot2docker-vm/cert.pem
Writing /Volumes/600GB SSD/Users/kraney/.boot2docker/certs/boot2docker-vm/key.pem
bash: export: `SSD/Users/kraney/.boot2docker/certs/boot2docker-vm': not a valid identifier

**Comment by SvenDowideit** [comment]
poking this too

**Comment by SvenDowideit** [comment]
this is a duplicate of #715
