### ISSUE TITLE
Default to a single CPU core

### ISSUE THREAD

**Issue by lmakarov** [boot2docker/boot2docker#769]
I'm getting considerably better results with a single core on both Mac and Windows.
The application uses two containers: a web (nginx+php-fpm) and a db (mysql).
I'm seeing a 40% (!!!) performance gain from switching from 8 cores (default and recommended max by VirtualBox) to a single core.

Apparently virtualizing multiple cores for a VM is more overhead than benefit for VirtualBox in most cases. You may achieve better results if the guest stack/application is optimized for a multi-core environment. However, the primary use case for boot2docker is non-production use/local development, so it may make sense to default to a single core for better performance in most cases.

**System information**
```
Boot2Docker-cli version: v1.5.0
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): darwin/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

**Related discussions**
- https://forums.virtualbox.org/viewtopic.php?f=2&t=56730
- http://superuser.com/questions/297697/are-there-any-real-advantages-to-assigning-more-cores-to-virtualbox
- #702

**Comment by SvenDowideit** [comment]
I have passed this on to the docker-machine project, as the b2d-cli which sets this is in the process of being replaced.
