### ISSUE TITLE
"boot2docker, please format-me" in docker home directory

### ISSUE THREAD

**Issue by pmario** [boot2docker/boot2docker#777]
slightly related to #634

I'm using docker:machine V 0.1.0 on Win 8.1 with hyper-v. 

I'm new to docker:machine and machine imo is alpha. So this is probably a newbie problem, but extremely time consuming and frustrating!

* I just did create a new VM using docker:machine 
* The actual version of DM has a bug https://github.com/docker/machine/issues/647 so the creation fails!
* I did download a development environment, fixed the bug, built a new windows exe
* now the `machine create` command seems to work ... 

... I did enter the vm with `machine ssh`, I did a `ls` in the docker home directory, I got `boot2docker, please format-me`

The result is, that I thought the whole process went wrong! ... Since machine (V0.1.0) is broken at the moment, I did search there, just to find out, it's just a init relict. 

For the sake of new users, please fix this.

**Comment by ehazlett** [comment]
This is part of the b2d process I believe.  @tianon can you explain why that file is there and is it safe to remove?

**Comment by tianon** [comment]
Yeah, this is due to the way the boot2docker initialization works, and should've been fixed by https://github.com/boot2docker/boot2docker/pull/651 (ie, not slightly related to #634: literally is #634 resurfaced :+1:).

**Comment by SvenDowideit** [comment]
who reviewed that PR? geeeesh. (or maybe it did work then, but ouch anyway)
