### ISSUE TITLE
Add a new subcommand for ip

### ISSUE THREAD

**Issue by crosbymichael** [boot2docker/boot2docker#792]
**Problem**

Subcommand "ip" output

**Solution**

The `boot2docker ip` subcommand returns a complex string rather than the IP address alone:

```
$ boot2docker ip

The VM's Host only interface IP address is: 192.168.59.103

```

Change the `ip` subcommand to return the IP address only.

**Comment by SvenDowideit** [comment]
this is a `boot2docker-cli` issue, and I _think_ its fixed.
