### ISSUE TITLE
Accessing host IP from boot2docker VM?

### ISSUE THREAD

**Issue by olalonde** [boot2docker/boot2docker#795]
Is there any way to access the host (OS X) IP from the boot2docker VM? If so, what is the IP or how can I find it? I have a default `boot2docker init` install.

**Comment by znerd** [comment]
It should be easy to set the host IP address from the host, in a specific
file, like /var/hostip or so.

Conceptually, something like this:

host$ HOST_IP=`ifconfig en1 | grep inet\ | awk '{print $2}'`
host$ ssh --non-interactive --command "echo $HOST_IP > /var/hostip`


Note that the SSH command might be a bit more complex, it's just to show
the concept.

Then from within the VM, you can just get the host IP address from that
file:

guest$ cat /var/hostip


HTH. Cheers, Ernst


2015-03-23 17:43 GMT+01:00 Olivier Lalonde <notifications@github.com>:

**Comment by olalonde** [comment]
Thanks
