### ISSUE TITLE
Starting a container from bootlocal.sh fails with TLS error

### ISSUE THREAD

**Issue by dmenne** [boot2docker/boot2docker#804]
This is a repost of:

http://stackoverflow.com/questions/29321917/container-cannot-be-started-from-bootlocal-sh

which comments/answers.

Running Boot2Docker 1.5.0 under Windows. A container `gastrobase` exists and can be started manually with `docker start gastrobase`.

When I put this command into /var/lib/boot2docker/bootlocal.sh, upon startup I get

`Post http:///var/run/docker.sock/v1.17/containers/gastrobase/start: dial unix /var/run/docker.sock: no such file or directory. 
Are you trying to connect to a TLS-enabled daemon without TLS? 
time="2015-03-28T19:50:51Z" level="fatal" 
msg="Error: failed to start one or more containers" in var/log/bootlocal.log.
`

Running ./bootlocal.sh manually starts Ok.

**Comment by dmenne** [comment]
This proved to be a racing condition: With the following in `bootlocal.sh` startup works

```
sleep 1
docker start gastrobase
```
Any suggestion how to make this more robust? Wait for what?

**Comment by RomanSaveljev** [comment]
Would `--restart=always` be enough to achieve the goal?

https://docs.docker.com/articles/host_integration/

**Comment by dmenne** [comment]
Can this be used on the command line? How? 
I always thought it is for systemd only.

**Comment by dmenne** [comment]
Seems to work mostly, but hangs (not reproducibly) occasionally.

A better refererence is:

https://docs.docker.com/reference/run/#restart-policies-restart

**Comment by mlb-** [comment]
To avoid race conditions, and lag from my boot2docker's hosting VM, I put this line before my docker commands:
`while [ ! -e /var/run/docker.sock ]; do sleep 1; done`
This is, admittedly, hacky, but it gets the job done.
