### ISSUE TITLE
NFS support

### ISSUE THREAD

**Issue by chiedojohn** [boot2docker/boot2docker#817]
What is the likelihood of getting NFS support? Shared folders are extremely slow. With Vagrant, I would just use the following in my vagrant file and things worked like a charm.
```config.vm.synced_folder '.', '/vagrant', nfs: true, :mount_options => ['actimeo=2']```

Is there anything on the radar for getting the same kind of option for boot2docker?

Thanks,

**Comment by AntonioMeireles** [comment]
@chiedojohn fwiw and as a 'workaround' you can just try to use my [vagrantified boot2docker](https://github.com/AntonioMeireles/boot2docker-vagrant-box) which does just that ...

**Comment by chiedojohn** [comment]
Thanks @AntonioMeireles  I will check that out. That could be a game changer. Things are running so slowly as it currently stands!

**Comment by joelwurtz** [comment]
You can use nfs inside boot2docker, it is just not documented

I have done the following steps in order to have nfs share on boot2docker : 

* Share the nfs folder on your mac by adding it to your /etc/exports : 

```
# /etc/exports
/Users 192.168.59.103 -alldirs -mapall=501:20
```

* Reload your nfs : 

```
sudo nfsd restart
```

* Mount the volume on boot2docker

```
boot2docker ssh
sudo umount /Users
sudo /usr/local/etc/init.d/nfs-client start
sudo mount -t nfs -o rw 192.168.59.3:/Users /Users
```

**Comment by chiedojohn** [comment]
Hey @joelwurtz,
Thanks for your suggestion. I'm having no luck though, 

I am getting the following after attempting to mount the nfs on the client:
```mount: RPC: Authentication error; why = Client credential too weak```

And I did change 192.168.59.3 to my host IP address as assumed.

Any ideas?

Thanks!

**Comment by chiedojohn** [comment]
Scratch that last statement. It looks like I wasn't supposed to change 192.168.59.3 to my host IP. Looks like it's working. Thanks for your help.

**Comment by chiedojohn** [comment]
Thanks again for all of your help. 

I went ahead and wrote a quick tutorial for whoever else comes across this page on how to automate that process so it's automatically is configured each time boot2docker is started.

https://gist.github.com/chiedojohn/4d2cc894f53c3da1910c

**Comment by thaJeztah** [comment]
@chiedojohn perhaps you should create a pull request to add this as a document to the docs?

**Comment by chiedojohn** [comment]
@thaJeztah good call. The pull request has been submitted.
