### ISSUE TITLE
SSL Certificate

### ISSUE THREAD

**Issue by Rob-Johnson** [boot2docker/boot2docker#819]
Hi,

This might be an issue for Docker rather than Boot2Docker, so apologies if that is the case.

I'm attempting to secure a Docker registry, and I'm testing my local setup:

- I'm running one container with the registry
- One container with a modified NGINX, responsible for SSL termination and reverse proxying.

I'm using an SSL certificate signed by GoDaddy (and so their Root CA Certificate is trusted by most OS's).

I can access `https://my-test-registry.bnservers.com:1000/_ping` fine through the browser and using cURL. Chrome shows the certificate as secure and recognises that it is signed by GoDaddy.

<img src="https://cloud.githubusercontent.com/assets/1389671/7046663/55e515c8-ddff-11e4-94a1-c8028d10e608.png" alt="alt text" width="200" height="300">

However, when I try and push/pull using the Docker Client (either on my host machine, or on the boot2docker vm) it fails with the following error:

```FATA[0000] Error: v1 ping attempt failed with error: Get https://test-registry.bnservers.com:1000/v1/_ping: x509: certificate signed by unknown authority. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry test-registry.bnservers.com:1000` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/test-registry.bnservers.com:1000/ca.crt```

The boot2docker vm seems to include the root CA certificates for GoDaddy:

```
$ ls /etc/ssl/certs | grep Go_Daddy
Go_Daddy_Class_2_CA.pem
Go_Daddy_Root_Certificate_Authority_-_G2.pem
```
I'm having trouble understanding why Docker is failing to recognise the certificate used. If you could advise on what role Boot2Docker might be having in all this (if any), then that would be great.

Thanks

**Comment by md5** [comment]
The `docker` daemon in b2d is only set up to recognize a single CA certificate: https://github.com/boot2docker/boot2docker/blob/175488c34ff9c05c1307705c47a4d8a1282951b8/rootfs/rootfs/usr/local/etc/init.d/docker#L60

It doesn't look at `/etc/ssl/certs`.

**Comment by md5** [comment]
You should be able to set `CACERT` to point to a PEM bundle that includes the GoDaddy root CA cert in `/var/lib/boot2docker/profile`.

**Comment by md5** [comment]
Acutally... The instructions I just gave are for if you want to recognize a client certificate signed by a real CA. For the `docker` client case, you need to do the same thing and pass the PEM bundle name to `-tlscacert` yourself.

**Comment by md5** [comment]
You might be able to just append the root CA to your `~/.boot2docker/certs/boot2docker-vm/ca.pem` and not have to much with `-tlscacert` directly.

**Comment by Rob-Johnson** [comment]
Hi @md5,

Thanks for your comments, they definitely identify the cause of the problem.

We're trying to reduce the amount of extra setup that developers have to go through to be up and running with Docker, so this isn't ideal. Why is it that boot2docker is set up to replace the recognised CAs, rather than just adding to them?

**Comment by SvenDowideit** [comment]
mmm, I was just testing something like this yesterday - though I was using a Docker 1.6 release candidate

@Rob-Johnson could you possibly test using an iso from https://github.com/tianon/boot2docker/releases ?

note that I was using a instantssl cert, and did not have to install any certs to be able to push&pull the local registry

**Comment by Rob-Johnson** [comment]
Hi @SvenDowideit,

Just tried with the latest boot2docker iso available at the link you pointed me to and I'm still having no luck. You being able to use an instantssl certificate gives me hope though, and means that what @md5 said above about boot2docker *only* accepting it's own self-signed certificate may not be entirely true.

Thanks,
Rob

**Comment by md5** [comment]
All I meant is that the default setup only recognizes the internally generated cert, not that it is only *able* to use that cert.

**Comment by SvenDowideit** [comment]
does #807 help you?

**Comment by Rob-Johnson** [comment]
Hi @SvenDowideit 

In the end I found it was an issue with the certificate - the cert issued by GoDaddy was signed by an intermediate cert so I needed to include the whole certificate chain.

Thanks for your help though, happy to close this.

Rob
