### ISSUE TITLE
Inaccurate logo in ASCII representation

### ISSUE THREAD

**Issue by abrkn** [boot2docker/boot2docker#821]
The ASCII representation of the Docker whaletainership is missing a container:

![ascii](http://i.gyazo.com/99d4c74d675dac5991d524290be0387e.png)

vs

![original](http://i.gyazo.com/8a42d1b7751c3dfeb39f847925d58a32.png)

Proposed solution: Add `##` to whale.

**Comment by thaJeztah** [comment]
:heart: best issue of the day!

**Comment by tiborvass** [comment]
Ping @steeve :D

**Comment by md5** [comment]
:laughing:
