### ISSUE TITLE
Boot2Docker for Windows should include docker CLI

### ISSUE THREAD

**Issue by AndreLouisCaron** [boot2docker/boot2docker#830]
I use boot2docker quite a bit on OSX and I've just tried it today on Windows.  It seems that a pre-built docker CLI for Windows is quite hard to find.  It would be much simpler if a copy was included alongside `boot2docker.exe` in the boot2docker installation.

It looks like there are ["Docker Master Binaries"](https://master.dockerproject.com/), but the page only has the latest Docker CLI binaries, which might be unstable or even more recent than the version of Docker in the boo2docker install.

**Comment by thaJeztah** [comment]
Docker 1.6 (which is scheduled to be released today) will be the first release with a native windows client binary; you should be able to download that from the docker website. There are still some rough edges with shell handling, but it is shaping up nicely thanks to a lot of effort from the Microsoft contributors!

**Comment by ereOn** [comment]
@thaJeztah That's great news indeed !

Is a new release of boot2docker planned as well for today ? It seems that the latest docker client version is not compatible with the one in boot2docker (1.17 <> 1.19).

**Comment by thaJeztah** [comment]
@ereOn Well the 1.6 release is still being tested, so *if all goes well*, it should be released (famous last words...)

I think the Boot2Docker maintainers will release at the same time

**Comment by AndreLouisCaron** [comment]
@thaJeztah Thanks for the info.  I have a related question.  I don't understand how to translate `$(boot2docker shellinit)` on Windows.  At least, with 1.5, it simply outputs the `export DOCKER_...=...` statements which are not compatible with Windows (in addition to not having an equivalent to the `$()` syntax).  How will that work in B2D 1.6?

**Comment by mausch** [comment]
The latest releases already include the Windows docker CLI, so I guess this issue can be closed now?

**Comment by AndreLouisCaron** [comment]
Yup!
