### ISSUE TITLE
[Question] Docker-cli outdated?

### ISSUE THREAD

**Issue by kennethlimcp** [boot2docker/boot2docker#833]
i just upgraded `boot2docker` on my Mac and here's the output:

```
boot2docker download
Latest release for boot2docker/boot2docker is v1.6.0
Downloading boot2docker ISO image...
Success: downloaded https://github.com/boot2docker/boot2docker/releases/download/v1.6.0/boot2docker.iso
```

Running `docker version`:

```
Client version: 1.3.1
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 4e9bbfa
OS/Arch (client): darwin/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
```

Is that correct or am i missing out some steps?

**Comment by Janus1990** [comment]
What System are you using?
How did you installed boot2docker and docker on your computer (Docker Installer, Homebrew, ...?).
Just updating the Linux image doesn't mean updating the binaries on your host.
I won't be surprised if ```boot2docker version``` returns:
```
$ boot2docker version
Boot2Docker-cli version: v1.3.1
Git commit: 57ccdb8
```
If your boot2docker binaries would be up to date you should get that output:
```
$ boot2docker version
Boot2Docker-cli version: v1.6.0
Git commit: 9894ae9
```

**Comment by kennethlimcp** [comment]
Indeed.. `boot2docker version` is giving me: 

```
Boot2Docker-cli version: v1.3.1
Git commit: 57ccdb8
```

I think i used the Docker installer. How can i go about updating everything properly? :)

**Comment by Janus1990** [comment]
Basically you could...
* visit http://boot2docker.io/ and grep the latest installer
* compile it on your own (I mean GitHub was build for this reason)
* use a package manager like Homebrew (which I prefer on my Mac).
* ...

Needless to say that you should uninstall your outdated version first.

**Comment by SvenDowideit** [comment]
have you run `boot2docker upgrade` ?

**Comment by kennethlimcp** [comment]
@SvenDowideit , thanks for getting back to me.

Just did that:

```
KENMBP:~ kennethlimcp$ boot2docker upgrade
Latest release for boot2docker/boot2docker is v1.6.0
Downloading boot2docker ISO image...
Success: downloaded https://github.com/boot2docker/boot2docker/releases/download/v1.6.0/boot2docker.iso
	to /Users/kennethlimcp/.boot2docker/boot2docker.iso
```

Does boot2docker actually upgrade the `docker` cli? Or do i have to upgrade it manually?

```
KENMBP:~ kennethlimcp$ docker info
^CKENMBP:~ kennethlimcp$ docker version
Client version: 1.3.1
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 4e9bbfa
OS/Arch (client): darwin/amd64
```

**Comment by SvenDowideit** [comment]
mmm, ok, I guess your version of Boot2Docker (the cli) is too old, so its not upgrading either it, or the docker client.

personally, I'd download the osx installer and use that to upgrade everything.

**Comment by kennethlimcp** [comment]
@SvenDowideit that did the trick! Thanks for the help :)
