### ISSUE TITLE
Boot2docker's VM time lagged behind the host's

### ISSUE THREAD

**Issue by cooniur** [boot2docker/boot2docker#840]
Related to https://github.com/boot2docker/boot2docker/issues/290 (trigger b2d to run ntpdate on OSX/WIndows resume events)

I wonder if the above issue 290 has been fixed. I found that after sleeping and resuming my Mac, the time in boot2docker VM was 15min behind the host. I'm on the latest version (1.5.0).

**Comment by docwhat** [comment]
Did it correct after about 10-15 minutes?  Or did it remain off?  `ntpd` doesn't fix the clock immediately.

**Comment by tianon** [comment]
#1035 didn't fix this just yet thanks to our `ntpd` being from BusyBox -- we should probably just get the `VBoxService` running now with `--timesync-only` or whatever the flag is now that we've got a 64bit userspace.  I'm working on a PR now. :smile:

**Comment by mikesherov** [comment]
Thanks @tianon this will be a tremendous help for us!
