### ISSUE TITLE
Connect devices to docker instances.

### ISSUE THREAD

**Issue by RamonBoza** [boot2docker/boot2docker#843]
Hi,

I'm trying to connect a device to a docker instance on Mac OS X.

I have 4 devices on my system:

* iphone 6
* iphone 5s
* s5
* nexus 6

I want to be able, if possible, to start 4 instances and assign each device to each instance.

Is it possible?

If so, how can I do that? I'm playing with --device command with no luck.

thanks!

**Comment by jonbjo** [comment]
Have a look at #707 and see if that helps.

**Comment by RamonBoza** [comment]
wow thanks you!!!

We have the limitation of needing a mac system, docker is based on top of
linux so we get that working using vagrant + vboxmanage as well.

But thanks!!!

**Comment by xavriley** [comment]
@RamonBoza can this be closed now?

**Comment by RamonBoza** [comment]
yes
