### ISSUE TITLE
Create custom boot2docker with images in local registry?

### ISSUE THREAD

**Issue by sisao** [boot2docker/boot2docker#855]
Hi,
is it possible to build a custom boot2docker iso file with a populated local registy?
If yes, is there a howto or is this all done in the Dockerfile?

thx...

**Comment by SvenDowideit** [comment]
yup, https://github.com/boot2docker/boot2docker/blob/master/doc/BUILD.md#making-your-own-customised-boot2docker-iso

**Comment by sisao** [comment]
Of course I know this doc, but what I wanted, was to create a iso with some images in the registry.
I got this now, the only disadvantage is the grown initrd.img...

**Comment by SvenDowideit** [comment]
ah, nice!
