### ISSUE TITLE
Unable to configure proxy in 1.6

### ISSUE THREAD

**Issue by PavelVanecek** [boot2docker/boot2docker#856]
I was using the `/var/lib/boot2docker/profile` file to set a proxy, as explained in a [stackoverflow post](http://stackoverflow.com/questions/24489265/docker-boot2docker-set-http-https-proxies-for-docker-on-osx).

However, since 1.6, this is ignored. How to reproduce:

```
$boot2docker ssh
> Boot2Docker version 1.6.0, build master : a270c71 - Thu Apr 16 19:50:36 UTC 2015
> Docker version 1.6.0, build 4749651
docker@boot2docker:~$ cat /var/lib/boot2docker/profile 
export foo=bar
docker@boot2docker:~$ echo $foo # expected: bar, actual: no value

```

If I include the file directly, it is interpreted correctly:
```
docker@boot2docker:~$ . /var/lib/boot2docker/profile
docker@boot2docker:~$ echo $foo
bar
```

Is there something I am missing?

**Comment by Mansuro** [comment]
Did you set your proxy username and password?

**Comment by SvenDowideit** [comment]
the `/var/lib/boot2docker/profile` file only sets the environment that the Docker daemon is started with, not that of the users.

**Comment by PavelVanecek** [comment]
It might be another issue then. To get the profile settings ready, is it enough to do `sudo /etc/init.d/docker restart` or it is necessary to run `boot2docker restart`?
