### ISSUE TITLE
Bump kernel to 4.0

### ISSUE THREAD

**Issue by frol** [boot2docker/boot2docker#861]
Could you please bump the kernel to 4.0? `kmem` leaks in cgroup were fixed ([here are more details](https://github.com/docker/docker/issues/6479#issuecomment-97503551))

**Comment by tianon** [comment]
That fix wasn't backported to the 3.18 longterm series?  I like 3.18
because it's a longterm, but Docker releases happen often enough that I
could be persuaded otherwise with compelling arguments (patches like this
one not being backported being an example, but I can't imagine Greg
wouldn't pull in fixes for things like kmem leaking). :smile:

**Comment by frol** [comment]
@tianon I'm not sure where I should look for information about backports, so I don't know whether it was backported or not. The commit in 4.0 was https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=d6e0b7fa11862433773d986b5f995ffdf47ce672

**Comment by tianon** [comment]
I can't find that commit in any kernel backports at all. :disappointed:

If we can reproduce the issue it fixes, that'd definitely help determine
whether 3.18 is affected, but it's looking like it probably is, and that
upgrading to 4.0 is inevitable. :+1:

**Comment by tianon** [comment]
I almost forgot our other main roadblock to switching.  AUFS support...

http://sourceforge.net/p/aufs/aufs3-standalone/ref/master/branches/ <<
we don't have a 4.0 branch yet :disappointed:

**Comment by frol** [comment]
@tianon kernels <4.0 are affected to the bug when you set `memory.kmem.limit_in_bytes`. Docker does not support this feature yet, so it doesn't affect Docker users directly, but my application uses cgroups directly and does set `memory.kmem.limit_in_bytes` as a workaround to prevent fork-bombs. There is another feature that would be great to upgrade to; it is pid subsystem in cgroup, which is on its way to the kernel.

It seems that they have renamed their branch too. So it is now aufs4-standalone: https://github.com/sfjro/aufs4-standalone/tree/aufs4.0

Does it seem right?

**Comment by tianon** [comment]
Yeah, figures.  I should've checked http://aufs.sourceforge.net/ instead of
just the aufs3-standalone repo! :+1:

**Comment by frol** [comment]
@tianon will be there an official release with 4.0 kernel?
