### ISSUE TITLE
boot2docker Persistent partition VM

### ISSUE THREAD

**Issue by irom77** [boot2docker/boot2docker#866]
I booted my ESXi VM and all is fine until I disconnect ISO.. I have  I have  partition labeled boot2docker-data, see below ?
docker@boot2docker:~$ blkid
/dev/sr0: UUID="2015-04-16-19-53-03-00" LABEL="Boot2Docker-v1.6.0" TYPE="iso9660" PTTYPE="dos" 
/dev/sda1: LABEL="boot2docker-data" UUID="b76e4da6-4940-4101-a510-926ea6a20641" TYPE="ext4"

**Comment by SvenDowideit** [comment]
boot2docker is a livecd distro that boots from the iso.

so the question is what do you mean by 'not-fine'

**Comment by irom77** [comment]
right, I uploaded iso to datastore and now it boots correctly;) But I was confused with static address not surviving reboot until I used /var/lib/boot2docker/bootlocal.sh instead /opt/bootlocal.sh for setup, thnx
