### ISSUE TITLE
How to run boot2docker in Linux

### ISSUE THREAD

**Issue by Tim-HU** [boot2docker/boot2docker#869]
Just to be clear, the answer to this question is not: "you can simply run docker without boot2docker VM."

Running boot2docker is Mac and Win is great, because running docker with "real" root privilege is no longer necessary.

This issue report is more like a feature that is very easy to have, and dramatically benefit boot2docker:
(Return on Investment is high)
Let's allow boot2docker to run on Linux.
Conceptually it seem not really difficult, just need to build the source code on Linux?
But please kindly illuminated me if I am wrong.

**Comment by bezerker** [comment]
In my use case, simply grabbing the boot2docker cli was all that was necessary as long as virtualbox is installed.  

The only thing that didn't work as it did on mac was the volumes. Volumes were not passed to my host but only to the virtualbox guest.

**Comment by SvenDowideit** [comment]
I'm going to close this. `boot2docker` has always worked on Linux - It is mostly developed and tested there - the only problem is the vbox shares, and this may become better in the 1.7 release.
