### ISSUE TITLE
docker run won't work on windows

### ISSUE THREAD

**Issue by cgcgbcbc** [boot2docker/boot2docker#870]
In windows, `docker run [option] image [command]` not work because it tries to find command in the host, not in the container. i.e. `docker run image /some.sh` will result in cannot find `C:\Users\user\some.sh`

**Comment by thaJeztah** [comment]
Looks like this is related to https://github.com/docker/docker/issues/12751#issuecomment-96288101 and https://github.com/docker/docker/issues/12590#issuecomment-95370211

> [...] It's happening due to msys, it converts unix paths to windows paths before passing them to docker.exe. In this case, that's not a docker bug. (it's not a msys bug either, it's by design.)
>See comments in #12590 to run it correctly, or use cmd.exe or powershell to not to have this problem.

**Comment by cgcgbcbc** [comment]
Depressed that I didn't find that issue even after a long searching... Thank you very much!

**Comment by thaJeztah** [comment]
@cgcgbcbc You're welcome; I remembered it because the behavior surprised me as well.
