### ISSUE TITLE
top command don't work any more

### ISSUE THREAD

**Issue by marcomsousa** [boot2docker/boot2docker#871]
With the new version boot2docker.iso 1.6.1 the top command not work.

> docker@boot2docker:~$ top
> top: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory

**Comment by arohter** [comment]
Confirmed :(

**Comment by jamshid** [comment]
And it's not fixed in boot2docker 1.6.2.
FYI you can install libncurses with this, though you'll have to redo it whenever you restart boot2docker:
```
$ docker-machine ssh
...
docker@dev:~$ top
top: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory
docker@dev:~$ tce-load -wi ncurses
Downloading: ncurses-common.tcz
...
docker@dev:~$ top
terminals database is inaccessible
docker@dev:~$ TERM=vt100 top -c  # works and displays full command line
```

**Comment by SvenDowideit** [comment]
This must have been an implied requirement for some other tool - its quietly working again in my master / pre-1.7 builds, but I'll add it in explicitly

**Comment by josephpage** [comment]
Got the same (1.6.2)
