### ISSUE TITLE
Multiple B2D instances on same PC and multi-host containers

### ISSUE THREAD

**Issue by bergtwvd** [boot2docker/boot2docker#890]
How can I let containers communicate with each other, that are loated in different Virtual Box Boot2Docker instances, but running on the same Windows 7 PC?

Currently I do the following (but for unknown reasons this does not work fully):

VirtualBox (VB):
- I use 2 VB instances (as example), with B2D.
- I set the VB network adapter #2 on each VB instance to Host-Only (leaving adapter #1 as NAT); IP address of host adapter is e.g. 192.168.56.1/24 for VB1, and 192.168.59.1/24 for VB2.
- consequently, on Windows IP routes are configured (by VB) for communication between the VB instances.

B2D:
- On each BD2 instance I change the docker0 IP address to an adress that is in the same subnet as the host adapter of the VB instance (by editing /var/lib/boot2docker/profile and adding EXTRA_ARGS='--bip=<ip address>/24'
- I attach eth1 to the docker0 bridge (via: brctl addif docker0 eth1)
- I remove the ip route to eth1 (via: ip route del < ip address >/24 dev eth1)
- I remove the Docker masquerading rulefor container addresses (via: iptables -t nat -F POSTROUTING)

I am able to:
- ping docker0, and any subsequent containers in either VB instance from the Windows DOS shell
- ping docker0, and any subsequent containers in either VB instance from the main shell of the other VB instance

But I CANNOT:
- ping between containers in different VB instances !
- ping between a container and its docker0 bridge IP !

All IP addresses used are unique, and I am puzzled why the last two bullets are not working.

What do I miss?

-- Tom

**Comment by jakirkham** [comment]
Were you ever able to figure this out?

**Comment by bergtwvd** [comment]
One way to do this is via direct routing as described on:
http://blog.sequenceiq.com/blog/2014/08/12/docker-networking/

**Comment by jakirkham** [comment]
So, I could be wrong, but I think this is the domain of ` docker machine`.
