### ISSUE TITLE
which linux-headers package to install in a docker image?

### ISSUE THREAD

**Issue by giodegas** [boot2docker/boot2docker#897]
I need to install a linux-headers package inside by ubuntu-based docker image.
[Here](http://gist.github.com/giodegas/7649c60721b03ea463ef) all the info I can get from my current boot2docker configuration.

```
apt-get install linux-headers-???
```

**Comment by SvenDowideit** [comment]
we build our own kernel during the creation of boot2docker so the right place to get it is probably a case of getting the GH repo for the release you're working with, and building it locally - then grabbing the headers from the final build container.

I wonder if we should be adding source & header snapshots to the releases

**Comment by giodegas** [comment]
I need to build the VirtualBox Guest Additions (VBA) in order to have X apps use the underline graphics card at the best. 
An alternative would be to have the VBA installed at the boot2docker level.
( I read last year discussions about VBA in boot2docker to have shared folders, but did not found any discussion about VBA to optimize X with OpenGL).
Having the possibility to build VBA inside the docker image would be nice.

**Comment by ivotron** [comment]
> I wonder if we should be adding source & header snapshots to the releases

@SvenDowideit that would be awesome. Currently, I'm doing:

```bash
docker-machine ssh dev \
  "sudo sh -c 'wget https://gist.githubusercontent.com/ivotron/131629dc8b144f015397/raw/0dfd80e9e1d16be0663e20c9ca33d7737f7afbde/install-headers.sh -O - | sh'"
```

The [gist](https://gist.github.com/ivotron/131629dc8b144f015397) is loosely based on the [Dockerfile](https://github.com/boot2docker/boot2docker/blob/v1.10.2/Dockerfile) (I don't mess with AUFS stuff). I also use [an image](https://hub.docker.com/r/ivotron/alpine-build-base/) with all the build dependencies for building. Then, for containers needing the headers:

```bash
docker run --rm -ti \
  -v /usr/src:/usr/src \
  -v /lib/modules:/lib/modules \
  -v /linux-kernel:/linux-kernel \
  debian:jessie
```

with the caveat that I need to do `make -C /linux-kernel/ scripts` sometimes (e.g. when switching from alpine to debian-based distros), not sure why.
