### ISSUE TITLE
User namespaces broken (&enable DoS) on kernel 4.0.4

### ISSUE THREAD

**Issue by ewindisch** [boot2docker/boot2docker#902]
The current kernel chosen by b2d has a DoS in user namespaces. Docker doesn't use this out of the box today, but some users use it and it does enable a denial of service attack.

All kernels from 4.0.2 through 4.0.4 are affected. A patch is expected for Linux 4.0.5

**Comment by tianon** [comment]
Any idea how long it'll be before we see 4.0.5?  Got a link to a bug or
mailing list thread upstream?

**Comment by ewindisch** [comment]
http://seclists.org/oss-sec/2015/q2/589

**Comment by tianon** [comment]
Thanks! :heart:

**Comment by tianon** [comment]
Hmm, I'm looking at [the changelog for 4.0.5](https://www.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.0.5) and not seeing the fix -- did I miss something?

**Comment by ewindisch** [comment]
They're there:

commit ef20854f7600f5019f1869fb331f73281f834257

commit 9993cbfde223f91ad29c5d002f6711fceff75219

**Comment by tianon** [comment]
Ahh, nice -- doesn't mention namespaces so I was thrown for a loop
wondering if it might be those two. :+1:
