### ISSUE TITLE
eval "$(boot2docker shellinit)" does not work via subprocess in Python 2.7 on Win7-64bit

### ISSUE THREAD

**Issue by chouclee** [boot2docker/boot2docker#909]
Env: Win7-64, python2.7 boot2docker-cli v1.6.2
Problem: each time I open a new git bash session, I need to type eval "$(boot2docker shellinit)", otherwise I would get error 
![capture](https://cloud.githubusercontent.com/assets/3389485/7972153/0b24541e-09ff-11e5-82d0-8e790f9a1be4.PNG)
Typing the command directly in bash command window could solve this problem.

Reproduce: If this command is executed with subprocess in Python:
cmd = [r'C:\\Program Files (x86)\Git\bin\bash.exe',  '-c', 'eval "$(boot2docker shellinit)"']
subprocess.call(cmd)

The command would not produce any errors and have the same output as working ones. But actually it does not have any effect.
![capture2](https://cloud.githubusercontent.com/assets/3389485/7972310/455b6f04-0a00-11e5-869f-e074ac742cbd.PNG)

BTW. directly typing boot2docker shellinit in git bash also doesn't work.

Did I miss something?

**Comment by edmorley** [comment]
I got this too - you have to convert the path in DOCKER_CERT_PATH to use an msys format path, ie:
``export DOCKER_CERT_PATH='/c/Users/zhoucli/.boot2docker/certs/boot2docker-vm'``

This does seem like a bug though - shellinit should output the correct format path.

**Comment by edmorley** [comment]
Sorry ignore the above, I misread the OP - my issue turned out to be boot2docker/boot2docker-cli#369.

**Comment by chouclee** [comment]
I guess my problem could be a python issue. I'm wondering does anyone else have met this problem before?
