### ISSUE TITLE
Docs: Make it clearer that only /var/lib/{boot2docker,docker} is persisted after reboot

### ISSUE THREAD

**Issue by edmorley** [boot2docker/boot2docker#912]
On Windows, using boot2docker 1.6.2, when I perform a ``boot2docker.exe restart``, the state of the VM isn't persisted (eg my modifications to .ashrc are gone, as is the python/pip/docker-compose install that I added).

This behaviour seems unexpected (it should just be doing a reboot, right?), and isn't mentioned on the boot2docker.exe help page:
```
   restart             Gracefully reboot the VM.
```

Is this intentional, or a bug?

**Comment by thaJeztah** [comment]
I'm not very profound in working with Boot2Docker, but you may check the "persistent partition" section here https://github.com/boot2docker/boot2docker/blob/master/doc/FAQ.md

**Comment by edmorley** [comment]
I created the VM using ``boot2docker init`` which is what https://github.com/boot2docker/boot2docker#persist-data says to do, however the data was not persisted. I suspect this is broken on Windows only?

**Comment by thaJeztah** [comment]
@edmorley honestly, no real idea here :smile: I'm quite a B2D n00b (should be working on that), I just pointed to that section, because I know some people weren't aware of that :wink:

**Comment by edmorley** [comment]
Appreciate the help! :-)

Looking closer, my ``boot2docker.exe restart`` **has** persisted the /var/lib/{boot2docker,docker} directories, but has wiped everything else.

The [persist-data section](https://github.com/boot2docker/boot2docker#persist-data) in the readme says:
```
When you run boot2docker init, the boot2docker tool auto-creates a disk that will be automounted and used to persist your docker data in /var/lib/docker and /var/lib/boot2docker. This virtual disk will be removed when you run boot2docker delete. It will also persist the SSH keys of the machine.
```
To me that doesn't imply "if you reboot the VM, you'll lose everything apart from what is in  /var/lib/{boot2docker,docker}".

The [Local Customisation](https://github.com/boot2docker/boot2docker/blob/master/doc/FAQ.md#local-customisation-with-persistent-partition) section in the FAQ doesn't warn about this either. 

If this really is expected behaviour, perhaps we need to:
1) Add a "Only files under FOO will be preseved when the VM reboots" to the persist-data section of the readme.
2) Add a link from the persist data section of the readme to the "Local Customisation" section of the FAQ.
3) Change the "Local Customisation" wording from:
``If you have a persistence partition, you **can** make customisations...``
to something like:
``If you wish for customisations to be persisted after reboots, you must have a persistence partition, and edit files under FOO, since anything outside of there will not be persisted...``

**Comment by thaJeztah** [comment]
Well, the maintainers here welcome pull-requests :)

(Hm.. talking of which, I can't find a CONTRIBUTING.md)

But seriously, it sometimes takes a "fresh" user to spot omissions in the documentation, and (although I'm really a n00b here), I know it's much appreciated to correct things by creating a pull-request. Many times a pull-request makes it easier to discuss as well

So if you have the chance to create one, :+1:

**Comment by edmorley** [comment]
Happy to submit one - just wanted to make sure this definitely was expected behaviour before doing so :-)
