### ISSUE TITLE
elastic search on boot2docker

### ISSUE THREAD

**Issue by arpras** [boot2docker/boot2docker#919]
I was following the instructions here : http://www.maori.geek.nz/post/boot_2_docker_how_to_set_up_postgres_elasticsearch_and_redis_on_mac_os_x

When I try to do
docker pull dockerfile/elasticsearch

it fails with 

FATA[0002] Error: image dockerfile/elasticsearch:latest not found 

Is there any other suggested way to get elastic search ?

Thanks

**Comment by rmg** [comment]
According to [this blog post](http://blog.docker.com/2015/03/thirteen-new-official-repositories-added-in-january-and-february/), elastic search was turned into an "official" repo at the beginning of the year.

Based on the [elasticsearch](https://registry.hub.docker.com/u/library/elasticsearch/) page on docker hub, you should be able to do `docker pull elasticsearch`.

@arpras does that get you up and running?

**Comment by arpras** [comment]
Thanks.  I also tracked similar issue on 
https://github.com/dockerfile/elasticsearch/issues/44

Thanks again. Closing
