### ISSUE TITLE
Feature request: xhyve support

### ISSUE THREAD

**Issue by alfonsodev** [boot2docker/boot2docker#922]
Already request by @alisnic here https://github.com/docker/docker/issues/13841
as said in the issue it makes more sense to discuss here.
What do you think about it ? would it be feasible in short term ? pros / cons ?

**Comment by tiborvass** [comment]
I'm not exactly sure what xhyve needs from boot2docker, but if anything, I'm in favor of it :)

Please note that this repo is about the boot2docker distro itself, and although there used to be boot2docker-cli, the recommended approach today is to use https://github.com/docker/machine. I would love to have xhyve support in machine, but for that xhyve needs to mature a little and at least not cause kernel panics while other virtualization software is running :)

**Comment by alfonsodev** [comment]
I understand , hopefully one day we don't need that 
boot2docker/osx-installer checks for virtualbox existence because it's not needed.
Thanks for the replay!

**Comment by SvenDowideit** [comment]
I'm going to play with this a little during the hackathons thou - so there will be something more to play with :)
