### ISSUE TITLE
Virtualbox 5 Compatibility [RC released 1st of June]

### ISSUE THREAD

**Issue by darkjaguar** [boot2docker/boot2docker#940]
Virtualbox 5 RC1 was already released the 1st of June, bound to have the final version released soon.

Please start taking into consideration Virtualbox 5 support, as boot2docker is currently not compatible.

The current error displayed on usage:

    error: Unknown option: --synthcpu

**Comment by lypanov** [comment]
+1

**Comment by smithwinston** [comment]
+1

VirtualBox 5 was released today.

**Comment by soberstadt** [comment]
+1

**Comment by tianon** [comment]
Closing this in favor of #979 (which seems to be opened by @darkjaguar's alter-ego @jamespacileo :smile:).
