### ISSUE TITLE
Windows boot2docker restart incurs a cert mismatch

### ISSUE THREAD

**Issue by joebalt** [boot2docker/boot2docker#948]
Anytime I stop and restart the docker daemon vm on Windows 7 x64, I am unable to run anything any more.

The only solution I have found so far - painful - is to boot2docker.exe delete followed by boot2docker init again.

=>docker -v
Docker version 1.7.0, build 0baf609

=>docker run hello-world
An error occurred trying to connect: Post https://192.168.59.103:2376/v1.19/containers/create: x509: certificate is valid
 for 127.0.0.1, 10.0.2.15, not 192.168.59.103

**Comment by joebalt** [comment]
dup of https://github.com/boot2docker/boot2docker/issues/824

**Comment by jakirkham** [comment]
Interesting data point, I was wondering if this might also be a problem for Windows.
