### ISSUE TITLE
Invalid certificate connecting to daemon

### ISSUE THREAD

**Issue by aburnett** [boot2docker/boot2docker#953]
I just upgraded to 1.7 and it looks like a possible timing issue when starting the boot2docker VM. During startup the 192 interface isn't up when `docker -d` is started. I modified `/etc/init.d/boot2docker` to print the output of ifconfig during startup and this is what I see.

    1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
    2: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default 
        link/ether 3e:8b:d2:d2:5d:ec brd ff:ff:ff:ff:ff:ff
    3: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
        link/ether 08:00:27:fe:88:a1 brd ff:ff:ff:ff:ff:ff
        inet 10.0.2.15/24 brd 10.0.2.255 scope global eth0
           valid_lft forever preferred_lft forever
        inet6 fe80::a00:27ff:fefe:88a1/64 scope link tentative 
           valid_lft forever preferred_lft forever
    4: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
        link/ether 08:00:27:6a:7f:44 brd ff:ff:ff:ff:ff:ff
    -------------------
    Need TLS certs for boot2docker,127.0.0.1,10.0.2.15
    -------------------

This leads to the following error when trying to run docker

    An error occurred trying to connect: Get https://192.168.59.103:2376/v1.19/containers/json: x509: certificate is valid for 127.0.0.1, 10.0.2.15, not 192.168.59.103

**Comment by josephpage** [comment]
Have a look at this fix : https://github.com/boot2docker/boot2docker/issues/824#issuecomment-113904164

Duplicate of #824

**Comment by aburnett** [comment]
Duplicate of #824 
Fix in PR #411
