### ISSUE TITLE
Virtualbox 5.0 Compatibility - [Final version released]

### ISSUE THREAD

**Issue by jamespacileo** [boot2docker/boot2docker#979]
Virtualbox 5 has been finally released
https://blogs.oracle.com/virtualization/entry/oracle_vm_virtualbox_5_07

New stable Vagrant release using Virtualbox 5 is likely coming out tomorrow
https://twitter.com/mitchellh/status/619163221992189952

Current release of boot2docker is not compatible with Virtualbox 5.

**Comment by nathanleclaire** [comment]
https://github.com/docker/machine/pull/1496 makes it work with `docker-machine`, perhaps a similar change would be all that is needed for boot2docker-cli.

**Comment by tianon** [comment]
If that's accepted as the solution for Machine, I'd definitely be super +1
to adding that same change to boot2docker-cli, especially since it's such
an easy fix! :+1:

**Comment by methane** [comment]
https://github.com/boot2docker/boot2docker-cli/blob/master/virtualbox/machine.go#L661

**Comment by rodlogic** [comment]
Same issue here:
```
VBoxManage: error: Unknown option: --synthcpu
error in run: Failed to initialize machine "boot2docker-vm": exit status 1
```

**Comment by CpuID** [comment]
Upstream has merged https://github.com/docker/machine/pull/1496 now

**Comment by maguowei** [comment]
I have the same problem

**Comment by pengux** [comment]
Is there any workaround for this issue until the fix is merged?

**Comment by returnpathadmin** [comment]
@pengux: Current workaround that works for me is to not use `boot2docker` and instead use the latest unreleased `HEAD` for `docker-machine` via Homebrew:

```bash
$ brew install --HEAD docker-machine
$ docker-machine  -v
docker-machine version 0.4.0-dev (HEAD)
$ docker-machine create -d virtualbox boot2docker
$ eval $( docker-machine env boot2docker )
$ docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): darwin/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

**Comment by trinitronx** [comment]
@pengux: Current workaround that works for me is to not use `boot2docker` and instead use the latest unreleased `HEAD` for `docker-machine` via Homebrew:

```bash
$ brew install --HEAD docker-machine
$ docker-machine  -v
docker-machine version 0.4.0-dev (HEAD)
$ docker-machine create -d virtualbox boot2docker
$ eval $( docker-machine env boot2docker )
$ docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): darwin/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

**Comment by micheleorsi** [comment]
thanks @trinitronx, this workaround works for me!

**Comment by jamespacileo** [comment]
Thanks for sharing @trinitronx :)

**Comment by nikolay** [comment]
Yeah, time to abandon ship!

**Comment by nikolay** [comment]
@trinitronx Actually, even with `--HEAD`, I still get version v0.3, not v0.4. I uninstalled it and then installed on clean slate, but it still installs v0.3.

**Comment by Antillean** [comment]
@trinitronx, works for me!

@nikolay, maybe try a `brew update` first?

**Comment by nikolay** [comment]
@Antillean Yes, I did `brew update`, but I still get the old version even if it says it's `HEAD`.

**Comment by tianon** [comment]
See also https://github.com/boot2docker/boot2docker-cli/issues/374 for more discussion of the issue and https://github.com/boot2docker/boot2docker-cli/pull/373 for discussion of a concrete fix.

**Comment by tianon** [comment]
Also of note is that https://github.com/docker/machine/pull/1496 already fixed this in `docker-machine`, and if you haven't given `docker-machine` a try yet, you probably want to since it'll be the de-facto way to use boot2docker in the near future.

**Comment by trinitronx** [comment]
@nikolay:  Try `brew uninstall docker-machine;   brew clean;  brew update;  brew install --HEAD docker-machine`

**Comment by nikolay** [comment]
@trinitronx Nothing helps! I've done `brew cleanup -s` before, uninstalled and deleted everything left over, it still installs v0.3, and that's it.

**Comment by nikolay** [comment]
@trinitronx The only thing that actually helped is removing everything related to docker-machine in `/Library/Caches/Homebrew`!

**Comment by methane** [comment]
@nikolay Do you really try docker-machine instead of boot2docker?

**Comment by ksylvan** [comment]
What's the workaround for Windows? How do I get the head/unreleased version of docker-machine on Windows?

**Comment by ksylvan** [comment]
Never mind. I figured it out. Cloned the docker/machine repository on my Linux box and did:

    ./script/build -os=windows -arch=amd64
    Sending build context to Docker daemon 8.307 MB
    Sending build context to Docker daemon 
    Step 0 : FROM golang:1.4.2-cross
     ---> bbc500088baa
    [...]
    Removing intermediate container fc1cc69270bd
    Successfully built b7a90fe3c3a9
    Number of parallel builds: 4
    -->   windows/amd64: github.com/docker/machine

And the new docker-machine binary worked beautifully.
