### ISSUE TITLE
Problems on OSX Yosemite (10.10.4)

### ISSUE THREAD

**Issue by guybluebat** [boot2docker/boot2docker#980]
Recently I've been having trouble with boot2docker on my macbook air (running Yosemite 10.10.4); after running for a while, when I try to execute docker commands it gives me the following error:

Cannot connect to the Docker daemon. Is 'docker -d' running on this host?

If I run 'boot2docker status' it says it's running. If I stop, then start again it works again for a while. I haven't yet determined if it's a specific amount of time before it dies or if it's just random. I did previously have kitematic installed, but when I installed boot2docker I removed kitematic and also the kitematic VM from virtualbox. I also tried deleting and recreating the host only networks in virtualbox before deleting and recreating the boot2docker image, but it doesn't seem to have made a difference

I'm also semi-regularly getting an error when I build images:

Untar error on re-exec cmd: fork/exec /usr/local/bin/docker: cannot allocate memory

I'm not sure if it's related to my main problem, but I thought it worth mentioning here as well.

This is a really annoying problem as b2d is dying about every 20 minutes which makes it hard to do anything useful with my containers. Any ideas?

Thanks,
Guy

**Comment by denisinla** [comment]
Have you tried restarting boot2docker? 

```sh
$ boot2docker ssh 'sudo /etc/init.d/docker restart'
```

Also this article should help shed some light:

https://github.com/iMerica/boot2docker/blob/master/doc/WORKAROUNDS.md

**Comment by jakirkham** [comment]
Couple of thoughts:

1. Did you run `eval $(boot2docker shellinit)`?
2. Have you tried updating? There was the 1.7.1 release a few days ago.
3. Are you trying to run a bunch of memory intensive programs at once?

**Comment by denisinla** [comment]
Make sure you remember how you install boot2docker, either package binary or via homebrew.
When updating boot2docker this will matter when you see that your boot2docker version is not
up to date.

**Comment by guybluebat** [comment]
Hi guys, thanks for all the replies. I seem to have fixed this by updating to the latest b2d version (currently v1.7.1). So far I haven't experienced any more of the issues in this ticket.

**Comment by jakirkham** [comment]
Glad to hear that you got working.

**Comment by jakirkham** [comment]
Fixed by boot2docker/boot2docker#960.
