### ISSUE TITLE
Just not working, no matter what I try on 2 machines.

### ISSUE THREAD

**Issue by bweston92** [boot2docker/boot2docker#997]
I get the following on 2 machines, running this as administrator doesn't help either. `boot2docker init` also fails.

I've Google'd and tried a few things but still nothing, this is a fresh install as-well.

![image](https://cloud.githubusercontent.com/assets/1764057/8756894/ae92791e-2ccd-11e5-930d-143a9f041b2e.png)

**Comment by triagmas** [comment]
I have same error
C:\Users\triag>boot2docker -v init
Boot2Docker-cli version: v1.7.1
Git commit: 8fdc6f5
2015/07/18 12:39:47 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo boot2docker-vm --machinereadable
2015/07/18 12:39:47 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo boot2docker-vm --machinereadable
2015/07/18 12:39:47 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe list vms
2015/07/18 12:39:47 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe createvm --name boot2docker-vm --register
Virtual machine 'boot2docker-vm' is created and registered.
UUID: 2a1a0927-90ad-4ae0-9de4-55888aa02cf4
Settings file: 'C:\Users\triag\VirtualBox VMs\boot2docker-vm\boot2docker-vm.vbox'
2015/07/18 12:39:48 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo boot2docker-vm --machinereadable
2015/07/18 12:39:48 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe setextradata boot2docker-vm VBoxInternal/CPUM/EnableHVP 1
2015/07/18 12:39:48 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm boot2docker-vm --firmware bios --bioslogofadein off --bioslogofadeout off --bioslogodisplaytime 0 --biosbootmenu disabled --natdnshostresolver1 off --natdnsproxy1 off --ostype Linux26_64 --cpus 8 --memory 2048 --vram 8 --acpi on --ioapic on --rtcuseutc on --cpuhotplug off --pae on --longmode on --hpet on --hwvirtex on --triplefaultreset off --nestedpaging on --largepages on --vtxvpid on --vtxux off --accelerate3d off --uart1 0x3F8 4 --uartmode1 server \\.\pipe\boot2docker-vm --boot1 dvd
2015/07/18 12:39:48 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo boot2docker-vm --machinereadable
2015/07/18 12:39:48 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm boot2docker-vm --nic1 nat --nictype1 virtio --cableconnected1 on
2015/07/18 12:39:48 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm boot2docker-vm --natpf1 ssh,tcp,127.0.0.1,2022,,22
2015/07/18 12:39:48 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe list hostonlyifs
2015/07/18 12:39:48 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe list dhcpservers
2015/07/18 12:39:48 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe hostonlyif create
0%...
Progress state: E_FAIL
VBoxManage.exe: error: Failed to create the host-only adapter
VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended info not available)
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreate(struct HandlerArg *)" at line 70 of file VBoxManageHostonly.cpp
error in run: Failed to initialize machine "boot2docker-vm": exit status 1

**Comment by micnigh** [comment]
This looks very similar the docker machine issue below - though I'm not sure how to apply the same workaround to boot2docker
https://github.com/docker/machine/issues/1521

**Comment by bweston92** [comment]
Ok, I really wanted to get going with Docker but this is holding me up, any ideas?

**Comment by sakai135** [comment]
See if setting the values in the [boot2docker configuration](https://github.com/boot2docker/boot2docker-cli#configuration) works.

**Comment by bweston92** [comment]
@sakai135 how values do you want me to use? :confused:

**Comment by jakirkham** [comment]
Put the configuration values there in this file `~/.boot2docker/profile` (on Windows use the provided Git Bash to do this). Afterwards, you will need to recreate the VM from scratch as shown below.

    $ boot2docker poweroff
    $ boot2docker destroy
    $ boot2docker init
    $ boot2docker up

**Comment by triagmas** [comment]
In windows 10 profile not work.
Go to virtaul box -> main settings -> network -> VirtualBox host - settings and set this
```
host-only network host IP
HostIP = "192.168.59.3"

host only network network mask
NetMask = [255, 255, 255, 0]

host-only network DHCP server IP
DHCPIP = "192.168.59.99"

host-only network DHCP server enabled
DHCPEnabled = true

host-only network IP range lower bound
LowerIP = "192.168.59.103"

host-only network IP range upper bound
UpperIP = "192.168.59.254"
```
then
```
$ boot2docker poweroff
$ boot2docker destroy
$ boot2docker init
$ boot2docker up
```
Now it's working correctly

**Comment by aaronsturm** [comment]
@triagmas Thanks for the settings. I created a new network with those settings in Virtualbox and was able to finally get ```boot2docker init``` to work, but I still have an issue with ```boot2docker up```. What version of Virtualbox are you using?

Here is the output:
$ boot2docker up -v
Boot2Docker-cli version: v1.7.1
Git commit: 8fdc6f5
2015/07/30 10:30:17 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminf
o boot2docker-vm --machinereadable
2015/07/30 10:30:18 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe guestprop
erty set boot2docker-vm /VirtualBox/GuestAdd/SharedFolders/MountPrefix /
2015/07/30 10:30:18 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe guestprop
erty set boot2docker-vm /VirtualBox/GuestAdd/SharedFolders/MountDir /
2015/07/30 10:30:18 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe sharedfol
der add boot2docker-vm --name c/Users --hostpath C:\Users --automount
VBoxManage.exe: error: Shared folder named 'c/Users' already exists
VBoxManage.exe: error: Details: code VBOX_E_OBJECT_IN_USE (0x80bb000c), component SessionM
achine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "CreateSharedFolder(Bstr(name).raw(), Bstr(hostpath).raw()
, fWritable, fAutoMount)" at line 1020 of file VBoxManageMisc.cpp
2015/07/30 10:30:18 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe setextrad
ata boot2docker-vm VBoxInternal2/SharedFoldersEnableSymlinksCreate/c/Users 1
2015/07/30 10:30:18 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm b
oot2docker-vm --type headless
Waiting for VM "boot2docker-vm" to power on...
VM "boot2docker-vm" has been successfully started.
error in run: Failed to start machine "boot2docker-vm": exit status 1

Thanks!

**Comment by rj919** [comment]
@triagmas Thanks for the virtual host settings suggestions. Worked for me!
Running Windows 10, VirtualBox 5 and Boot2Docker 7
Ended up wasting a lot of time installing docker-master and looking on forums regarding VirtualBox mis-configuration to no avail. But, these settings and order of re-initialization were successful.

To clarify for others using a similar VirtualBox 5, settings can be found at:

Preferences > Network > Host-Only Networks > Edit

Adapter: 
IPv4 Address: 192.168.59.3 
IPv4 Network Mask: 255.255.255.0

DHCP Server:
Server Address: 192.168.59.99
Server Mask: 255.255.255.0
Lower Address Bound: 192.168.59.103
Upper Address Bound: 192.168.59.254

Thanks again.
